### ISSUE TITLE
[BUG] dedicated server crash

### ISSUE THREAD

**Issue by imreallybadatnames** [DaFuqs/Spectrum#1]
**Describe the bug**
Dedicated server crashes because entity types are not initialized.

Adding `SpectrumEntityTypes.registerClient();` to `onInitialize` method in `SpectrumCommon.java` fixed the issue.
**To Reproduce**
Just start up a dedicated server with spectrum.

**Expected behavior**
Not crash.

**Screenshots**
Not needed, it is easily reproducible and always happens no matter what.

**Comment by imreallybadatnames** [comment]
Unfortunately, the quick and dirty fix crashes the client, seemingly because the entity types are registered twice now(in common and client java files)

**Comment by imreallybadatnames** [comment]
Yep, removing the register call from the client init method fixed the issue.

**Comment by DaFuqs** [comment]
Did you actually build this thing yourself before the first actual release? I honestly feel honored, wow.

Yeah, those should definitely be registered both server and clientside. Thank you!

**Comment by DaFuqs** [comment]
If you have any kinf of feedlack whatsoever I am happy to hear it. 😁
