### ISSUE TITLE
Make Exuberance work on pickaxes :)

### ISSUE THREAD

**Issue by ariesclark** [DaFuqs/Spectrum#10]
https://github.com/DaFuqs/Spectrum/blob/756dc02ecc65ff051347c78b0b6c29d15711994d/src/main/java/de/dafuqs/spectrum/enchantments/ExuberanceEnchantment.java#L11

**Comment by DaFuqs** [comment]
I would love to see that!

Currently Vanilla is hardcoded to only support a single Enchantment Targets for an enchantment (mining tools, weapons, bows, crossbows, tridents, ...) I will see if I find any way around that.

**Comment by ariesclark** [comment]
> I would love to see that!
> 
> Currently Vanilla is hardcoded to only support a single Enchantment Targets for an enchantment (mining tools, weapons, bows, crossbows, tridents, ...) I will see if I find any way around that.

Perhaps internally you could register multiple of the same enchantment, just with different targets.

**Comment by CamperSamu** [comment]
Done :D
(waiting for approval:tm:)
(merged now)
https://github.com/DaFuqs/Spectrum/pull/18

**Comment by DaFuqs** [comment]
done. Ty for the contribution! :)
