### ISSUE TITLE
Weird Text on items/blocks

### ISSUE THREAD

**Issue by stubbz00** [DaFuqs/Spectrum#100]
I'm running All of Fabric 5 which includes Spectrum 1.4.2 and I'm seeing some strange text on certain blocks/items.  I've attached pictures of what I'm seeing.  

Does anyone know the cause for this
![Screenshot 2022-08-12 150418](https://user-images.githubusercontent.com/68363851/184427035-fb9dcb2f-0195-4e87-9482-4564ac8f9679.jpg)
![Screenshot 2022-08-12 150419](https://user-images.githubusercontent.com/68363851/184427045-62a7c1eb-2795-4b81-8de1-1c0b4324a486.jpg)
?

**Comment by DaFuqs** [comment]
ඞ

**Comment by DaFuqs** [comment]
This is very much by design.
Specteum uses a method I call Revelations, to gradually reveal new blocks and items to the player. As long as you do not reached enough Spectrum progression, you will not be able to see the blocks in their true form.
So do not worry, your game is not bugging out. :)

**Comment by stubbz00** [comment]
Ahh!.  Thank you so much
