### ISSUE TITLE
Consider Compressing Images

### ISSUE THREAD

**Issue by xanthian** [DaFuqs/Spectrum#101]
I ran the gui and block folders through a PNG compression app and saved 1.7mb
I know its not a lot in the grand scheme of things, but all helps to keep file size down :)

Tool used PNG Gauntlet.
Its free, doesn't reduce quality, just file size.
https://pnggauntlet.com/

**Comment by tambry** [comment]
[`oxipng -o max -Z`](https://github.com/shssoichiro/oxipng) is likely to yield even better results and can be easily ran recursively locally on many cores.

**Comment by Azzyypaaras** [comment]
NO no no do NOT fucking compress the images, compressed pngs are a fucking pain in the ass to import back into pixel editing software largely nulling the value of the repo as archival for the images. If anyone tries to make a texture pack or if for any reason the original files are lost and they need to be fetched from this compression would fuck that.

**Comment by xanthian** [comment]
> NO no no do NOT fucking compress the images, compressed pngs are a fucking pain in the ass to import back into pixel editing software largely nulling the value of the repo as archival for the images. If anyone tries to make a texture pack or if for any reason the original files are lost and they need to be fetched from this compression would fuck that.

what..
