### ISSUE TITLE
[BUG] Dimensions except the vanilla ones cannot be entered in the latest version

### ISSUE THREAD

**Issue by Jenny77** [DaFuqs/Spectrum#103]
This time I updated my mods,and tried to continue my building in a dimension from the mod Paradise Lost,but I happened to get stuck in Overworld,and realized that the portal cannot be used to teleport to that dimension. When I used the command block to see if I can get back to the dimension,I found that there are only 3 vanilla dimensions. Maybe there's something wrong with Revelationary Mod.

**Comment by DaFuqs** [comment]
That is a weird one. Does that happen in existing, or even new worlds?

**Comment by Jenny77** [comment]
In an existing world it does! But I haven't tried it in a newly-created world.

**Comment by Seceroth** [comment]
This is now affecting the AQM2 modpack, more info there: https://github.com/itsdinkd/AQM2/issues/104

**Comment by DaFuqs** [comment]
AQM2 made a fucky wucky.
I sadly could not reproduce it in other modpacks, so it might have resolved itself/with newest updates?
