### ISSUE TITLE
[Feature] 1.19

### ISSUE THREAD

**Issue by Mahadbaloch** [DaFuqs/Spectrum#109]
Is there a plan to update the mod to 1.19?

If so how long might it take. Really like the mod.

**Comment by DaFuqs** [comment]
I am on the finishing touches and playtesting as we write :)

**Comment by Mahadbaloch** [comment]
Awesome

**Comment by DaFuqs** [comment]
There you go!
https://www.curseforge.com/minecraft/mc-mods/spectrum/
https://modrinth.com/mod/spectrum/

**Comment by Jenny77** [comment]
Woah! How time flies! How progressive the work is! Maybe I shall make more textures in the last few days of my summer holiday!

**Comment by Mahadbaloch** [comment]
Will it work on 1.19 as well as 1.19.2?

**Comment by DaFuqs** [comment]
1.19.2 only, sorry!
