### ISSUE TITLE
[Feature] EMI support

### ISSUE THREAD

**Issue by Pirogiran** [DaFuqs/Spectrum#111]
Similar to REI, but with some handy features.
[https://www.curseforge.com/minecraft/mc-mods/emi](https://www.curseforge.com/minecraft/mc-mods/emi)

**Comment by DaFuqs** [comment]
EMI is really nice and I would like to support it. But adding support would take me at least a whole week of spare time.

If someone wants to help out with this one that would be great.

**Comment by Pirogiran** [comment]
> If someone wants to help

It's a shame that I only understand how to translate mods...

**Comment by fzzyhmstrs** [comment]
EMI support is far easier than REI, fwiw (what took me a week of struggling with REI took me a couple hours tops in EMI, and then polishing after that). I might open a PR at some point since you did call out help

**Comment by DaFuqs** [comment]
I would be very happy! And it would give me a nice starting point and reference to add support for all future recipe types.
