### ISSUE TITLE
[BUG] REI Compatibility

### ISSUE THREAD

**Issue by BSherb** [DaFuqs/Spectrum#113]
**Describe the bug**
Attempting to auto-fill recipes in altars results in an error message:
"Internal Error: Container Info does not exist on the server!"

**To Reproduce**
With REI(roughly enough items)
Have items for crafting
Open REI
Select item to craft
Click "Fill missing items"

**Expected behavior**
Expected items to go from inventory into altar

**Mod version**
1.5.2

**Comment by DaFuqs** [comment]
That should be fixed in the newest versions. Would you try it out with the newest version, please?

**Comment by BSherb** [comment]
I'll give it a try here in a bit, thanks for the quick response though!
