### ISSUE TITLE
[BUG] Spectrum compacting chest item duplication

### ISSUE THREAD

**Issue by dimspith** [DaFuqs/Spectrum#115]
**Describe the bug**
The compacting chest allows players to duplicate items that can be compressed. This happens when the final item (of 4 or 9) is placed in a different slot from the others. The chest then compresses it but leaves all other slots of the item intact. This can also be seen in the screenshots below.

**To Reproduce**
- Have more than 9 of an item that can be compressed.
- Add 8 in the compacting chest, in one slot or split upon multiple slots.
- Add all remaining items in another slot

**Expected behavior**
All 4/9 items should be compressed without leaving any behind.

**Mod version**
All of Fabic 1.5.1 - Spectrum 1.5.0

**Screenshots**
![2022-09-10_21-25](https://user-images.githubusercontent.com/51262483/189498212-35fef7cf-5eba-4d3f-849c-1d9e9fad8e35.png)
![2022-09-10_21-25_1](https://user-images.githubusercontent.com/51262483/189498214-4997c8cb-689e-44bb-89c9-1ff49a8e0e14.png)

**Comment by DaFuqs** [comment]
That is definitely something I should fix on my end. :)

**Comment by DaFuqs** [comment]
Fixed for upcoming version.
