### ISSUE TITLE
[BUG] Incompatible with Quilt

### ISSUE THREAD

**Issue by Sunconure11** [DaFuqs/Spectrum#116]
https://pastebin.com/7vHx32wn

**Comment by DaFuqs** [comment]
That does not look like a quilt incompatibility, but a mod accessing critical classes at a point where mods are not all initialized, still, causing casading errors though lots of mods.
arclight, maybe?

**Comment by Sunconure11** [comment]
This error is no longer an issue, but I see you are using incubus core. Apparently it has some compat issues.

https://github.com/LordDeatHunter/Alloy-Forgery/issues/69#event-7414419254

**Comment by DaFuqs** [comment]
Ah yes, it's Incubus Concern again.

**Comment by DaFuqs** [comment]
Resolved in newest release.
