### ISSUE TITLE
URGENT bugged chunk from trying to use fusion altar

### ISSUE THREAD

**Issue by LargerManZ** [DaFuqs/Spectrum#118]
**Describe the bug**
(this is on a server, for reference) While trying to craft onyx gem, I left the materials inside the altar and went underground to do something else and the chunk became uninhabitable and unloaded. I fell infinitely and had to TP out. The chunks stay unloaded with a server reset as well as numerous other attempts to fix it such as breaking the blocks, or nuking it.

**To Reproduce**
leave the materials to craft an onyx gem on a fusion altar for a while on a server, and while it's crafting you go underground so you can't see the sky the server was reset while it was on there, and that caused another person to not have the chunks load for them

**Expected behavior**
Obvious

**Mod version**
1.5.0

**Screenshots**
![image](https://user-images.githubusercontent.com/62466706/192127294-2fd30172-d061-49c5-bbac-259da00f6a51.png)

**Comment by Noaaan** [comment]
This issue is known, and should already be resolved in the latest versions of Spectrum. These are available for both 1.18 and 1.19

**Comment by LargerManZ** [comment]
alright I'll let the all of fabric team know cause that's the modpack the server is using
