### ISSUE TITLE
[BUG] fixing the bulb with a spirit instiller ate my bucket

### ISSUE THREAD

**Issue by DougStoker** [DaFuqs/Spectrum#121]
**Describe the bug**
it ate my bucket

**To Reproduce**
put dead bulb, vegetal, and a bucket on a spirit instiller

**Expected behavior**
leave an empty bucket in the item bowl

**Mod version**
Which version of the mod are you currently using?

spectrum-1.5.7-1.18.2-magic.jar

**Screenshots**

**Crash Report**
If it is a crash bug add your crash log here

**Comment by DaFuqs** [comment]
Fix will be included in next release. Ty for the report!
