### ISSUE TITLE
[BUG] Free enchanting

### ISSUE THREAD

**Issue by ouroborus** [DaFuqs/Spectrum#122]
**Describe the bug**
When using the enchanter to apply a book to an item, it's possible to remove the item before the process is complete. It appears the the enchantment is applied immediately (as can be seen by observing the enchantment glow) then the xp is drained over time. When the item is pulled off, the process terminates but the enchant remains.

**To Reproduce**
Put an enchanted book in the dish and put the xp widget in the table. Put the item in the table and then immediately remove it. Note the enchantment and the amount of xp used.

**Expected behavior**
No free enchantments. The enchantment should not be applied until the xp drain has completed.

**Mod version**
spectrum-1.5.2-1.18.2-magic.jar

**Comment by DaFuqs** [comment]
Fixed in 1.6.0
