### ISSUE TITLE
Can you use gender neutral pronouns 🥺 

### ISSUE THREAD

**Issue by ghost** [DaFuqs/Spectrum#123]
https://github.com/DaFuqs/Spectrum/blob/7e2e6079aab09d60bd78635e0daf54cf6470f25d/src/main/resources/assets/spectrum/lang/en_us.json#L163

(basically requesting he be changed to they)

Alternatively can avoid pronouns entirely by swapping to `%s was not invited, but understood too late`

**Comment by DaFuqs** [comment]
how did I miss that. Yes, definitely

**Comment by DaFuqs** [comment]
Fixed in 1.6.0
