### ISSUE TITLE
[BUG] No recipe available for Fanciful Tuff Ring

### ISSUE THREAD

**Issue by anagram3k** [DaFuqs/Spectrum#126]
The recipe for Heartsinger's Reward requires a "Fanciful Tuff Ring". Shift-click to the recipe redirects to Fanciful circlet. There is no available recipe to craft the ring.

**Mod version**
spectrum-1.5.7-1.18.2-magic

Obs: I am playing All of Fabric 5

**Comment by anagram3k** [comment]
After crafting the refined azurite, the recipe did appear.

**Comment by DaFuqs** [comment]
Fixed in next version. Thank you!
