### ISSUE TITLE
[BUG] Infusing color on items don't work after a certain level

### ISSUE THREAD

**Issue by anagram3k** [DaFuqs/Spectrum#127]
**Describe the bug**
The items "Heartsingers' reward" and "Gloves of Dawn's Grasp" can be infused with color to improve stats, but after a certain level the infusing stops,

**Expected behavior**
The infusing should continue.

**Mod version**
spectrum-1.5.7-1.18.2-magic

Obs: I am running All of Fabric 5 modpack

**Screenshots**
![Screenshot_20221023_222516](https://user-images.githubusercontent.com/76353/197430180-bad826e1-2f72-4fa7-aa5a-bdde9c969994.png)

![Screenshot_20221023_222501](https://user-images.githubusercontent.com/76353/197430196-016e8f52-19e7-41b1-a03d-124fa620b11d.png)

![Screenshot_20221023_222429](https://user-images.githubusercontent.com/76353/197430226-7bc76d3b-ca62-4d19-a2fb-2213a8f5ffee.png)

**Comment by DaFuqs** [comment]
Looking at your screenshots you may have activated the color filter?
The icon above the output slot indicates the color that will get put into the Trinket. You have selected light blue (?), so the color picker will only try to ouotput light blue into the output slots items. Click onto that color square to clear it and allow the color picker to fill containers will all colors again.

Additionally to that, the Color Picker will only fill items in the output with color when the amount in the picker is greater than the amount in the trinket.

**Comment by anagram3k** [comment]
Yes, I changed the filter but forgot to do that in the screenshot, but I didn't know the amount in the picker should be greater than the amount in the trinket. It is working as expected.

Maybe this should be clearer in the book. Something like "Infusing is a difficult process and the item can buildup a resistance to the color".

Anyway, your mod is amazing. It is really a hidden gem.

**Comment by DaFuqs** [comment]
Thank you! I appreciate it.
I agree the guidebook can use a sentence on that
