### ISSUE TITLE
[BUG] Enchantmentless enchanted books

### ISSUE THREAD

**Issue by Igno-miny** [DaFuqs/Spectrum#129]
**Describe the bug**
When midnight dipping enchanted books in order to disenchant them, they do in fact lose their enchantments. However, they do not lost the title of 'enchanted' books.

**To Reproduce**
1. Throw an enchanted book with an enchantment, such as impaling, into midnight solution.
2. Wait for ~30 seconds
3. Retrieve the enchanted books, which are still *technically* enchanted books despite having no enchantment applied.

**Expected behavior**
The books would become normal books.

**Mod version**
1.5.7, in minecraft version 1.19.2

**Screenshot**
Image of resulting book:
https://ibb.co/C78zTjy

**Crash Report**
Not applicable.

**Comment by Igno-miny** [comment]
Further testing also seems to reveal that this results in no dropped EXP. Weird.

**Comment by DaFuqs** [comment]
Fixed in 1.6.0
