### ISSUE TITLE
[BUG] Quitoxic Reeds seemingly not able to spawn whatsoever.

### ISSUE THREAD

**Issue by Pathos951** [DaFuqs/Spectrum#131]
**Describe the bug**
Could be a product of the modpack, (AOF5) but I have searched and searched for hours on end through vanilla swamp biomes and have not seen a single reed spawning naturally.

**To Reproduce**
Attempt to find these damn reeds in AOF5.

**Expected behavior**
I was hoping to see some spawning on clay deposits like pictured in the in-game documentation.

**Mod version**
v1.5.7

**Comment by togreglove** [comment]
Also seems to be the same issue on Dreamcraft. It may be that the biome mod, Terralith has fundamentally changed the way swamps work? Maybe there's no spawn spots with clay or mud? No clue, but figured I'd let you know as much info as I had.

**Comment by tabstop2** [comment]
this is a known issue w/ terralith. the way it messes with worldgen prevents quitoxic reeds from spawning

**Comment by Pathos951** [comment]
Update:

Going into the in-game config and turning the spawn value for the reeds up by 10x (I was desperate) and then using the Nature's Compass to locate a BYG Bayou Biome, which was listed in the config as a valid spawn biome for Quitoxic Reeds, I did eventually find some. It took a worrying amount of searching even with the spawn chances all the way up but there is at least a workaround.

So glad I'm able to continue with this amazing mod.

**Comment by DaFuqs** [comment]
Yes, like tapstop2 said, is an unlucky state of affairs when combined with Terralith. The swamps are much deeper than vanilla swamps, greatly reducing clay spots in shallow water. Not much I can do on this front.
Bumping up the generation chances seems like a nice workaround in that case, very good!

Alternatively, using the newest Spectrum 1.6.0+ also contains them in one of the new puzzle structures as fallback.

**Comment by Pathos951** [comment]
Hey thanks for the quick response, just looked at the 1.6.0+ changes, nice to see you accounting for all use cases of the mod.

Definitely becoming an auto-include in any future Fabric modpacks.
