### ISSUE TITLE
[BUG] Can't equip trinkets

### ISSUE THREAD

**Issue by DanDragonWolf** [DaFuqs/Spectrum#133]
**Describe the bug**
I am not able to equip anything that would go into a trinket slot from this mod.

**To Reproduce**
Get something like the Radiance Pin and try to put it in the pin slot or the Potion Pendant and try to put it in the Necklace slot

**Expected behavior**
For Trinket slot items to be equipable

**Mod version**
1.6.2

**Comment by DaFuqs** [comment]
Do you have the advancements that would allow you to craft these trinkets?

**Comment by DanDragonWolf** [comment]
No, I grabbed them from creative. So I need the advancements to equip them?

**Comment by DaFuqs** [comment]
Yes, correct. If you just try out stuff in creative you can use the /advancement command to grant yourself all advancements and you will be good to go

**Comment by DaFuqs** [comment]
I believe this mystery is solved
