### ISSUE TITLE
[BUG] Collision with the "Croptopia mod" on most recent version of spectrum

### ISSUE THREAD

**Issue by XeroXavion** [DaFuqs/Spectrum#134]
**Describe the bug**
Recently spectrum had a new update. (1.6.2) whatever it was has caused compatibillity issues with "Croptopia." The mod works fine up until I right click a crop, which closes the client after freezing. 

Tested this on a server, only the client crashes.

I've already sent this issue to the croptopia github but i'm covering it here too incase its an issue on this side

This bug occurs on **only** the most recent version of spectrum. other versions do not replicate this issue

**To Reproduce**
Install croptopia's most recent version and spectrum's most recent version for 1.19.2 fabric, then grow a crop from the mod (like corn), use bonemeal to make it mature and right click once it is fully grown. 

**Expected behavior**
What is meant to happen is that croptopia's crops can be harvested by right-clicking, removing the need to break the crops. right clicking the crop should drop the crop and also some seeds. what happens currently is that the game freezes, and the client who right-clicked promptly crashes.

**Mod version**
1.6.2 in 1.19.2 of fabric
fabric api version is 0.67.1

**Screenshots**
None needed.

**Crash Report**
Opening the vanilla client after the modded client crashed gave me a crash report:
[Crash report 001.txt](https://github.com/DaFuqs/Spectrum/files/10094532/Crash.report.001.txt)

**Extra info**
The issue can be resolved by going down a version but this may affect future updates so I just wanted to be sure that this was known.

Croptopia mod page link: [Link](https://www.curseforge.com/minecraft/mc-mods/croptopia)

**Comment by DaFuqs** [comment]
Croptopia calls the afterBlockBroken() method on both client and server. This method should only ever be run serverside
https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/8bb89cf46d971d1bc079e41f401578d8aa46c3e2/shared/src/main/java/com/epherical/croptopia/blocks/CroptopiaCropBlock.java#L76

I will put in a work around on my side, but that definitely should be changed on Croptopias side, too.

**Comment by XeroXavion** [comment]
I see, I'll notify their side about this then, thank you for your time

**Comment by DaFuqs** [comment]
perfect, thank you!
