### ISSUE TITLE
Conflict with Immersive Portals is back on new version

### ISSUE THREAD

**Issue by oldjollysanta** [DaFuqs/Spectrum#135]
**Describe the bug**
After updating spectrum it now crashes on launch. Removed Immersive Portals and it launches correctly.
Was working on spectrum-1.5.7-1.19.2-magic with Immersive Portals

**To Reproduce**
Install Immersive Portals + the latest version of spectrum (spectrum-1.6.3-1.19.2-leisure_time)

**Mod version**
spectrum-1.6.3-1.19.2-leisure_time

**Crash Report**
[crash-2022-11-29_11.19.47-client.txt](https://github.com/DaFuqs/Spectrum/files/10108912/crash-2022-11-29_11.19.47-client.txt)
[2022-11-29-7.log](https://github.com/DaFuqs/Spectrum/files/10108903/2022-11-29-7.log)

**Comment by DaFuqs** [comment]
fixed.
