### ISSUE TITLE
[BUG] Spectrum trees lose their color

### ISSUE THREAD

**Issue by Tomatobird8** [DaFuqs/Spectrum#136]
Colored oak trees lose their biome specific foliage color when joining a world where you havent progressed so far to see their real colors. This occurss **after** switching from a world where you have progressed so far to see them.

**To Reproduce**
> Join a world where you can see the true colors of spectrum trees
> Leave and join one where you can't see them
> The leaves turn gray

**Expected behavior**
Leaves should be colored to the biome foliage color rather than no color.

**Mod version**
v1.6.3-1.19.2 (tested on All of Fabric 6 v0.1.7)

**Screenshots**
![image](https://user-images.githubusercontent.com/60841151/205120064-8cdd248a-6ba8-4ac5-b661-4706d3aa8ca3.png)

**Comment by DaFuqs** [comment]
fixed.
