### ISSUE TITLE
[BUG] Drinking tea with scone in hotbar crashes game.

### ISSUE THREAD

**Issue by Clonephaze** [DaFuqs/Spectrum#137]
**Describe the bug**
Attempted twice in a row, when I attempted to drink demon tea with a scone in my hotbar the game crashes with "Cannot invoke "net.minecraft.class_4174.method_19230()" because "foodComponent" is null" as the reason. Oddly the scone was gone but the tea was not when I relaunched the game, but I also got a bottle from the tea both times. 

**To Reproduce**
Drink tea with scone in hotbar.

**Expected behavior**
Advancement achieved without crashing, tea gone and scone still ready to eat. 

**Mod version**
spectrum-1.6.3-1.19.2-leisure_time

**Crash Report**
[crash-2022-12-01_18.05.49-server.txt](https://github.com/DaFuqs/Spectrum/files/10137561/crash-2022-12-01_18.05.49-server.txt)

**Comment by DaFuqs** [comment]
Fixed in next version. In the meantime always drinnk tea with at least 2 scones. :)
