### ISSUE TITLE
[BUG] Infinite gunpowder

### ISSUE THREAD

**Issue by EleiteRanger** [DaFuqs/Spectrum#138]
**Describe the bug**
When midnight aberrations are put into a bottomless bundle, you just keep getting gunpowder without losing any aberrations. This seems to be specific to the bottomless bundle, as when putting it in simple backpack's simple bundle or vanilla's bundle, you don't get infinite gunpowder.

**To Reproduce**
Put at least 1 midnight aberration into a bottomless bundle and wait.

**Expected behavior**
Either not getting gunpowder, or losing midnight aberrations in bottomless bundles.

**Mod version**
spectrum-1.6.3-1.18.2-leisure_time.jar

**Comment by DaFuqs** [comment]
Fixed in next release
