### ISSUE TITLE
[Feature] Make all budding blocks craftable with budding onyx's recipe but their block instead of an onyx block

### ISSUE THREAD

**Issue by EleiteRanger** [DaFuqs/Spectrum#139]
Currently the only renewable budding block is onyx, and adding this would make them renewable and wouldn't feel out of place or break game balance.

**Comment by DaFuqs** [comment]
The other gemstones can easily be farmed using Crystal Apothecaries in huge amounts and gives players a good reason to leave their base once in a while.
Any specific pro for making the other budding blocks craftable, that I am not seeing, currently?

**Comment by samudec** [comment]
Also other buddings are available in the last dungeon chest (at least it was in 1.5.7, idk about the later versions)

**Comment by Sparkezel** [comment]
not having to explore a lot of undergrounds for more blocks, also the ability to just put them all into one place, not more than that I guess.

**Comment by Red6785** [comment]
The only real pro I can think of is basically anti-griefing, but on most servers you've got some of form of that anyways. While this would be nice, I don't see much of a point, and you could always add custom recipes if you really want to.

**Comment by DaFuqs** [comment]
I have an idea for that. But it will take an update or two :)
