### ISSUE TITLE
[BUG] Midnight solution should be able to put copper items into their next state, only works up to exposed. 

### ISSUE THREAD

**Issue by Clonephaze** [DaFuqs/Spectrum#140]
**Describe the bug**
Midnight dipping should allow base copper -> exposed copper -> weathered copper -> oxidized copper. Midnight dipping only works 
for base copper -> exposed copper. Throwing exposed copper in does nothing, along with throwing in weathered copper.

**To Reproduce**
Throw exposed copper anything in midnight solution and watch nadda happen. 

**Expected behavior**
Copper items should run through their states like listed in REI

**Mod version**
spectrum-1.6.3-1.19.2-leisure_time.jar

**Screenshots**

![Exposed copper in solution](https://user-images.githubusercontent.com/6809805/205837237-91482705-7a39-463b-a4f8-e64e4902d00d.png)
![Exposed copper in inv](https://user-images.githubusercontent.com/6809805/205837240-b0f94ff9-e7da-4554-ba42-21dbbf88020d.png)

**Comment by DaFuqs** [comment]
fixed.
