### ISSUE TITLE
[BUG] Glowing Phantom Frame

### ISSUE THREAD

**Issue by Fortist** [DaFuqs/Spectrum#141]
I made a few glowing phantom frames and after putting one up testing the look, I went to pick it up and it drops a REGULAR phantom frame when broken.

Im not sure if it has to do with what tool I was holding at the time, but it was a bedrock tool if it was.
MC 1.19.2 - 1.6.4 version

Gonna go mess around with it for a bit for more comprehensive testing.

**Comment by DaFuqs** [comment]
thank you!

**Comment by DaFuqs** [comment]
Fixed in 1.6.8
