### ISSUE TITLE
[Feature] Disable higher vanilla enchantment levels

### ISSUE THREAD

**Issue by inikishev** [DaFuqs/Spectrum#142]
Seems OP

**Comment by DaFuqs** [comment]
Which higher vanilla enchantment levels? Please elaborate

**Comment by inikishev** [comment]
> Which higher vanilla enchantment levels? Please elaborate

I installed this mod and villagers sell respiration 4 for example

**Comment by DaFuqs** [comment]
Spectrum does not touch Villager trades or vanilla max enchantment levels. Sure you are not thinking of an other mod?

**Comment by inikishev** [comment]
> Spectrum does not touch Villager trades or vanilla max enchantment levels. Sure you are not thinking of an other mod?

are you sure? I did a binary search on all enchantments that are affected, all of them were found in spectrum and most only in spectrum

**Comment by inikishev** [comment]
> Spectrum does not touch Villager trades or vanilla max enchantment levels. Sure you are not thinking of an other mod?

pretty suer it raises sharpness to 7, a lot of stuff like protection, looting to 5. Without it max levels are as they are in vanilla

**Comment by Red6785** [comment]
Does this happen with just spectrum?

**Comment by DaFuqs** [comment]
Yes, I am sure Spectrum does not touch villager trades, or enchantment max levels, at all.
The only means to get overleveled enchants would be via [Enchantment Upgrading](https://github.com/DaFuqs/Spectrum/wiki/Custom-Enchantment-Upgrade-Recipes) via the Spectrum Enchanter in combination with a specific, still unobtainable enchantment unlock.

**Comment by Red6785** [comment]
Or to take the overleveled enchantments off of bedrock tools.

**Comment by DaFuqs** [comment]
Oh yeah, that ^ :P

**Comment by DaFuqs** [comment]
I guess this is "solved", then?

**Comment by DaFuqs** [comment]
So, for completion: Amethyst Imbuement does it, if that's in your pack
