### ISSUE TITLE
[BUG] Viewing hints crashes the game in AQM2

### ISSUE THREAD

**Issue by xErrorAmelie** [DaFuqs/Spectrum#144]
**Describe the bug**
When you try to view a hint in the Spectrum Book, it will crash the game.

**To Reproduce**
Use the AQM2 Modpack and try to view a hint.

**Expected behavior**
Should view the hint without a crash.

**Mod version**
1.6.4 for 1.18.2

**Crash Report**
Latest.log: https://mclo.gs/B1sffFC
Crash-report: https://mclo.gs/mXIirii

**Comment by xErrorAmelie** [comment]
Could be, because of a mixin conflict with BetterThirdPerson?

**Comment by DaFuqs** [comment]
Patchouli either needs an up- or downgrade.

**Comment by xErrorAmelie** [comment]
Seems like the last patchouli update for 1.18.2 was about 6 months ago and we have that newest version. Would be weird if it needs a downgrade, but I can try it.

**Comment by DaFuqs** [comment]
The crash indeed stems from an outdated Patchouli API. From Spectrum 1.4.2-chaos-and-exploration back at the Jun 28:
> This release fixes the guidebook not working anymore due to a breaking change in Patchouli and contains a few other minor improvements & fixes. This version requires Patchouli >=1.18.2-71.1-FABRIC.

Currently, the pack only ships with an old version of Patchoili, namely:

> patchouli 1.18.2-66-FABRIC-SNAPSHOT via modern_industrialization

Adding the most recent version of Patchouli from CF will fix these crashes
