### ISSUE TITLE
[BUG] Brown/Black Sapling recipes not actually unlocking

### ISSUE THREAD

**Issue by ceasefyre** [DaFuqs/Spectrum#15]
**Describe the bug**
Achievement progression shows that necessary triggers hit:
```
"spectrum:progression/colored_saplings/unlock_brown_sapling": {
    "criteria": {
      "has_vegetal": "2022-01-01 16:00:46 +0000",
      "collected_onyx_shard": "2022-01-01 19:29:36 +0000",
      "collected_amethyst_shard": "2021-12-30 17:03:37 +0000",
      "collected_citrine_shard": "2022-01-01 06:32:13 +0000"
    },
    "done": true
  },
"spectrum:progression/colored_saplings/unlock_black_sapling": {
    "criteria": {
      "has_vegetal": "2022-01-01 16:00:46 +0000",
      "collected_onyx_shard": "2022-01-01 19:29:36 +0000"
    },
    "done": true
  }
```
However, recipes aren't showing in REI nor in Colorful World manual as unlocked.

**To Reproduce**
Suspect that when acquiring onyx shard from fusion, the unlock triggers didn't perform entirely?

**Expected behavior**
Upon acquiring the prerequisite items, saplings recipes should be available.

**Screenshots**

**Comment by DaFuqs** [comment]
For the recipe to unlock / be craftable you also (while now shown) need the advancement "Construct the Spectrum Temple". Do you have that one?
Like the crafting of the CMY Pedestal it is considered a major milestone, unlocking a new recipe tier, that these need.

**Comment by ceasefyre** [comment]
What is required for that advancement? I have constructed the multiblock (says 'complete'). Is that what is not registering properly then?

**Comment by DaFuqs** [comment]
Depends on what version of Spectrum you are running on. Are you on 1.2.0 Midgame1 or higher?
In versions before there is a blocker at this point, because lots of features were not done yet.
Otherwise just clicking onto the pedestal with the Onyx structure should do it.

**Comment by ceasefyre** [comment]
Yep, you replied literally as I was checking. I assumed (incorrectly) that because the pack was added to AoF5 recently, it would have been a more up to date version of your pack. Sure enough, it is only earlygame4... explains so much.
Thanks for the time to reply. Enjoying your mod so far!

**Comment by DaFuqs** [comment]
No problem at all! Have fun :)
