### ISSUE TITLE
[BUG] Cannot shift-click into the bottom right slot of a Pigment Pedestal

### ISSUE THREAD

**Issue by xijtsjis** [DaFuqs/Spectrum#150]
You can shift-click items out from the bottom right slot, but not in. Shift-clicking works as expected for every other slot in the crafting grid, and also for powders/crafting tablets into their specific slots.

**Mod version**
1.6.4-1.18.2-leisure_time

**Screenshots**

https://user-images.githubusercontent.com/49894915/212636063-b08d6fe3-f126-4200-abc7-6ab760629b77.mp4

**Comment by DaFuqs** [comment]
will be included in the next update. Thank you lots!
