### ISSUE TITLE
[BUG] Lanterns Become Waterlogged

### ISSUE THREAD

**Issue by MysticWolfy** [DaFuqs/Spectrum#155]
**Describe the bug**
We have Better End installed, and with the Iron Bulb Lanterns, there are other colors. When the color was changed with a paintbrush, the lantern became waterlogged.

**To Reproduce**
Have a hanging, colored, Iron Bulb Lantern. Have the paintbrush and select a different color to the lantern. Right Click the Lantern and it will change color and become water logged.

**Expected behavior**
The Lantern should only change color and not become waterlogged.

**Mod version**
spectrum-1.6.4-1.19.2-leisure_time.jar

**Screenshots**
![2023-01-18_10 55 35](https://user-images.githubusercontent.com/123000065/213222967-0253352b-3529-4f01-8298-fbfe3bddfa90.png)
![2023-01-18_10 55 45](https://user-images.githubusercontent.com/123000065/213222975-48d84c94-9c89-4758-8f78-2e4be4dba16e.png)
![2023-01-18_10 55 46](https://user-images.githubusercontent.com/123000065/213222983-e973ad0a-469e-4eaf-a99a-a2533e755f47.png)
![2023-01-18_10 55 48](https://user-images.githubusercontent.com/123000065/213222986-afcf464b-a21e-492c-8d9d-fe7fa7e139d8.png)

**Comment by DaFuqs** [comment]
Fixed in Spectrum's alpha builds.
