### ISSUE TITLE
[BUG] Incompatibility with newest incubus_core (1.9.4) 1.19.2

### ISSUE THREAD

**Issue by Gamerbolts** [DaFuqs/Spectrum#158]
**Describe the bug**
When creating a new world, it loads then goes to saving and crashes to desktop

**To Reproduce**
This is in my modpack which is not yet released to the public

**Expected behavior**
World to load

**Mod version**
1.6.5

**Screenshots**
n//a

**Crash Report**
[crash-2023-02-05_09.04.38-client.txt](https://github.com/DaFuqs/Spectrum/files/10611354/crash-2023-02-05_09.04.38-client.txt)
[latest.log](https://github.com/DaFuqs/Spectrum/files/10611355/latest.log)

Any help is appreciated. Thank you!

**Comment by DaFuqs** [comment]
This will be an easy fix. I'll keep you updated.

**Comment by Kasax007** [comment]
This issue also occurs in the newest Beta version of my mod pack Dreamcraft. It would be amazing if there is a quick fix for this since I need to update to a new version of spectrum to fix past issues of spectrum. 
[latest.log](https://github.com/DaFuqs/Spectrum/files/10734482/latest.log)

**Comment by DaFuqs** [comment]
Dreamcraft is a pack name I haven't heard in a good while. Is that the same Dreamcraft that had... strong opinions about Spectrum back in 1.18.1, or is the name a simple coincidence?
Fix will be out this weekend ✔

**Comment by Kasax007** [comment]
I have never said anything bad about spectrum as far as I can remember. In 1.19.2 it is one of my favorite magic mods because of its features. Has its own chapter in the quest book ;) 
Thanks for fixing the issue <3

**Comment by Kasax007** [comment]
Would it be possible for you to provide me with a preview version of the fixed mod so I can implement it? With the current newest version which is available on curseforge, I also can't boot old worlds for some reason. It just says something along the lines of data pack issues. It only happens when spectrum is in my mod list.

**Comment by DaFuqs** [comment]
Sure!
https://www.dropbox.com/s/dawdqkz5otr3f06/spectrum-1.7.0-deeper-down-alpha1.jar?dl=0
You will also find upcoming alpha builts in the Spectrum discord's preview channel

**Comment by Kasax007** [comment]
Thanks! All issues are fixed :) Old worlds and new worlds work. Can't wait for this version to be on curseforge so I can use it for the next update of my pack!

**Comment by DaFuqs** [comment]
Implemented in 1.6.6
