### ISSUE TITLE
the fuffing brown pigment

### ISSUE THREAD

**Issue by Gamercat09** [DaFuqs/Spectrum#166]
i have aLL of thE other colored pigments,(no grey, black or white[OR BROWN!!!!!]) i dont know how i've looked everywhere im fgoing insane
Send Help,
Gamercat09

**Comment by tabstop2** [comment]
craft a brown sapling to grow a brown tree, then break the leaves.

**Comment by Gamercat09** [comment]
I don't have the knowledge to do that yet

**Comment by Gamercat09** [comment]
I have just unlocked all said previous pigments, and that is as far as I have went

**Comment by imreallybadatnames** [comment]
what gemstones have you currently unlocked

**Comment by imreallybadatnames** [comment]
(hinting at the existence of more than the basic three, or just asking if you unlocked the 4th one if you already got to that point)

**Comment by imreallybadatnames** [comment]
anyways sending a screenshot of the advancement tree would be quite helpful in finding out the *exact* point of progress(since going as far as unlocking all other pigments doesnt affect the progression to the brown pigment)

**Comment by Gamercat09** [comment]
![2023-03-01_18 46 04](https://user-images.githubusercontent.com/103867279/222301711-6cbe7959-6ad9-4030-b149-50a6493c2c5a.png)
![2023-03-01_18 46 09](https://user-images.githubusercontent.com/103867279/222301716-637b5211-7400-438f-a70a-ac1a82522e40.png)

**Comment by Gamercat09** [comment]
I'm so stupid i haven't collected magenta pigment
Then again it was late

**Comment by DaFuqs** [comment]
Sounds like this is resolved, then :)
