### ISSUE TITLE
Brown pigment quest unfollowable

### ISSUE THREAD

**Issue by SHADOW-WOLF-FURRY** [DaFuqs/Spectrum#168]
So as playing thru the mod in all of fabric 6 I noticed that once you got to the brown pigment quest it requires you to craft brown pigment, but to do that you need onyx shards to upgrade the pedastal but to get onyx shards it requires the infusion alter which is only unlocked by the brown pigment quest completion. So basically wondering if that's intentional or not but it makes the quests unfollowable. So this is a request I guess to reverse the needed quest unlocks for those please.

**Comment by DaFuqs** [comment]
Quests in Quest Books are created by the modpacks team, so I can't help with how those are built.
Spectrum itself presents it's progression via Guidebook and Advancements, so those will likely help you out a lot.

Without knowing perfectly where you are standing in progression currently, your current goal might be to collect all of the Pigments minus Brown and the grayscale ones. This will unlock the Fusion Shrine. To get an overview which ones are missing still, take a look at the "Pigment" entry in the Colorful World guidebook.

**Comment by SHADOW-WOLF-FURRY** [comment]
i figured it out, i didnt see that i hadnt unlocked pink pingment yet
