### ISSUE TITLE
[BUG] Crafting tablet allows for duping some recipes

### ISSUE THREAD

**Issue by MobSlicer152** [DaFuqs/Spectrum#17]
**Describe the bug**
The crafting tablet makes some recipes, seemingly those that use the top left slot and result in a stackable item, give an extra item. This means things like ore blocks and anvils can be duplicated, allowing for infinite resources, especially with mods like Blockus that provide blocks of golden apples and such.

**To Reproduce**
Do a crafting recipe (the ones using the top left slot seem to work the best, but I haven't tested it too thoroughly) such as an ore block, then shift click the output slot (which doesn't show the new item, by the way). If you have an empty inventory slot that isn't part of your hotbar, an extra item is produced. If your only empty slots are part of your hotbar, the items simply aren't given.

**Expected behavior**
The recipe provides the normal amount of items, the result shows up in its slot instead of just being invisible, and shift-clicked results aren't deleted.

**Mod version**
1.2.1-1.18.1-midgame2, as part of All of Fabric 5 version 0.2.7

https://user-images.githubusercontent.com/39959519/148596697-6f0a4f6e-ba21-4d47-975d-88761ee0c7bb.mp4

**Comment by NotoJames** [comment]
I found that it is actually anything you can shift click to instantly craft.

**Comment by MobSlicer152** [comment]
Only if the result is stackable, this doesn't work on beds or armour.

**Comment by DaFuqs** [comment]
Fixed in the next update. Thank you two for the very detailed report.

**Comment by MobSlicer152** [comment]
No problem.

**Comment by DaFuqs** [comment]
fixed in 1.2.3-midgame4
