### ISSUE TITLE
[BUG] Can't pick up Storm Stones

### ISSUE THREAD

**Issue by darkspyro92** [DaFuqs/Spectrum#170]
**Describe the bug**
Storm Stones not being broken when hitting.

**To Reproduce**
Hit Storm Stone.

**Expected behavior**
It should break and you should receive a Storm Stone.

**Mod version**
1.6.6

**Screenshots**
![image](https://user-images.githubusercontent.com/22324730/223176844-8fc0aec3-b289-4101-a9ea-036da445ee73.png)

**Comment by DaFuqs** [comment]
Works fine with newest Spectrum and Revelationary 1.3.1. Maybe it's some kind of mod conflict?
Does it drop when using your hands and no armor equipped? Any errors in the client or server logs?

**Comment by darkspyro92** [comment]
Tried everything and updated and nothing works. It's part of a modpack but other people running this modpack aren't having this issue which is strange.

**Comment by DaFuqs** [comment]
can you send a screenshot of your current midgame progression tree, please ("Fall from Grace")?

**Comment by darkspyro92** [comment]
I don't see Fall from Grace, unless I need to find a falling star?

![image](https://user-images.githubusercontent.com/22324730/224704425-352df514-91ae-4501-a029-8404a88f86eb.png)
![image](https://user-images.githubusercontent.com/22324730/224705484-0031b0da-d112-4e53-bb0f-8e349800b1fd.png)
![image](https://user-images.githubusercontent.com/22324730/224705497-9a640dae-329a-4966-b6e6-1bfe97acb554.png)

**Comment by DaFuqs** [comment]
It's a second Advancement Tree with an Onyx Pedestal as Icon

**Comment by darkspyro92** [comment]
![image](https://user-images.githubusercontent.com/22324730/224715173-fae885c1-e8dc-4ebd-a645-2fed8f7c68fb.png)
Didn't even know that existed.

**Comment by darkspyro92** [comment]
![image](https://user-images.githubusercontent.com/22324730/224716316-68cdd2e0-d0a9-487f-8c78-1df5f17bb7ae.png)
![image](https://user-images.githubusercontent.com/22324730/224716334-baf94a1f-70dc-4e9f-ba09-d96bb5a6281a.png)
Might be easier if I post two images of the advancements since it's so big. xD

**Comment by DaFuqs** [comment]
Looks fine to me. I will see if I can replicate your issue in my personal AQM2 instance

**Comment by darkspyro92** [comment]
Alright. Thanks.

**Comment by darkspyro92** [comment]
Figured anything out? Also, other question, is there a way to transfer my Spectrum progress to another server through the files? We're moving our server so our characters aren't going to be saved of course. Didn't want to lose all that if possible. If not, oh well. Just have to work through it again.

**Comment by imreallybadatnames** [comment]
all of it is advancement based iirc
just move the old advancement tree

**Comment by DaFuqs** [comment]
^ this

Sadly I could not reproduce your issue at all, sorry. I made an update for Revelationary, which may add some more checks, just in case some mod may interfering, so that will be worth a try.
Have you tried breaking a storm stone with just using a vanilla pickaxe, without having any modded armor or trinkets equipped?

**Comment by darkspyro92** [comment]
I have tried it with an iron pickaxe with nothing else equipped. Still
didn't work.

**Comment by DaFuqs** [comment]
Pretty out of ideas then, sorry. No errors in the log, nothing?

**Comment by darkspyro92** [comment]
As far as the server owner said, no.

**Comment by darkspyro92** [comment]
Hey. Sorry to repost on this. Server owner finally gave me some storm
stones, got the advancement for getting them, and I was suddenly able to
gather them. Don't know if that helps any.

**Comment by DaFuqs** [comment]
Currently not getting any wiser, sadly. But I'm currently doing a full run from start to finish myself. If I happen to have the same problem I will get it fixed asap ✅

**Comment by darkspyro92** [comment]
Thanks for that. Hopefully you can figure it out. Sorry for the bother.
