### ISSUE TITLE
[BUG] Amaranth incompatible with RightClickHarvest

### ISSUE THREAD

**Issue by Shoes4Clues** [DaFuqs/Spectrum#179]
**Describe the bug**
The mod "[RightClickHarvest](https://www.curseforge.com/minecraft/mc-mods/rightclickharvest)", when used on the bottom half of an Amaranth plant, harvests the plant but keeps the top half. The top half can then be harvested and it plants an Amaranth plant in the air.

**To Reproduce**
1. Plant and fully grow Amaranth.
2. Attempt to right click the bottom half of the crop.
3. After harvesting the bottom half, harvest the top half.
This may be repeated indefinitely to make a tower of Amaranth crops.

**Expected behavior**
Expected full crop to harvest no matter where you click

**Mod version**
1.6.9-1.18.2

**Screenshots**
![2023-03-30_15 35 10](https://user-images.githubusercontent.com/63887849/228978572-5348e409-cef1-44b6-af55-469e32d61e71.png)

**Crash Report**
N/A

**Comment by DaFuqs** [comment]
I have seen this before. This is more an issue with how right click harvest handles crop replacing, missing some checks. This is something that should be fixed on their side.
In the meantime use a different Right Click Harvest mod. Most others I have seen do not have that issue.
