### ISSUE TITLE
[BUG] Spirit Sallow Leaves Crash Game

### ISSUE THREAD

**Issue by TempestuousVixen** [DaFuqs/Spectrum#180]
**Describe the bug**
When rendering the Spirit Sallow Leaves block, Minecraft crashes. This was discovered on a server with an extensive mod-list; however, to ensure that a mod incompatibility was not the source of the issue, I have also tested with only Spectrum and its dependencies and the crash still occurred.

**To Reproduce**
Place and render Spirit Sallow Leaves block.

**Expected behavior**
Game should not have crashed.

**Mod version**
Spectrum 1.6.9 for Minecraft 1.19.2 on Fabric Loader 0.14.17
Dependency Versions:
Cloth Config 8.2.88
OwO Lib 0.8.5
Patchouli 77
Trinkets 3.4.2
Revelationary 1.3.3

**Crash Report**
[crash-2023-04-01_17.31.04-client.txt](https://github.com/DaFuqs/Spectrum/files/11130737/crash-2023-04-01_17.31.04-client.txt)

**Comment by Bellabong** [comment]
How are you obtaining these blocks in the first place? They're not meant to be available in survival

**Comment by TempestuousVixen** [comment]
I'm in Creative mode, where they are obtainable via the Creative inventory. I was going to build with them. Regardless of whether they're meant to be obtainable in survival, I feel that crashing on rendering the blocks is a pretty severe issue.
