### ISSUE TITLE
[BUG] Store item into Bottomless Bundle by AE2 storage bus cause item duplicating

### ISSUE THREAD

**Issue by XenonDB** [DaFuqs/Spectrum#183]
**Describe the bug**
For example, insert one item via storage bus cause bundle have 2 item.
Not sure whether this issue is caused by Spectrum or AE2 so I report it both side.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7033

**Expected behavior**
Item duplicating shouldn't happen.

**Mod version**
spectrum-1.6.9-1.19.2-leisure_time
appliedenergistics2-fabric-12.9.2

**Comment by DaFuqs** [comment]
I can not reproduce it in the Spectrum dev + AE2 12.9.2. This is a good thing.
In dev, the Bottomless Bundle internals have gotten a total revamp, so probably is on Spectrum's side + already fixed. Consider it resolved for AE2 and in general when Spectrum 1.7 is released.

**Comment by XenonDB** [comment]
Sounds great.
I should close issue which I paste in AE2 issue list.

**Comment by DaFuqs** [comment]
Fixed in Spectrum's alpha builds.
