### ISSUE TITLE
[Feature] Improved Big Catches Configuration

### ISSUE THREAD

**Issue by Aeonsteel** [DaFuqs/Spectrum#184]
Big Catches should be able to be configured by biome, biome tags, dimension, and other factors (Weather? Skylight? Time of Day?). In addition, I feel that the Entity it fishes up should be able to have custom NBT set for it. (Honestly I want the NBT stuff for it so I can add Cobblemon to the big catches thing)

**Comment by DaFuqs** [comment]
That seems like a fun use case. Will do

**Comment by DaFuqs** [comment]
This is now a thing in the Alphas, thanks to @Electro593 !
