### ISSUE TITLE
[BUG] Constructor's Staff consume a wrong number of material when building slabs

### ISSUE THREAD

**Issue by Hophenby** [DaFuqs/Spectrum#185]
**Describe the bug**
only one slab was consumed when placing a double-slab block which would cause item duplicating.

**To Reproduce**
place the slabs near a double-slab block

**Expected behavior**
consume one slab while it should have consumed 2

**Mod version**
Which version of the mod are you currently using?
1.6.9-1.19.2-leisure_time

**Screenshots**
![image](https://user-images.githubusercontent.com/66473090/232242535-e033342e-79ce-4473-a49d-a72331fdde5d.png)
![image](https://user-images.githubusercontent.com/66473090/232242577-02281cab-790d-47f9-8143-8e30ef4756a5.png)

**Comment by Hophenby** [comment]
the staff doesn't check the blockstate when placing something. A same bug can be reproduced when placing candles, sea pickles or blazing rods in the mod Supplementaries

**Comment by DaFuqs** [comment]
Sadly there is no lookup to check what amount of blocks it would take to place a specific block state. For Slabs & some vanilla blocks I might come up with a (hardcoded) way for their placement.
In the meantime adding the blocks to the `spectrum:building_staffs_blacklisted` block tag will mitigate any dupes

**Comment by DaFuqs** [comment]
Improved block placing & staff blacklist in alpha-20.
