### ISSUE TITLE
[Feature] AE2 Support

### ISSUE THREAD

**Issue by moshner** [DaFuqs/Spectrum#186]
I would love to see it if AE2 could fortune the discovered ores from Spectrum. Currently it just breaks the block as if it was stone/netherrack/etc because AE2 cannot unlock advancements.

**Comment by DaFuqs** [comment]
Not AE2 specific, but I will add a way (machines / api) to auto harvest ores & other recources that use cloaking down the line.

**Comment by DaFuqs** [comment]
This will magically start working in later mc versions, with the introduction of FakePlayers in Fabric API

**Comment by DaFuqs** [comment]
Tested and fully working in 1.20. This will resolve itself :)
