### ISSUE TITLE
[BUG] Intermittent placing of Shimmerstone Staff lights.

### ISSUE THREAD

**Issue by Gammavali** [DaFuqs/Spectrum#187]
**Describe the bug**
Radiance Staff is placing lights unreliably despite making particle effects, sounds, and using up Shimmerstone Gems, attempting to remove already placed lights occasionally tries to place another instead of remove. 
Also does not attempt to place at a distance longer than the players normal reach nor place in the air as book describes.

**To Reproduce**
Left click Shimmerstone Staff on blocks while in mainhand to try and place invisible light.

**Expected behavior**
Left clicking a block face (or already placed light) with Shimmerstone Staff in mainhand while Shimmerstone Gems are in inventory to place (and remove) an invisible light. 

**Mod version**
spectrum-1.6.9-1.19.2-leisure_time (Modpack: All of Fabric 6 (v1.5.3)

-Updated Spectrum to v1.6.10 to test if issue persisted (it did indeed)
-It seems like the mod is simply double left clicking.

**Comment by DaFuqs** [comment]
Fixed in the alphas.
