### ISSUE TITLE
[BUG] Midnight Solution dont work with Copper Block Correctly.

### ISSUE THREAD

**Issue by MrHaiopei** [DaFuqs/Spectrum#188]
**Describe the bug**
Dipping Copper Blocks in Midnight Solution work only to Exposed Copper but after this dont work.

**To Reproduce**
I try to dipping Exposed Copper Block in Midnight Solution in the Overworld.

**Expected behavior**
i Expected, i can turn every time after dipping in Midnight Solution the next tier of Oxidized Copper

**Mod version**
spectrum-1.6.9-1.19.2-leisure_time.jar (Fabric)

**Screenshots**

![image](https://user-images.githubusercontent.com/132226267/235371973-4c81619c-f48e-4c36-a356-dd43b346f509.png)

**From Exposed Copper to Weathered Copper dont Work.**

![image](https://user-images.githubusercontent.com/132226267/235372015-f7395194-f506-4b95-8cae-29e4b3578501.png)

**From Weathered Copper to Oxidized Copper dont work too.**

![image](https://user-images.githubusercontent.com/132226267/235372031-ce50efdd-8004-4900-815e-67e7991f0ea9.png)

**Crash Report**
No Crashes

**I Hope you can fix this and i can Help to find more.**

btw i play the Modpack All of Fabric 6

**Comment by DaFuqs** [comment]
Worked perfectly fine for me. Might be because of a mod that 'optimizes' fluid collissions?
Please remove mods until it works to find out the culprit. Then I can get to adding compat.

Might also just be really bad luck, since fluid conversion is chance-based, instead of fixed time
