### ISSUE TITLE
[BUG] Crafting Recipes in Book and REI broken

### ISSUE THREAD

**Issue by blutact** [DaFuqs/Spectrum#189]
**Describe the bug**
Crafting recipes show wrong items and dont seem to work anymore

**Crash Report**
will add this later if needed, but I doubt the crash had something to do with spectrum, I was just mining stone. Server probably crashed because of not enough ram (we've had that before)

**To Reproduce**
Play Dreamcraft(modpack), crash server, have corrupted advancements and other account data (corrupted in terms of everything but items is reset to 0), use old save file for stats, advancements and playerdata, log back in, try to progress towards where you where

**Expected behavior**
recipes should show right items and work when u unlock all materials again/when you are back where you were before crash

**Mod version**
1.6.6

**Screenshots**
(I know that the mats are wrong in the screenshot)
![d0e5d5a3ac657d9463ce8126d8efbe1f](https://user-images.githubusercontent.com/132268317/235447322-17093f53-28a2-4aaa-b891-6877f2eefb23.png)
![4f5dfe0f3c86989b0576d2091daabc01](https://user-images.githubusercontent.com/132268317/235447298-603f6fda-69fc-4f66-8a01-e9b7104b4acd.png)

**Comment by blutact** [comment]
Ok so a relog seems to have fixed it.
still a weird bug.

**Comment by DaFuqs** [comment]
That sounds like an item id desync.
Pretty sure there is nothing I can do about it. If you ever find out what has caused it, I can look into it further
