### ISSUE TITLE
[BUG] Dupe Bug

### ISSUE THREAD

**Issue by mfkG** [DaFuqs/Spectrum#19]
**Describe the bug**
I can dupe all Crafting recipes i tried.
For example, insert an iron block into the Pigment Pedestal, and while its crafting the 9 iron, remove (shift-click!) the block and it continues crafting.

**To Reproduce**
Add recipe into the Pedestal, and when it begins crafting, shift-click the ingridient(s) out (back into inventory), it continues crafting.

**Expected behavior**
Stops Crafting when removing an ingridient.

**Mod version**
spectrum-1.2.6-1.18.1-midgame7

I updated the mod, today (from midgame3 iirc), and the achievments are there, and the stuff in the book, but the Pigment Pedestal shows no unlocked reciepe (hadnt much unlocked anyways, coz i have no clue how, but thats another story). don't know if that has something todo with it.
Guess not, tried it with just Spectrum installed, same thing, just shift-click crafting ingredients out, and it just continous crafting....

**Comment by nickalbrecht** [comment]
I encountered this today the same way, upgraded the version to midgame7 from midgame3. I also noticed it starts to craft immediately and doesn't seem to wait for a redstone signal?
