### ISSUE TITLE
Various blocks do not have rotate or mirror implementations

### ISSUE THREAD

**Issue by haykam821** [DaFuqs/Spectrum#191]
Various blocks in Spectrum do not have rotation or mirror functionality implemented, meaning structures (such as through structure blocks) will not rotate or mirror these blocks correctly. These blocks include at least entangled chests, entangled tanks, breakers, placers, wither builders, igniters, and drawbridges.

**Comment by Aeonsteel** [comment]
I don't think those blocks are from Spectrum...?

**Comment by LunaLilac** [comment]
Yeah, I think they're talking about blocks from Kibe.

**Comment by haykam821** [comment]
Yes, I mistakenly opened the issue in the wrong repository. All of Spectrum's blocks seem to have rotate and mirror implementations from my testing.
