### ISSUE TITLE
[BUG] Crash on generation chunk

### ISSUE THREAD

**Issue by Qblolz** [DaFuqs/Spectrum#198]
**Describe the bug**
Crash on generation chunk

**To Reproduce**
--

**Expected behavior**
--

**Mod version**
spectrum-1.6.10-1.19.2-leisure_time

**Screenshots**

**Crash Report**

[2023-06-12-2.log](https://github.com/DaFuqs/Spectrum/files/11721768/2023-06-12-2.log)

**Comment by DaFuqs** [comment]
Acessing the inventory of blocks while worldgen is still running?
While that is really weird, I can add a workaround for that, ty!

**Comment by DaFuqs** [comment]
I will release a version with the fix today on both Curseforge & Modrinth

**Comment by DaFuqs** [comment]
this was fixed in 1.6.11-1.19.2
