### ISSUE TITLE
[BUG] ParticleSpawner crash

### ISSUE THREAD

**Issue by DomenicoCatrambone** [DaFuqs/Spectrum#20]
**Describe the bug**
When, in creative, I try to use the particle spawner the client crashes.

**To Reproduce**
- Take particle spawner from creative and place
- Use it

**Mod version**
spectrum-1.2.6-1.18.1-midgame7.jar

**Comment by DaFuqs** [comment]
Are both client and server using midgame7?
If yes plase attack a full log of the crash and I can get it fixed swiftly.

**Comment by DomenicoCatrambone** [comment]
[crash-2022-01-12_11.10.49-client.txt](https://github.com/DaFuqs/Spectrum/files/7854361/crash-2022-01-12_11.10.49-client.txt)
It's a singleplayer world. I will test in multi too.

Edit:
Happens in multiplayer too.

**Comment by DaFuqs** [comment]
Does it still happen in midgame8?

**Comment by DomenicoCatrambone** [comment]
It doesn't crash anymore, but it doesn't let me use the menu that opens.

**Comment by DaFuqs** [comment]
Is it a premade, publicly available pack or a self-made one? In the first case I can directly look at the pack and test where the issue originates.

**Comment by DomenicoCatrambone** [comment]
It's self-made one
[TestPack.zip](https://github.com/DaFuqs/Spectrum/files/7884900/TestPack.zip)
.
