### ISSUE TITLE
[BUG] Spectrum ruins/dungeons when using mods for deeper oceans

### ISSUE THREAD

**Issue by slammaja** [DaFuqs/Spectrum#201]
**Describe the bug**
Ruins generated by the mod meant to spawn underground are floating in water, when using mod that makes oceans deeper.

**To Reproduce**
Use Spectrum with Worldgen Variety mod or similiar.

**Expected behavior**
Ruins should generate under ocean floor, not in water.

**Mod version**
1.6.10

**Screenshots**

According to closed issue #167, I can configure ruins generation using datapack, maybe the easiest way would be to remove ruins from ocean biomes altogether. I am unfortunately inexperienced in this way of configuration. Could you post some kind of example or template?

Thank you very much, your mod's awesome BTW :).
 
![2023-06-24_11 40 08](https://github.com/DaFuqs/Spectrum/assets/12775695/e5205e6b-6169-41b1-8bc5-e23bd91ab58b)
![2023-06-24_11 40 30](https://github.com/DaFuqs/Spectrum/assets/12775695/88aade82-83f3-411b-8997-37813ef1b2a7)

**Comment by DaFuqs** [comment]
There is a good chance that I have improved that in the recent alpha builds already.
Could you try the newest one from Modrinth and see if the generation improved?

**Comment by slammaja** [comment]
Been swimming around quite a while now with alpha bulid 15 of version 1.7.0 and it looks promising now floating ruins. Think I can close the issue :) That is great news, thanks!

**Comment by DaFuqs** [comment]
Perfect, thanks for letting me know
