### ISSUE TITLE
[BUG] Titration Barrel to indicate when a recipe has finished crafting?

### ISSUE THREAD

**Issue by Shibva** [DaFuqs/Spectrum#204]
**Describe the bug**
It appears that after seeing what would yield for a 0 day fermentation of kimchi (im new to this so I was curious of a premature brew process) and I was given water bottles. this would be fine but I dint gave any glass bottles in my inventory; meaning I got 8 free bottles out of thin air

**To Reproduce**
Kimchi fermentation; seal and unsleal and right click

**Expected behavior**
When you r-click it would give a message saying "you dont have any means to bottle your brew" or a message to inform the user that they lack glass bottles to properly bottle it. if you do it would give you the bottle product but also remove the glass bottle from your inventory

**Mod version**
1.6.11 - 19.2 - leisure time

**Comment by Shibva** [comment]
Note: this issue is NON-existent with the deeper down alpha; not sure at what point but dosent have this issue in alpha v16

**Comment by DaFuqs** [comment]
Sorry for the late answer. Was away for a bit for real life things.
I've completely revamped the Titration Barrel's internals in the alphas, so good to know that this is fixed already, ty!

Leaving this issue open until the next big release, if someone else notices the same issue.

**Comment by Shibva** [comment]
I seem to have came across the issue again, this time I Think I have realized what it was

apperently if you open something too soon, if you try to exract it, you get bottles of water

**Comment by Shibva** [comment]
found this out when extrating what I thought was a finished thing of chocolate (0.3 days read)

if I could, id recomend maybe including some qol thing for if a fermentation process is complete it would show green over the time message when checking the barrel

**Comment by Burritooo242** [comment]
hey guys. I've almost finished Spectrum, but got a prob with the titration barrel;

I've got my recipe in, but can't seem to unseal it, no matter what I try? I sneak-use (right button like every freaking item) and it won't unseal, am I just dumb or what

**Comment by DaFuqs** [comment]
Done. Barrels can now only be unsealed when they are ready and if not state so.
