### ISSUE TITLE
[BUG] Wireless redstone does produce a redstone signal

### ISSUE THREAD

**Issue by ironstars1** [DaFuqs/Spectrum#205]
**Describe the bug**
Wireless Redstone blocks are not producing a signal to adjacent redstone at the recieving end.

**To Reproduce**
send redstone signals through wireless redstone and attempt to connect at the recieving end.

**Expected behavior**
Redstone signal being transferred from the active Wireless Redstone block to nearby redstone.

**Mod version**
1.18.2

**Screenshots**

![2023-07-07_19 07 42](https://github.com/DaFuqs/Spectrum/assets/138941194/183d4151-b9b9-47cd-94dc-c1526d7b029c)

**Comment by DaFuqs** [comment]
The receiver only outputs redstone on one side, so your redstone contraptions can be pretty compact.
Look for the side with the arrow. (Next update will have it a bit more visible)
