### ISSUE TITLE
[BUG] Fusion Shrine Multiblock crashing when right clicking it, and more importantly the guide does not work at all (Tied to the shrine bug)

### ISSUE THREAD

**Issue by PraiseTheDunBun** [DaFuqs/Spectrum#206]
**Describe the bug**
1st : When you right click the shrine with ANYTHING even an ingridient for a recipe, it will crash the client, tried it with more people on the same chunk on a server and it doesnt affect anyone but the one that uses the Shrine

2nd : The "Colorful World" guide does not work at all, example :

![imagen](https://github.com/DaFuqs/Spectrum/assets/139375069/7a0b879f-3e73-4b26-bcdf-86754fbf3cc3)

As it says on the screenshot, the shrine seems to be the issue so thats why Im making it all into a single post.

**To Reproduce**
Right click it with anything or use the guide.

**Expected behavior**
A concise description of what you expected to happen.

**Mod version**
1.6.12-1.19.2-leisure_time

**Screenshots**
Screenshot provided above of the guide not working

**Crash Report**

[crash-2023-07-12_00.39.43-client.txt](https://github.com/DaFuqs/Spectrum/files/12030110/crash-2023-07-12_00.39.43-client.txt)

**Comment by JasonBlunder** [comment]
Hey, I ran into the same issue with All the Fabric 6. Duplicate the pack and it should fix the book even if you're in a server. Repairing the pack didn't work. 
While I have no idea why this is happening wanted to share the "fix" I stumbled on by accident.
Haven't tested the shrine yet however, as I've just started poking this mod.

**Comment by DaFuqs** [comment]
The newest ~~KubeJS~~ Mystical Agriculture breaks it. Nothing I can do about it. (May be able to add a bandaid fix in 2 weeks, but it will not be pretty)

**Comment by JasonBlunder** [comment]
> Hey, I ran into the same issue with All the Fabric 6. Duplicate the pack and it should fix the book even if you're in a server. Repairing the pack didn't work. While I have no idea why this is happening wanted to share the "fix" I stumbled on by accident. Haven't tested the shrine yet however, as I've just started poking this mod.

> Hey, I ran into the same issue with All the Fabric 6. Duplicate the pack and it should fix the book even if you're in a server. Repairing the pack didn't work. While I have no idea why this is happening wanted to share the "fix" I stumbled on by accident. Haven't tested the shrine yet however, as I've just started poking this mod.

Update: reloaded the pack to keep playing after posting this and it broke again. comment above has reason. Having a fresh dup only works sometimes but after it breaks only a fresh install works. Sucks but nothing to do about it but wait,

However it seems whatever is causing the breaks seems to do with servers or multiple relaunches as I've used a fresh ATF6 dup to play in a single player world and it worked for a few restarts. only one relaunch when I join a server however.  
If the book is showing the error you cant use the shrine without crashing.

**Comment by Linguardium** [comment]
Issue with Mystical Agriculture 2.0.6+. downgrade that mod or remove it
