### ISSUE TITLE
[CRASH] Hexcasting integration page crashes upon attempting to view contents

### ISSUE THREAD

**Issue by Shibva** [DaFuqs/Spectrum#208]
**Describe the bug**
Opening the hexcasting integration page on the mod integration section causes the game to crash

**To Reproduce**
should be self-explaniotyr

**Expected behavior**
The game not to crash, lel

**Mod version**
Deeper Down alpha 16

**Screenshots**

**Crash Report**
https://gist.github.com/Shibva/844e3142e5ed7f25b9039e549ea5cb54

**Comment by Linguardium** [comment]
This is not really a spectrum problem. remove all mods except spectrum, patchouli and hexcasting (and dependencies) to verify the issue still persists

**Comment by Shibva** [comment]
started a fresh instance and only downloaded the mods with dependencies

The issue persisted: please remember that this was using the alpha releases of the Deeper Down (spectrum-1.7.0-deeper-down-alpha16-1.7.0)

report: https://gist.github.com/Shibva/fa3fbf8ebb7466d36dc852ad303bd970

**Comment by DaFuqs** [comment]
Fixed in the newest upcoming alpha. 👌
