### ISSUE TITLE
[BUG] Fusion Shrine crashes game when interacted with

### ISSUE THREAD

**Issue by sullyboy12312** [DaFuqs/Spectrum#209]
**Describe the bug**
Whenever I interact with the fusion shrine, be it by adding a liquid or inserting or removing an item, my game crashes. If there is a block above the shrine, making it inoperable, I am free to interact without any issues, however, if I remove the block and interact with it again, it will crash. Breaking it does not seem to crash the game however. This has only started occurring after the server running the mod was updated from All of Fabric 6 1.6.1 to 1.8.1

**To Reproduce**
Place a fusion shrine with its structure, and either add an item or add a liquid

**Expected behavior**
For the shrine to not crash the game

**Mod version**
1.6.11-1.19.2

**Crash Report**
https://mclo.gs/8vC2DJf

**Comment by Trent2087** [comment]
This was caused by Mystical Agriculture 2.0.8. We downgraded it to 2.0.5 in AoF6 1.8.2. Update your modpack.

**Comment by DaFuqs** [comment]
Like Trent noted, downgrading Mythical Agriculture will do the trick.
