### ISSUE TITLE
[BUG] Spectrum trees generate on mushroom islands.

### ISSUE THREAD

**Issue by RubyRezal** [DaFuqs/Spectrum#21]
**Describe the bug**
Green leafy trees are an odd sight to see generating on a mushroom island.
Is this intended?

**To Reproduce**
Setup client with minimal modset; Spectrum, WTHIT, WMITAF, and dependencies.
Create a world with worldseed -1166828785
Travel to a mushroom island at coords 815, 71, -692
Observe oak trees with obfuscated block names and tagged as Spectrum blocks.

**Expected behavior**
Unknown, I was testing Spectrum for potential inclusion on my server. I have yet to explore its mysterious mysteries, but oak trees on a mushroom island are pretty conspicuous.

**Mod version**
Which version of the mod are you currently using?
Spectrum 1.2.6-1.18.1-midgame7

**Screenshots**
![2022-01-12_17 37 15](https://user-images.githubusercontent.com/1816386/149234342-35b9a0ba-1d86-4df3-b22d-fe54d174b468.png)

**Comment by DaFuqs** [comment]
> oak trees on a mushroom island are pretty conspicuous.

Definitely. I will see what I can do. Ty for the report!
