### ISSUE TITLE
[BUG] Blackslag Iron Ore is in c:lapis_ores; Blackslag Lapis Ore doesn't have any tags

### ISSUE THREAD

**Issue by pbone64** [DaFuqs/Spectrum#210]
**Describe the bug**
Blackslag iron ore is in the c:lapis_ores tag

**To Reproduce**
1. Download spectrum
2. Open Minecraft
3. Look at Blackslag Iron Ore
4. Look at Blackslag Lapis Ore
5. ???
6. Profit

**Expected behavior**
Blackslag Iron Ore should be in c:iron_ores; Blackslag Lapis Ore should probably be in c:ores, minecraft:lapis_ores, and c:lapis_ores

**Mod version**
1.7.0-alpha16 but I've verified that this remains unfixed in the current working version.

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/47093312/6b7915f0-31cb-4b72-9104-75d9906ebb68)
![image](https://github.com/DaFuqs/Spectrum/assets/47093312/311de153-1189-421d-ad0f-f2f18f208681)

**Comment by DaFuqs** [comment]
Will fix that. Ty!
