### ISSUE TITLE
[BUG] Bedrock dungeon locks players in if they dont already know what they are doing

### ISSUE THREAD

**Issue by Linguardium** [DaFuqs/Spectrum#213]
**Describe the bug**
exit relies on item not despawning and not being picked up by the blackhole chest

black hole chest is inside. This dungeon effectively softlocks players into the final room with no way to escape if the item despawns. This might even be the first dungeon players face, pushing people further away from the mod after the midnight aberration failure... 

**Expected behavior**
Redstone controlling the exit door should toggle rather than switch. this can be done with a piston breaking a torch with very minimal modification to the dungeon

**Mod version**
1.6.11

**Comment by Noaaan** [comment]
Its worth noting that you are able to destroy blocks inside the dungeon (albeit not the indestructible ones). The wooden pressure plate can easily be replaced with a lever or a redstone torch. If the player decides to solve the puzzle in this manner (which arguably, I did my first time), then it is on them to respect the item despawn timer.

**Comment by DaFuqs** [comment]
While that is true, being trapped isn't very fun. The structure was revamped in the alpha builds to prevent that.

**Comment by DaFuqs** [comment]
Improved in Spectrum's alpha builds.
