### ISSUE TITLE
[Feature] Tinted Glass added to blocks to ignore as an obstruction

### ISSUE THREAD

**Issue by Shibva** [DaFuqs/Spectrum#218]
Should be self explanitory

it appears glass works as a block that structures that requires sky exposure so why not Tinted Glass?
![image](https://github.com/DaFuqs/Spectrum/assets/38770780/da3dfd24-1261-40da-b85e-12c40752c5c9)

**Comment by DaFuqs** [comment]
Sadly, that's a bit of a limitation on how tinted glass works. Since it does not let any light through, it counts as non-translucent, even if players can view through it. So the builtin "is open sky" check sees it as quite-solid block.
