### ISSUE TITLE
[BUG] Ocean dungeons spawn too high with any mod that causes deeper oceans

### ISSUE THREAD

**Issue by cranberriez** [DaFuqs/Spectrum#220]
**Describe the bug**
Dungeons spawn too high and cause floating orbs in the ocean absolutely everywhere. This happens when combined specifically with the Tectonic mod.

**To Reproduce**
Spectrum 1.19.2 and Tectonic 1.19.2 both Fabric

**Expected behavior**
Dungeons to spawn lower along the ground or not at all.

**Mod version**
fabric-0.14.21
spectrum-1.6.12-1.19.2-leisure_time.jar
tectonic-mod-mc1.19.2-v1.1.10.jar

**Screenshots**
![Minecraft Screenshot 2023 07 22 - 13 39 46 24](https://github.com/DaFuqs/Spectrum/assets/24465331/7ab33950-52c0-4d9c-945b-c7196cc92d70)

If its possible to adjust the dungeon spawner, either through config or kubejs would be helpful.

**Comment by DaFuqs** [comment]
Similar to #201. this will be fixed with the next release.

In the meantime, you can adjust the height of the structures via overriding these files via data pack: https://github.com/DaFuqs/Spectrum/tree/1.19-leisure-time/src/main/resources/data/spectrum/worldgen/structure

**Comment by DaFuqs** [comment]
On second thought, leaving this open in case someone else stumbled across that until the next release.
