### ISSUE TITLE
[Feature] Recommending "Advancements Debug" below 19.4 versions

### ISSUE THREAD

**Issue by Shibva** [DaFuqs/Spectrum#223]
Yes, IK that there are no newer versions of the mod beyond 19.2; I say this because this issue was corrected in 19.4 

What does it do:
While the name is somewhat misleading in making you think its advancement debug tools; its actually a mod that patches an issue that occurs when enough advancements are loaded to cause a `StackOverflow` error. In my pack I started running into this error as a result of the mass advancements in it, a large part of it being added by Spectrum. 

Why make it a dependency?
I rather not make it a required one (that is up to you), rather a suggested/optional dependency as this patches the bug that was fixed in 19.4

Got a link?

sure https://www.curseforge.com/minecraft/mc-mods/advancements-debug

**Comment by DaFuqs** [comment]
I'm regularily using that mod, too. Since spectrum comes with so many advancements, suggesting it for 1.19.2 definitely makes sense.
Will add that, ty!

**Comment by DaFuqs** [comment]
done.
