### ISSUE TITLE
[BUG] Chunk generation crashes server

### ISSUE THREAD

**Issue by AnidemDex** [DaFuqs/Spectrum#225]
**Describe the bug**
Seems like the plugin crashes when tries to generate a chunk?

**To Reproduce**
I haven't find a proper way to reproduce. Seems to be something random.

**Expected behavior**
No crash

**Mod version**
spectrum: Spectrum 1.6.12-1.19.2-leisure_time

**Crash Report**
https://mclo.gs/mNvxwD1
https://mclo.gs/lxSLX3O

**Comment by AnidemDex** [comment]
Seems like aternos replaces the log everytime the server starts. Gonna try to replicate the bug and paste the log here instead. Crash report link is static.

Edit: Removing the mod that generates the instance works as a temporary solution

**Comment by DaFuqs** [comment]
> at com.supernoob.atfmd.object.StructuresFeatures.BedrockDiscStructure.method_38676(BedrockDiscStructure.java:69)

Looks like your crash is caused by https://github.com/SuperNoobYT/AllTheFanMadeDiscs
Best to report it to them so they can go fix it.
