### ISSUE TITLE
[BUG] canvas copy enchanted book does not consume

### ISSUE THREAD

**Issue by SmallYii** [DaFuqs/Spectrum#227]
**Describe the bug**
For example, if I use the canvas to copy the enchanted book of Protection 4, when I copy the enchanted book of Fire Protection 4, the enchantment of Protection 4 and Fire Protection 4 will exist on the same enchanted book, and so on.

**To Reproduce**
Use canvas to copy enchanted books, then copy other enchanted books

**Expected behavior**
Make the canvas prohibit copying enchanted books

**Mod version**
mod version 1.6.4 game version fabric1.18.2, but after my test, this bug also exists in 1.6.9

**Screenshots**
no screenshot

**Crash Report**
not a crash

**Comment by DaFuqs** [comment]
This is fixed in dev ✅

**Comment by DaFuqs** [comment]
Fixed in alpha-20
