### ISSUE TITLE
[Forked Fix] Implementing missing shimmer bloom on medium-sized crystals (primary progression crystals only)

### ISSUE THREAD

**Issue by Shibva** [DaFuqs/Spectrum#229]
This is a notice on an issue I ran into and made an attempt to fix 

for some reason, all crystal buds that are medium-sized dint have a file made for implementing bloom via shimmer.

I may not know how to code, but I can do some things; like tracking down what file adds shimmer and then when learning its simple to implement, copy-pasted the file contents into new files with names that abide by the block associated with it.

It should work, but Id recommend checking for any possible spelling errors; while it doesn't look like I made any.

Adds all medium crystals needed for progression to have bloom with the exception of Amethyst

see #228 

This report is to serve both as a notice in case merge requests don't notify you and to serve potently for archival purposes.

Feel free to terminate the fork once merged

**Comment by DaFuqs** [comment]
merged 👌

**Comment by Shibva** [comment]
@DaFuqs can ya terminate the branch I made for me? not sure how to get rid of it afterward

**Comment by Noaaan** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository#deleting-a-branch
