### ISSUE TITLE
[BUG] Colorful World guidebook error building entry

### ISSUE THREAD

**Issue by LightSubZero** [DaFuqs/Spectrum#230]
Describe the bug
When you open the book, the progress of the mod and its normal use is not available

To Reproduce
I don’t know, am trying to understand why this happened only to me from my whole party

Expected behavior
The normal performance of the book and the passage of the mod

Mod version
spectrum-1_6_11-1_19_2-leisure_time

Screenshots
![изображение](https://github.com/DaFuqs/Spectrum/assets/25801524/a2e4c89e-1c03-4135-93e8-e95d0ecf1545)
![изображение](https://github.com/DaFuqs/Spectrum/assets/25801524/bbeecd63-0bd2-40ff-b089-7fa2f7fdadae)
![изображение](https://github.com/DaFuqs/Spectrum/assets/25801524/87e13d40-862c-4e8c-a663-956fcd718074)

Crash Report
There is no word from the mod Spectrum in the crash report, it works fine, only the book does not work for me

**Comment by DaFuqs** [comment]
Try updating to 1.6.12-1.19.2 on both server & client, please

**Comment by LightSubZero** [comment]
Thanks man, now working
![изображение](https://github.com/DaFuqs/Spectrum/assets/25801524/8dd00758-743c-4419-93d1-a5ef2c15ee9f)
