### ISSUE TITLE
[Feature] "count" recognition for "base_ingredient" in potion workshop for niche case recipies.

### ISSUE THREAD

**Issue by Shibva** [DaFuqs/Spectrum#231]
## The Story
I made a small json for someone in the Hexcasting community that made a mod called Hex Gloop

one of the things they add is casting potions; a "brew" that can have a pattern casted into it and then be consumed for a one-use (apparently for selling into shops or something; still neat concept)

I decided to help out by, and I mean this literally, ripping open alpha 18 and using an existing json to understand the format and then tinkering with it to get the end result (call it plagiarism if ya what lel)

the only issue is that with brewing, it works with effects so I had to resort to crafting, and that worked; however I've discovered that `"count"` is only set to work on the output. And that brings us here
## The Suggestion 
what I'm suggesting is that you can allow for `base_ingredient' to have an optional parameter that can determine the number of base items needed for it to run to fix this and if possible apply it to the `Leasure Time` release line as well, though it's up to you 

(format of the recipe I made)
![image](https://github.com/DaFuqs/Spectrum/assets/38770780/b33c644a-7f03-456a-869e-bfc213b2996b)

**Comment by DaFuqs** [comment]
You really went the hard route, since [the recipe type is nicely explained on the wiki](https://github.com/DaFuqs/Spectrum/wiki/Custom-Potion-Workshop-Crafting-Recipes). But either way, the end result looks perfect.

I'll add the ability of specifying input counts.

**Comment by DaFuqs** [comment]
Fixed in alpha-20
