### ISSUE TITLE
[BUG] Possible Progression Hinderance; End Remasterted prevents use ender eyes on cracked frames

### ISSUE THREAD

**Issue by Shibva** [DaFuqs/Spectrum#234]
**Describe the bug**
Due to a part of Ender Remaster reworking how one enters the end, it optionally disables the ability to use Ender Eyes to activate the portal to encourage exploration; however, as a result of messing around in a test world, I've discovered that the frames you add also share this hindrance and worse part being is it not able to accept the other eyes the mod adds

**To Reproduce**
install spectrum (preferably deeper down alpha 19) and Ender Remastered

**Expected behavior**
any attempt to put an eye of ender in will not work and it seems that frames placed by players won't work properly 

**Mod version**
Deeper Down Alpha 19

**Crash Report**
Non-applicable

**Comment by 800020h** [comment]
did you miss word the expected behaviour part?

**Comment by Shibva** [comment]
I don't think so

Trying to use ender eyes on places frames won't work and trying to use others will not work either

**Comment by 800020h** [comment]
expected behaviour is what you think should happen/what you expected to happen

you seem to have just repeated observed/wrong behaviour

in this case expected behaviour could be "using eyes of ender on cracked frames would work like it does without end remastered"

**Comment by 800020h** [comment]
it wouldn't surprise me if it's an end remastered issue
with how it handles preventing default behaviour

**Comment by DaFuqs** [comment]
Looks like End Remastered [globally disables the use of Eye of Enders on any block](https://gitlab.com/endrem/end-remastered-fabric/-/blob/master/src/main/java/com/endremastered/endrem/mixin/EnderEyeItemMixin.java?ref_type=heads#L24). Their deprecated forge branch only [prevents the use of Eye of Ender on vanilla End Portal Frames](https://gitlab.com/endrem/end-remastered/-/blob/1.17.1/src/main/java/com/shteken/endrem/events/ModEvents.java?ref_type=heads#L21). So for their own consistencies sake and for compat with all other mods that interact with Eyes of Ender that would better be corrected on their end.
