### ISSUE TITLE
[Feature] REI Move Items not supported in Pedestal

### ISSUE THREAD

**Issue by EzequielDM** [DaFuqs/Spectrum#235]
**Describe the bug**
REI Move Items in crafting not working

**To Reproduce**
Simply try to use a recipe inside a pedestal

**Expected behavior**
Should work

**Mod version**
1.7.0-deeper-down-alpha18

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/17010688/8de2abd7-cfbd-4e55-84d1-a0bbc4bfb0fe)

**Crash Report**
NULL

**Comment by EzequielDM** [comment]
Modlist just in case:
Mods:
  [✔] AE2WTLib-12.9.5
  [✔] amecs-1.3.8+mc.1.19-rc2
  [✔] appleskin-fabric-mc1.19-2.4.1
  [✔] appliedenergistics2-fabric-12.9.6
  [✔] architectury-6.5.85-fabric
  [✔] balm-fabric-1.19.2-4.5.7
  [✔] BetterF3-4.0.0-Fabric-1.19.2
  [✔] BetterPingDisplay-Fabric-1.19.2-1.1.1
  [✔] Bookshelf-Fabric-1.19.2-16.3.20
  [✔] borderless-mining-1.1.5+1.19
  [✔] Botania-1.19.2-440-FABRIC
  [✔] BotanyPots-Fabric-1.19.2-9.0.35
  [✔] c2me-fabric-mc1.19.2-0.2.0+alpha.9.10
  [✔] carpet-extra-1.19.2-1.4.84
  [✔] carpet-fixes-1.19-1.12.2
  [✔] chipped-fabric-1.19.2-2.1.5
  [✔] Chunky-1.3.38
  [✔] clientcommands-2.7.5
  [✔] clientcrafting-fabric-1.19.2-1.6
  [✔] clienttweaks-fabric-1.19.2-8.1.2
  [✔] cloth-config-8.3.103-fabric
  [✔] Controlling-fabric-1.19.2-10.0+7
  [✔] create_enchantment_industry-1.0.0
  [✔] create_jetpack-fabric-3.2.3
  [✔] createaddition-fabric+1.19.2-20230723a
  [✔] create-fabric-0.5.1-b-build.1089+mc1.19.2
  [✔] CreateFabricREIBugFix-0.1.5-create0.5.1-mc1.19.x
  [✔] create-track-map-1.4+mc1.19.2-fabric-create-0.5.1
  [✔] Cucumber-Refabricated-1.19.2-1.0.6
  [✔] DisableCustomWorldsAdvice-3.0
  [✔] entityculling-fabric-1.6.1-mc1.19.2
  [✔] essential_commands-0.33.2-mc1.19.2
  [✔] exordium-fabric-1.0.2-mc1.19.2-hotfix
  [✔] ExtendedDrawers-1.4.3+mc.1.19.2
  [✔] fabric-api-0.76.0+1.19.2
  [✔] fabric-carpet-1.19.2-1.4.84+v221018
  [✔] fabric-language-kotlin-1.10.8+kotlin.1.9.0
  [✔] fabrishot-1.9.2
  [✔] farmers-delight-fabric-1.19.2-1.3.10
  [✔] Fastload+1.18.2-1.20-3.4.0
  [✔] ferritecore-5.0.3-fabric
  [✔] ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric
  [✔] ftb-essentials-fabric-1902.3.3-build.100
  [✔] ftb-library-fabric-1902.4.1-build.236
  [✔] ftb-ultimine-fabric-1902.4.1-build.90
  [✔] ImmediatelyFast-1.1.12+1.19
  [✔] indium-1.0.9+mc1.19.2
  [✔] inventoryessentials-fabric-1.19-5.0.2
  [✔] InventorySorter-1.8.10-1.19
  [✔] invhud.fabric.1.19-3.4.7
  [✔] iris-flywheel-compat-1.19.2-0.2.1
  [✔] iris-mc1.19.2-1.6.4
  [✔] Jade-1.19.1-fabric-8.7.3
  [✔] JadeAddons-1.19.2-fabric-3.2.0
  [✔] krypton-0.2.1
  [✔] lazydfu-0.1.3
  [✔] ledger-1.2.5
  [✔] litematica-fabric-1.19.2-0.12.7
  [✔] litematica-printer-1.19-3.2
  [✔] lithium-fabric-mc1.19.2-0.11.1
  [✔] Log-Begone-Fabric-1.19.x-1.0.6
  [✔] LuckPerms-Fabric-5.4.66
  [✔] malilib-fabric-1.19.2-0.13.0
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] mixintrace-1.1.1+1.17
  [✔] Modern-Industrialization-1.6.12
  [✔] modmenu-4.2.0-beta.2
  [✔] moonlight-1.19.2-2.2.43-fabric
  [✔] moreculling-1.19.1-0.17.0
  [✔] MouseTweaks-fabric-mc1.19-2.22
  [✔] MysticalAgriculture-Refabricated-1.19.2-2.0.8
  [✔] no-telemetry-1.7.0
  [✔] observable-3.3.1
  [✔] opac-fabric-create-support-1.3.0
  [✔] open-parties-and-claims-fabric-1.19.2-0.19.2
  [✔] owo-lib-0.9.3+1.19
  [✔] Patchouli-1.19.2-77-FABRIC
  [✔] PickUpNotifier-v4.2.4-1.19.2-Fabric
  [✔] Powah-4.0.10
  [✔] PuzzlesLib-v4.4.3-1.19.2-Fabric
  [✔] rebind_narrator-fabric-1.19.2-2.0.1
  [✔] REICustomCommand-1.19.2-fabric-1.0.2
  [✔] rer-2.6.0
  [✔] resourcefullib-fabric-1.19.2-1.1.24
  [✔] revelationary-1.3.5
  [✔] RoughlyEnoughItems-9.1.632
  [✔] RoughlyEnoughLootTables-1.19-1.0
  [✔] RoughlyEnoughProfessions-fabric-1.19.2-1.1.4
  [✔] RoughlyEnoughTrades-1.19-1.0
  [✔] roughly-searchable-2.5.2+1.19.3
  [✔] sliceanddice-fabric-2.2.1
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] spark-1.10.37-fabric
  [✔] spectrum-1.7.0-deeper-down-alpha18
  [✔] StackDeobfuscatorFabric-1.4.0+a93f231
  [✔] starlight-1.1.1+fabric.ae22326
  [✔] Steam_Rails-1.4.3+fabric-mc1.19.2
  [✔] stoneholm-1.4.4
  [✔] supplementaries-1.19.2-2.3.20-fabric
  [✔] syncmatica-1.18.2-0.3.10
  [✔] TechReborn-5.4.0
  [✔] Terralith_1.19.3_v2.3.10
  [✔] toms_storage_fabric-1.19-1.5.9
  [✔] travelers-backpack-1.19.2-8.2.26
  [✔] trinkets-3.4.2
  [✔] tweakeroo-fabric-1.19.2-0.14.3
  [✔] visuality-0.5.6
  [✔] VisualWorkbench-v4.2.4-1.19.2-Fabric
  [✔] vmp-fabric-mc1.19.2-0.2.0+beta.7.30-all
  [✔] watson-fabric-1.14.4+1.19.2
  [✔] waystones-fabric-1.19.2-11.4.1
  [✔] worldedit-mod-7.2.12
  [✔] Xaeros_Minimap_23.6.0_Fabric_1.19.1
  [✔] XaerosWorldMap_1.31.0_Fabric_1.19.1
  [✔] YetAnotherConfigLib-2.2.0-for-1.19.2
  [✔] youre-in-grave-danger-1.4.9
  [✔] Zoomify-2.9.0

**Comment by DaFuqs** [comment]
Implemented in #331

**Comment by EzequielDM** [comment]
Amazing! Thanks @DaFuqs
