### ISSUE TITLE
ItemStack aware recipe remainders deleted

### ISSUE THREAD

**Issue by Linguardium** [DaFuqs/Spectrum#236]
https://github.com/DaFuqs/Spectrum/blob/084703c2680f9149c8f494d93cd3c9270d18017d/src/main/java/de/dafuqs/spectrum/blocks/pedestal/PedestalBlockEntity.java#L603

I would recommend calling the injected `ItemStack getRecipeRemainder(ItemStack stack)` method instead of the vanilla one, to ensure you dont accidentally start wiping out items. 

https://github.com/FabricMC/fabric/blob/1.19.2/fabric-item-api-v1/src/main/java/net/fabricmc/fabric/api/item/v1/FabricItem.java#L33C70-L33C70

**Comment by Linguardium** [comment]
also affects fabrication chest and likely anything else that uses the InventoryHelper method https://github.com/DaFuqs/Spectrum/blob/8d33b79cb44cca6750a474145cb51c0b34c805c4/src/main/java/de/dafuqs/spectrum/helpers/InventoryHelper.java#L311

**Comment by DaFuqs** [comment]
Absolutely. Pretty sure that code is back from 1.17.1 even, when that method did not even exist. Will do
