### ISSUE TITLE
[BUG] Preservation Ruin #2 not counting

### ISSUE THREAD

**Issue by EzequielDM** [DaFuqs/Spectrum#237]
**Describe the bug**
The second preservation ruin (dike ruin) did not count for me for whatever reason.

**To Reproduce**
All I did was roam around and do the puzzles.

**Mod version**
1.7.0-deeper-down-alpha18

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/17010688/f4a90280-ade6-43ce-8d4b-a1df8ff2546a) (fixed it by using `/advancement grant @p only spectrum:solve_dike_gate_preservation_ruin` before taking a screenshot of the book, you'll have to take my word for it...)

If any other players of our server get this, I'll make sure to document better than I did this time.

**Comment by DaFuqs** [comment]
No problem at all. I could not reproduce this in a freshly generated world, but it sounds very plausible, since I changed a lot about the structure advancements.

Was it in a world generated in one of the recent alphas, or an older one?

**Comment by EzequielDM** [comment]
Generated on deeper-down-alpha18

**Comment by EzequielDM** [comment]
Adding to this, another user reported the same issue. I'm inside the ruin he finished (not an already finished one) and he does not have the achievement. I feel this has something to do with us finding this one first, way before we can actually enter it. The other ones we did not touch before being able to enter. He did not get the achievement for this ruin.

![image](https://github.com/DaFuqs/Spectrum/assets/17010688/2f0f5dd8-a0f0-4e4b-be3c-6502b3a9d352)
Added manually to allow his progression

**Comment by EzequielDM** [comment]
Same happened to a third player. 

![image](https://github.com/DaFuqs/Spectrum/assets/17010688/644d3d6c-699a-4ad2-a3b0-372e90f68805)
**Nky614:** _I finished them all; tho the book shows i didnt do the 2nd_
**me**: _not this again;_

Went ahead and checked with the player, they finished all of them but didn't get an advancement for the dike ruin.
Again, adding manually through commands fixes the issue.

**Comment by EzequielDM** [comment]
If you want to test it out on our server where the issue seems to be recurring, contact me via Discord `@zekihvh` and I will make arrangements.

The issue seems to be tied to the sequence of events, first finding the ruin and not being able to go through, then starting out on the mod (none of the 3 players had touched Spectrum before finding the ruin) and then finishing the ruin and not receiving the advancement.

**Comment by DaFuqs** [comment]
Fixed for next alpha, thanks a ton!

**Comment by EzequielDM** [comment]
Good to know! I'm glad players will now pass the dike gate's vibe check 🤣
