### ISSUE TITLE
[BUG] Colored world book and fusion shrine issues

### ISSUE THREAD

**Issue by Sweet141** [DaFuqs/Spectrum#238]
**Describe the bug**
I am playing on a friend server with some mods, including Spectrum. When i open the book, it says this (see screenshot  N°1). Also, when i try to interact with the fusion shrine, If its not on the correct structure my game crash, if its on the structure but with no direct acces to the sky, my game doesnt crash and if there is a sky acces with no block on the way it crash again. (screenshot N°2)

**To Reproduce**
Steps to reproduce the behavior.
I dont know if you can reproduce it since it work perfectly on a private world, only bug in the server.

**Expected behavior**
A concise description of what you expected to happen.
I should be able to open the book and use the shrine in my server.

**Mod version**
Which version of the mod are you currently using?
1.19.2

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/117515678/696da332-3e37-4f8e-b4ef-32d9d7f80032)
![image](https://github.com/DaFuqs/Spectrum/assets/117515678/a9ff6e43-0e90-4e2f-9440-0f82c6bd7df1)
**Crash Report**
If it is a crash bug add your crash log here
[crash-2023-08-11_11.38.12-client.txt](https://github.com/DaFuqs/Spectrum/files/12320365/crash-2023-08-11_11.38.12-client.txt)

**Comment by 800020h** [comment]
full crash report please

**Comment by Sweet141** [comment]
[crash-2023-08-11_11.38.12-client.txt](https://github.com/DaFuqs/Spectrum/files/12320291/crash-2023-08-11_11.38.12-client.txt)

**Comment by DaFuqs** [comment]
Seems like connecting to the server does not register the Spectrum Multiblocks.

Do both server & client run Spectrum 1.6.12-1.19.2-leisure_time (probably yes, but does not hurt to check)

Other than that I got nothing, I am afraid. I can only suggest removing mods and check when it starts to work. As soon as we know the exact combination of mods that cause this I'll look into that and work on a fix.
