### ISSUE TITLE
[BUG] Celestial Pocketwatch not working

### ISSUE THREAD

**Issue by EzequielDM** [DaFuqs/Spectrum#239]
**Describe the bug**
Just unlocked and crafted the Celestial Pocketwatch, though it doesn't work for me. A friend that's playing with me in the same server can use it normally. 

**To Reproduce**
I have no clue how this happened.

**Expected behavior**
Should warp time

**Mod version**
deeper-down-alpha18

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/17010688/70c85315-fa80-4ec2-b4be-5efbddde7eae)
_(entry unlocked)_ 

![image](https://github.com/DaFuqs/Spectrum/assets/17010688/b0a77807-4aa3-4491-83ce-31061b48d522)
_(I do have ink)_

**Comment by DaFuqs** [comment]
Are you both in the overworld / same dimension?

**Comment by EzequielDM** [comment]
Yes

**Comment by EzequielDM** [comment]
Confirmed source of the problem.
If there's any other player online that has the watch unlocked, it doesn't work. I asked the last player that had it to log off and I'm now able to use the watch normally.

**Comment by DaFuqs** [comment]
That is some weird ass stuff. Will look into that

**Comment by EzequielDM** [comment]
> That is some weird ass stuff. Will look into that

If you need any help with testing anything, just send a message over here

**Comment by DaFuqs** [comment]
Did anyone still notice this in the most recent patches / 1.20.1?

**Comment by Noaaan** [comment]
If you get your hands on a pocketwatch early (in the sense of progession skipping or broken progression), what happens when you use the watch?

**Comment by DaFuqs** [comment]
> If you get your hands on a pocketwatch early (in the sense of progession skipping or broken progression), what happens when you use the watch?

As long as you have some ink on you, you can use it no problem
