### ISSUE TITLE
[Feature] While Pigment Pedestal has a defined Crafting Tablet, prevent autocrafting until grid matches recipe in tablet.

### ISSUE THREAD

**Issue by RubyRezal** [DaFuqs/Spectrum#24]
When using Compress'em recipes to compress common blocks like cobblestone, a Pigment Pedestal will start autocrafting any valid recipes.  This can cause the Pigment Pedestal to repeatedly play and cut off its crafting sounds as it passes through slab and wall recipes on the way to the full 3x3 grid.  This is just one example, there are many vanilla recipes this could apply to as well.

It would be nice if crafting tablets could make it so Pigment Pedestals would only start autocrafting once the crafting grid matches the tablet recipe.

Thanks!

**Comment by DaFuqs** [comment]
In Midgame8 the pedestal crafting mechanism has been changed.
It will only start to craft if it gets a redstone pulse. Are you at that version, or using a previous one?

**Comment by RubyRezal** [comment]
I'm testing in Midgame8, yes.  Here's my example setup.
![2022-01-17_14 50 37](https://user-images.githubusercontent.com/1816386/149829802-51f5cbec-0213-4644-abe9-0f9e9b0c2ceb.png)

I'm trying to compress cobblestone.  If I flip the lever on for continuous autocrafting the Pigment Pedestal will still try to craft cobblestone slabs and cobblestone walls then gets cut off when the hopper feeds in more cobblestone.
![2022-01-17_14 49 11](https://user-images.githubusercontent.com/1816386/149830032-43308f73-3eba-4005-8035-d926d3b3ce47.png)
![2022-01-17_14 49 12](https://user-images.githubusercontent.com/1816386/149830036-378d2811-422b-431c-83a8-3f1c76461f11.png)
![2022-01-17_14 49 13](https://user-images.githubusercontent.com/1816386/149830043-2c0d5311-847f-4b62-b63e-1f9b5f48943e.png)

**Comment by RubyRezal** [comment]
Doing the same thing with Iron Ingots, it will try to craft iron nuggets, an iron pressure plate, and iron bars before the input hopper finally fills the grid for a block of iron.

**Comment by DaFuqs** [comment]
Switching the lever for a small redstone clock / redstone timer that only triggers a redstone pulse when the Pedestal is filled correctly will solve your problem.
I get that it would be more convenient that a Pedestal with inserted Crafting Template would only be able to craft that single recipe. In contrast, setting up a small construction that times the required redstone pulse sounds like a very nice small automation challenge.

Personally I do not like "full automation solutions" in a single block. I will build such a construction and if it is easy to set up I would very much declare it as "works as intended". If really hard / unintuitive I will change it like you suggested,.

**Comment by DaFuqs** [comment]
Seeing that just adding a redstone clock to your construction mitigates your small issue I very much consider this a feature :)

**Comment by RubyRezal** [comment]
> Seeing that just adding a redstone clock to your construction mitigates your small issue I very much consider this a feature :)

that's fair.  A redstone clock or similar mechanism is easy enough a solution.
