### ISSUE TITLE
[Feature] Removal of potion effects from Potion Pendant

### ISSUE THREAD

**Issue by Aphyxia** [DaFuqs/Spectrum#240]
Or alternatively make topaz' removal of potion effects work for pendants also. Currently it does not seem to work for pendants.

**Comment by DaFuqs** [comment]
You should be able to just put the potion Pendant into a crafting grid to clear it (not 100% sure if that is a thing in the leisure-time versions yet. It definitely is in the alpha releases)

**Comment by Aphyxia** [comment]
Sorry. It seems I did not express myself clearly. I meant the visual effects (the swirly particles) that happen with potion effects. Those are rather annoying when wearing the pendant.
The pendant in crafting grid is indeed in 1.6 but it does nothing so yeah that is broken.

**Comment by DaFuqs** [comment]
Can confirm that Topaz Powder removes the visual particles on Pendants in alpha-20. ✅
