### ISSUE TITLE
[BUG] Registry remapping failed: Received iD map for minecraft:enchantment contains IDs unknoun to thereceiver!spectrum:disarming

### ISSUE THREAD

**Issue by DustanC** [DaFuqs/Spectrum#243]
![bda5b36c5c7ce70f29bea63bfd20d03](https://github.com/DaFuqs/Spectrum/assets/142276728/826a6c45-3fe4-4f01-a34c-68836d571231)
my friend cant play with me because of this mod,but I dont know how to change it.
Please help me.

**Comment by DaFuqs** [comment]
Make sure you two (and the dedicated server) are using the same Spectrum config. It has settings to disable enchantments like this one.

**Comment by DustanC** [comment]
> 确保你们两个（和专用服务器）使用相同的频谱配置。它具有禁用此类结界的设置。

but the spectrum he used was transmintted to him by me.why it became different.

**Comment by DaFuqs** [comment]
Maybe the modpack that you used disabled the setting? The default for that setting is enabled.
You know better why files on your two's PCs are different 😄
