### ISSUE TITLE
[BUG] Tight Grip enchantment removes Malachite Ultra Greatsword's bonus range

### ISSUE THREAD

**Issue by burrows4days** [DaFuqs/Spectrum#244]
**Describe the bug**
Applying the Tight Grip enchantment to a Malachite Ultra Greatsword causes the weapon's attack range bonus to disappear. It isn't just a text bug, the actual attack range becomes the same as all other swords.

**Expected behavior**
The attack range bonus stays when enchanted, like it does for other enchantments besides Tight Grip.

**Mod version**
spectrum-1.7.0-deeper-down-alpha19

**Screenshots**
![swordsbug](https://github.com/DaFuqs/Spectrum/assets/142636280/8a5ca350-4920-4b45-b4ad-8681ae0ed360)

**Comment by DaFuqs** [comment]
Fixed in alpha-20
