### ISSUE TITLE
[BUG] - Enchanting Seven League Boots doesn't give the advancement

### ISSUE THREAD

**Issue by EzequielDM** [DaFuqs/Spectrum#245]
**Describe the bug**
Even after enchanting the Seven League Boots with Power V it doesn't trigger the advancement.

**Mod version**
deeper-down-alpha18

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/17010688/02d17e13-6140-45b2-a85b-a90da74df0c6)
*Força V = Power V (translated)*

![image](https://github.com/DaFuqs/Spectrum/assets/17010688/6b2d6961-14d2-45d8-8366-34ef32b7cb67)

**Comment by EzequielDM** [comment]
Same happens for the Exchange Staff and it's advancement

**Comment by DaFuqs** [comment]
Fixed in alpha-20
