### ISSUE TITLE
[BUG] Mutliblocks not registered

### ISSUE THREAD

**Issue by SharkOSix** [DaFuqs/Spectrum#246]
**Describe the bug**
A previously shown bug with fusion alters its also breaking the spectrum book. Placing the fusion alter is fine (placing it by itself), but when placed with the multiblock structure and right clicked to use will crash your game. Spectrum book can't be used and just shows an error for the fusion alter (will be shown in screenshots) .

**To Reproduce**
Join a server, get a fusion alter, make the fusion alter structure and right click you crash. Spectrum book is join a server, right click book can't see progression stages (I've been using achievements and YouTube videos).

**Expected behavior**

Expected to crash, and not show progression in book.

**Mod version**
spectrum-1.6.12-1.19.2-leisure_time.jar
https://www.curseforge.com/minecraft/modpacks/wayfarer-smp-pack (Mod Pack used) 

**Screenshots**
![2023-08-21_17 32 52](https://github.com/DaFuqs/Spectrum/assets/142845104/7b4e5475-915a-4c3a-b1c9-0acf69183b41)
![2023-08-21_17 33 59](https://github.com/DaFuqs/Spectrum/assets/142845104/18663060-beb5-486b-9568-24e17a1b1d4b)

**Crash Report**
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "vazkii.patchouli.api.IMultiblock.validate(net.minecraft.class_1937, net.minecraft.class_2338, net.minecraft.class_2470)" because "multiblock" is null (this is on crash ticket).

[crash-2023-08-21_17.35.40-client.txt](https://github.com/DaFuqs/Spectrum/files/12402751/crash-2023-08-21_17.35.40-client.txt)

**Comment by SharkOSix** [comment]
If you need a server to replicate issue I am fine DMing you the server IP as it is a public server

**Comment by Trent2087** [comment]
> If you need a server to replicate issue I am fine DMing you the server IP as it is a public server

I'm going to assume the pack has MA 2.0.8... which is breaking spectrum. You will want to downgrade that...

**Comment by DaFuqs** [comment]
^
