### ISSUE TITLE
Cinderhearth crash

### ISSUE THREAD

**Issue by 00ffaa** [DaFuqs/Spectrum#247]
Version 1.6.12
When using the Cinderhearth, leads to minecraft crashing

Put any item into the smelting slot of the Cinderhearth, leads to the game immediately crashing

Expected item to instead smelt into desired result.
 
**Crash Report**
If it is a crash bug add your crash log here
[crash-2023-08-24_22.49.32-server.txt](https://github.com/DaFuqs/Spectrum/files/12435091/crash-2023-08-24_22.49.32-server.txt)

**Comment by DaFuqs** [comment]
Fixed in alpha-20
