### ISSUE TITLE
[BUG] Crystal logged mermaid bush doesnt apply effects

### ISSUE THREAD

**Issue by Linguardium** [DaFuqs/Spectrum#248]
**Describe the bug**
Crystal Fluid source blocks apply an effect. only full source blocks apply this effect. Fluid logged and flowing crystal fluid do not apply the effect. If a source block is needed, fluid logged blocks should apply the effect as well.

**To Reproduce**
place fluid, plant bush, stand on bush

**Expected behavior**
effect is applied

**Mod version**
1.6.12-1.19.2

**Comment by DaFuqs** [comment]
That is a tricky one. I'll note that down for later.

**Comment by DaFuqs** [comment]
Fixed via https://github.com/DaFuqs/Spectrum/commit/b9f667028c69dc20f0d2259650430e1e70da0550
