### ISSUE TITLE
[BUG] Bottle o' Enchanting recipe consumes XP orb

### ISSUE THREAD

**Issue by Shibva** [DaFuqs/Spectrum#249]
**Describe the bug**
According to the book, 10 points of XP are supposed to be extracted when making a bottle o' enchanting; however it its consumed in the process

**To Reproduce**
Create one, try a regular one and then an enchanted one

**Mod version**
Deeper Down Alpha 19

**Crash Report**
If it is a crash bug add your crash log here

**Comment by DaFuqs** [comment]
Fixed in alpha-20
