### ISSUE TITLE
[BUG] Voidbundletooltipdata crash

### ISSUE THREAD

**Issue by zlohbierdcul** [DaFuqs/Spectrum#25]
**Description**
Game crashes trying to display Voidbundletooltip.
Bedrockify has a feature to display the item tooltip when selected in the hotbar.  
![bedrockify](https://user-images.githubusercontent.com/82916072/150617289-55166bca-b0da-428b-88fc-051eb78ce48e.png)

**To Reproduce**
Hold the Voidbundle in the hand when Mod: 'Bedrockify' is installed.

**Mod version**
Spectrum - Midgame8
Bedrockify - 1.3.0  (https://github.com/juancarloscp52/BedrockIfy)
FabricAPI - 0.45.2

**Crash Report**
[crashreport.txt](https://github.com/DaFuqs/Spectrum/files/7917284/crashreport.txt)

**Comment by LKD-PIX** [comment]
SmoothScrollingEverywhere, SlightGUIModifications and Fabrication are also installed, but not mentioned in the stacktrace

**Comment by DaFuqs** [comment]
Try updating Iceberg Library
