### ISSUE TITLE
[Feature] Add a "Compass" to the REI/JEI recipie UI for the Enchanter

### ISSUE THREAD

**Issue by Shibva** [DaFuqs/Spectrum#250]
At first when I tried using the Enchanter to make a book, nothing happened. It was only after I remembered a simular thing from Better End's Infuser having the recipe referencing due north that I tried it on the enchanter and it started working

The suggestion is to include some sort of map compass or some background overlay to the Recipe UI to indicate the receive being viewed is in reference to being facing northward to avoid possible confusion

**Comment by Linguardium** [comment]
are you sure you didnt have the diagonals crossed? The only issue i have causing issues with book creation is that the diagonals must be in the correct place (for example, top left would be front left when looking in a given direction). accidentally putting the top-left and bottom right ingredient in the top right and bottom left slots will fail

**Comment by Shibva** [comment]
Yeah might be it? I'll have to try this further to check

**Comment by Shibva** [comment]
Yep it is 

My bad
