### ISSUE TITLE
[Contribution] Expanded Cross Content plan

### ISSUE THREAD

**Issue by Shibva** [DaFuqs/Spectrum#256]
I am making this a separate "issue" to help keep track of things.
### Please be aware that I do NOT know how to code in java; however, my interest in tinkering with datapacks have given me some knowledge on how to contribute in that area

I plan on contributing some cross-mod interactions with Spectrum to increase some of the interactivity with other mods though Mod Integration. While I neither can nor know how to code in Java, I have been growing familiar with the data pack aspect of Minecraft and therefore an understanding of the portion of a mod that uses the data pack system to add certain content such as recipes.

The objective here is for me to make and propose cross-content with Spectrum; primarily focusing on the Potion Workshop via pull/merge requests.

### Why am I doing this?
Because this mod reminds me much of Chromaticraft and my experience with this mod so far (while slow due to various other mods I have in place to slow me down a bit and my attention span lel) was great and I feel that this is something I can contribute to thanks to you @DaFuqs for responding nicely and with interest to my ideas.

### What's your plan?
Currently, I have a list of things I plan on extending content for, they are the following.

- [ ] Bewitchment (some brews are workable, though it won't be all of them :P, My idea here is to use an NBT version of Mandrake that is "energized" with ME to allow for some of the brews to work under the impression that a "workaround" with this craft was made possible to brew with the Potion Workshop
- [ ] YTTR (some content is not finished and may be susceptible to change but I feel that for the time being I can provide some interesting things to the table, Powerful yet expensive reagents; will be holding off on this one till content is pushed onto their Cursefroge page, as I am currently using a dev-build that WAS on there at one point.)
- [ ] Fuz's Mutant Mobs (Basic integration, adds brew recipe for chemical X )
- [ ] The Bumblezone (adds in one or 2 effects)
- [ ] Zenith (a few effects to the brewery, some other crafting things as well; might include a change to disable base-trident recipe added by spectrum to be replaced with an alternate recipe to power an inert-trident; May or May not include recipes for Masterwork, Twisted and Corrupt that bypasses the process in Zenith; however at a very high cost )
- [ ] More Botania stuff (Mana Potion in particular; I'm thinking of making it into a Roulete-type reagent that can make a great brew, to one that's fine or one that is downright terrible for the situation. Feeling Lucky? (This is due to the fact that drinking it causes a random event to happen, so why not? :P)
#### Please note that this list may be subject to change and may be expanded on; feel free to give feedback if you have any ^u^

**Comment by Pqvel1l** [comment]
I wish there was more compatibility with Miskatonic Mysteries

**Comment by DaFuqs** [comment]
That's a long, impressive list!
I always feel honored when people want to contribute because they like the mod, makes me happy.

Ideally, everything you want to do will be exposed via data pack already. If you find anything lacking, like #255, just open a new Feature Request and I'll look into it code-wise.

**Comment by Shibva** [comment]
I would like to apologize for the lack stuffs and radio silence; I'm currently taking a break from fabric for the time being, but I still plan to introduce the stuff within time; hopefully before the end of October

**Comment by DaFuqs** [comment]
Take all the time you need, no worries. It's a hobby after all, not a job and should be fun, not stressful.

**Comment by Shibva** [comment]
thanks

oh yeah; idk if this is fixed yet but Saturation from your drinks (your saturation) appears to not be working period; unless your saturation works differently

**Comment by DaFuqs** [comment]
It's much slower than vanilla saturation, so it doesn't give insane regeneration abilities with low potency (since life regeneration is based on how full the saturation bar is).
At potency 3+ you should see some decent saturation effects that keep you fed when mostly standing around.

**Comment by Shibva** [comment]
maybe have a unique look to this one instead of the normal saturation icon and maybe call it something else to avoid confusion

mention it in the book too why don'tcha

**Comment by DaFuqs** [comment]
I will close this for the time being, but if you start working on it again, feel free to reopen or ask me whenever you need something
