### ISSUE TITLE
Font Question

### ISSUE THREAD

**Issue by MEGATREX4** [DaFuqs/Spectrum#257]
Hi, [@hnufelka](https://github.com/hnufelka) and I are translating your mod into Ukrainian, don't worry about the quality, we are experts and have already translated Immersive Engineering and about a hundred other small and large mods.

I really liked your mod, I'm grateful for it, it's a really good job. Is there any way to add letters to the font for the tabs in the creative menu? Thanks for the answer, it's very important for me, it would be great if I could localize mod completely <3

_PS Sorry, I don't know how to add Labels_

> ![image](https://github.com/DaFuqs/Spectrum/assets/59817721/c9ec5cb7-b877-4695-b16d-da34c5437644)

**Comment by DaFuqs** [comment]
No, sadly. The tiny font used there only has a very limited character set. :(

**Comment by MEGATREX4** [comment]
thanks for the answer
