### ISSUE TITLE
[BUG] attempting to view any progression hint causes a CTD

### ISSUE THREAD

**Issue by Hoxeji** [DaFuqs/Spectrum#258]
**Describe the bug**
Using the Colorful World book normally causes no issues but attempting to view any of the progression hint chapter causes an instant CTD

**To Reproduce**
Open any progression hint chapter will cause this bug

**Expected behavior**
to be able to view your current progression hints

**Mod version**
Spectrum 1.6.9 (curseforge)

**Crash Report**
https://pastebin.com/9yv9KxvJ

**Comment by DaFuqs** [comment]
This is caused by a breaking change in Patchouli. Update Patchouli to the newest Patchouli-1.18.2-71.1-FABRIC.jar
