### ISSUE TITLE
[BUG] Colorful World Book Loading Error | Fusion Shrine

### ISSUE THREAD

**Issue by cranberriez** [DaFuqs/Spectrum#259]
**Describe the bug**
![colorful_world_fail](https://github.com/DaFuqs/Spectrum/assets/24465331/84349541-b3db-4024-a257-6e518922b1a4)
No information in the server log about this.

**To Reproduce**
Unsure; very mod-heavy modpack. However, the bug only occurs when viewing the book on a server. Opening the book in single-player has it load fine.

**Expected behavior**
The book should load? As it does in singleplayer.

**Mod version**
spectrum-1.6.12-1.19.2-leisure_time.jar

**Screenshots**
Seen above.

**Crash Report**
Not Crashing.

**Comment by Gronglegrowth** [comment]
Do you have Mystical Agriculture? If yes, you need to downgrade it to 2.0.5

**Comment by cranberriez** [comment]
Will do, I have mystical agriculture at 2.0.8. Is this an issue only on servers?

Also found the logs: [https://pastebin.com/bXEi32Jq](https://pastebin.com/bXEi32Jq)

**Comment by Gronglegrowth** [comment]
This is the exact same issue as #206 and #209, you can view those for more detail

**Comment by cranberriez** [comment]
Appreciate the quick response, didn't see those issues as I hadn't checked closed issues. Will close mine as well.
