### ISSUE TITLE
[BUG] z-fighting in Spectrum redstone components unlit redstone torches

### ISSUE THREAD

**Issue by RubyRezal** [DaFuqs/Spectrum#26]
**Describe the bug**
z-fighting in unlit torches of redstone components 

**To Reproduce**
Place Spectrum redstone components. Default resourcepacks.

**Expected behavior**
no z-fighting

**Mod version**
spectrum-1.2.7-1.18.1-midgame8

**Screenshots**
![2022-01-22_14 03 50](https://user-images.githubusercontent.com/1816386/150652070-a67c8285-5371-4fed-a2ae-e690c27ad054.png)
![2022-01-22_14 03 53](https://user-images.githubusercontent.com/1816386/150652073-ae388875-3999-4ea3-a7a1-d85fa14e1bfd.png)

**Comment by DaFuqs** [comment]
NVidia graphics?

**Comment by RubyRezal** [comment]
Yes, with and without Sodium on client.

**Comment by DaFuqs** [comment]
fixed in the next version. Thank you for the report!
