### ISSUE TITLE
[Feature] Add compat for Friends & Foes lightning rods

### ISSUE THREAD

**Issue by cravl-dev** [DaFuqs/Spectrum#260]
Currently the storm stone spawning logic only checks for the vanilla lightning rod, and so no storm stones ever spawn with F&F rods (thus the moment it oxidizes it stops working, and you can't wax it either). It would be nice to check if F&F is installed and if so use the `#friendsandfoes:lightning_rods` tag instead.

**Comment by DaFuqs** [comment]
Sure

**Comment by DaFuqs** [comment]
Released in alpha-21
