### ISSUE TITLE
[BUG] AE2 compat Flawless Budding Certus recipe

### ISSUE THREAD

**Issue by Surnyy** [DaFuqs/Spectrum#261]
**Describe the bug**
Been having an issue where crafting the Flawless Budding Certus from AE2 using the Spirit Instiller isn't working.
One item, the Flawed Certus, doesn't even show up in REI (screenshot below) and the craft doesn't work, neither with nor without said Flawed Certus.

**To Reproduce**
Playing on a server, if it matters

**Mod version**
deeper-down-alpha19, if this is fixed in later versions, my bad

**Screenshots**
![javaw_2023-10-04_01-16-27](https://github.com/DaFuqs/Spectrum/assets/68776821/32d907b7-9abc-4d78-814c-f1d602f10402)

I have noticed in the data describing compat recipes that this part in particular in `(src/main/resources/data/spectrum/recipes/mod_integration/ae2/spirit_instiller/flawless_budding_quartz.json)` seems a little odd:

```
{
  "type": "spectrum:spirit_instiller",
  "time": 400,
  "experience": 8.0,
  "ingredient1": {
    "tag": "ae2:flawed_budding_quartz"
  },
  "ingredient2": {
    "item": "ae2:charged_certus_quartz_crystal"
  },
  "center_ingredient": {
    "item": "spectrum:neolith",
    "count": 4
  },
  "result": {
    "item": "ae2:flawless_budding_quartz"
  },
  "fabric:load_conditions": [
    {
      "condition": "fabric:all_mods_loaded",
      "values": [
        "ae2"
      ]
    }
  ]
}
```
how come ingredient1 uses "tag" instead of "item" here, like you'd expect it to? I haven't tested if changing would fix it, but it sounds reasonable to me.

**Comment by DaFuqs** [comment]
There's  a simple reason why: I'm dum

**Comment by DaFuqs** [comment]
thank you!
