### ISSUE TITLE
[BUG] Visual Bug with Fishing Rod Line Rendering 1.19.2

### ISSUE THREAD

**Issue by DonorKrovi** [DaFuqs/Spectrum#264]
**Describe the bug**
A strange visual bug with the fishing rod when playing online, for some reason the line joins other floats

**To Reproduce**
![image](https://github.com/DaFuqs/Spectrum/assets/60231586/611babb6-d740-48b0-aa5a-5733fe116fc0)

**Expected behavior**
A concise description of what you expected to happen.

**Mod version**
https://github.com/DaFuqs/Spectrum/actions/runs/6495680751

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/60231586/611babb6-d740-48b0-aa5a-5733fe116fc0)

**Crash Report**
Nope

**Comment by DaFuqs** [comment]
Does not seem to happen with Spectrum alone? Any other mods that come to mind that may interfere?

**Comment by DonorKrovi** [comment]
> Похоже, что это не происходит только со Спектрумом? Есть ли еще какие-нибудь моды, которые приходят на ум, которые могут помешать?

hmm, idk

**Comment by 800020h** [comment]
isn't it a vanilla bug?

**Comment by Mosklia** [comment]
A vanilla bug. I experienced this when playing vanilla with friends.
And the bug seems to be aging.

**Comment by DaFuqs** [comment]
See https://github.com/IrisShaders/Iris/issues/2041
