### ISSUE TITLE
[Feature] Pedestals pull items needed automatically from inventory above it when it has a crafting tablet.

### ISSUE THREAD

**Issue by Mosklia** [DaFuqs/Spectrum#269]
When a pedestal has a configured crafting tablet in its tablet slot, and it is charged by redstone, it tries to pull ingredients it needs to its inventory from the inventory above it. So that you do not have to break the multiblock and use lots of hopper, to automate some recipes.

**Comment by eehunter** [comment]
I would think that the Pastel Network would provide an alternative to this, but perhaps a solution should be available earlier on? Maybe the input inventory should be on the side, though, since the pedestal also outputs to the top?

**Comment by DaFuqs** [comment]
I thought about that one and agree with eehunter here. Having nice item transfer sounds like the more intuitive solution
