### ISSUE TITLE
game crashes when you put spectrum mob heads in cosmetic armor slot

### ISSUE THREAD

**Issue by GodlyBDS** [DaFuqs/Spectrum#27]
**Describe the bug**
cosmetic armor adds a new armor slot which is as the name suggests only cosmetic but when i put a spectrum mob head in it it crashes

**To Reproduce**
download https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric and put mob head in the new armor slot and it should crash instantly

**Expected behavior**
not crashing able to wear armor while displaying the mob head as cosmetic

**Mod version**

1.2.8-midgame9

**Screenshots**
unable to because the game crashes instantly when trying to look at the player

**Comment by DaFuqs** [comment]
Has to be resolved by https://github.com/apace100/cosmetic-armor/issues itself. Sorry, does not seem like I can do anything about it myself.
