### ISSUE TITLE
[Feature] Make fluid drinkable (in Traveler's Backpack)

### ISSUE THREAD

**Issue by Mosklia** [DaFuqs/Spectrum#271]
Make the four new fluid drinkable and give the drinker effects, when stored in tanks of Traveler's Backpack.
Here are my ideas:
- Mud: grant nausea and slowness;
- Liquid Crystal: grant regeneration;
- Midnight Resolution: grant wither and blindness;
- Dragonrot: grant life drain.

**Comment by DaFuqs** [comment]
Drinkable = in bottles, you mean?

I'll see what I can do about that. Sounds fun!

**Comment by Mosklia** [comment]
> Drinkable = in bottles, you mean?
> 
> I'll see what I can do about that. Sounds fun!

Emm...Not exactly
I mean Traveler's Backpack allows player to drink fluids in the backpack's tank, including lava. But...bottles of Liquid Crystal sounds even more fun!
And there is also a bug: when potions from Potion Workshop is stored into the tank of Traveler's Backpack, it simply becomes "No Effect" potion. I feel this should be solved by the backpack mod?

**Comment by Mosklia** [comment]
Tested on latest Spectrum Essentials.

**Comment by DaFuqs** [comment]
I'll check out backpack drinking, then.

Yes, the 'no effect' part would have to be solvrd by them. Sounds they just handle the default potions, ignoring potions with the `CustomEffects` tag (which is also a thing in vanilla).

**Comment by Mosklia** [comment]
I will open an issue in their repo later, if there's none.

**Comment by DaFuqs** [comment]
Looks like there is!
https://github.com/Tiviacz1337/Travelers-Backpack/issues/712

I've left a comment for them.

**Comment by Mosklia** [comment]
Thanks lol.
