### ISSUE TITLE
[Feature] Automated pigment producing

### ISSUE THREAD

**Issue by Mosklia** [DaFuqs/Spectrum#273]
Is it possible to make pigment producing automated? For example, something can eat (break) ALL the colored leaves on a tree and dropping pigments.
Automated tree planting is solved, but breaking leaves in vanilla ways or other mods' ways seems not dropping pigments.

**Comment by DaFuqs** [comment]
Boy do I have news for you.

- Next alpha build will feature a simple block breaker that respects player advancement checks.
- Fabric API 1.20 includes a fake player module that will greatly extend compat with other mods block breakers
- One of Spectrums next major releases will feature a very powerful and easy way to farm loads of ink

**Comment by DaFuqs** [comment]
A simple way of breaking cloaked blocks using the players progression is now in. Will be expanded later as mentioned ✅

**Comment by Mosklia** [comment]
Seems still not enough...

A huge redstone machine is still needed. (A wall of prisons pushing the whole tree to a wall of breaker.)
