### ISSUE TITLE
[Feature] Ink as a fluid

### ISSUE THREAD

**Issue by Castone22** [DaFuqs/Spectrum#285]
It would be great if it was possible to fill a bucket with ink in the color picker, and then dump it to get liquid ink on the ground for decorational purposes.  

Perhaps the ink could even apply a minor buff while standing in it; like pink applying a very weak regeneration or  magenta making your buffs expire slightly faster.

Mostly i just want to have fun colored water flowing in my base.

**Comment by DaFuqs** [comment]
That would indeed be cool and would nicely fit into the theme of the next update. Maybe, maybe!

**Comment by DaFuqs** [comment]
Since Ink behaves more like a gas, I do not think adding a fluid variant would be fitting, thematically. Some other form of colored fluid could be nice, though.
