### ISSUE TITLE
[BUG] Being reduced to half a heart by dragonrot while under divinity won't proc the advancement

### ISSUE THREAD

**Issue by Castone22** [DaFuqs/Spectrum#286]
**Describe the bug**
Being reduced to half a heart while under the effects of deadly poison and life drain from taking a dip in dragonrot does not grant the dangerously close to gods advancement.

**To Reproduce**
Take a dip in dragonrot to get afflicted with deadly poison and life drain, let yourself drop to 1 hp, then drink freigeist to ascend.

**Expected behavior**
Should gain the Dangerously Close to Gods advanancement.

**Mod version**
1.7.0

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/12468749/82110fb2-f35d-4a2b-8447-4ef607f4aa25)

**Comment by Electro593** [comment]
This should be fixed in the next release.
