### ISSUE TITLE
[BUG] Game does not launch

### ISSUE THREAD

**Issue by Cataratas** [DaFuqs/Spectrum#287]
Game does not launch with spectrum installed.
My modpack is big so maybe it's an incompatibility, however I don't have the time right now to check that.
Here's my log file:

[latest.log](https://github.com/DaFuqs/Spectrum/files/13572970/latest.log)

**Comment by DaFuqs** [comment]
Wow, you were quick. Redownload from Curseforge / Modrinth, please. A recent fabric change that was still untested broke some stuff and had to be fixed quickly.
Sorry!
