### ISSUE TITLE
[BUG] Guidebook loading error

### ISSUE THREAD

**Issue by Cataratas** [DaFuqs/Spectrum#288]
When opening the guidebook, there's a loading error that says:

Error building entry spectrum:mod_integration/ae2 of book spectrum:guidebook
Error while building entry spectrum:mod_integration/ae2 page 1 of book spectrum:guidebook
Unkown item ID: ae2:quartz_growth_accelerator

Perhaps you meant "ae2:growth_accelerator"?

**Comment by DaFuqs** [comment]
Looks like that block was renamed in 1.20, good catch!

**Comment by DaFuqs** [comment]
Fixed for release tomorrow

**Comment by luo-zi** [comment]
same problem in zh_cn folder
