### ISSUE TITLE
[BUG] Server crashes when trying to craft Workstaff

### ISSUE THREAD

**Issue by MysticWolfy** [DaFuqs/Spectrum#290]
What happens is when trying to craft the malachite workstaff, the server crashes immediately upon putting all items inside the fusion shrine.

**To Reproduce**
Place all items inside the fusion shrine to make the malachite workstaff and the server will crash.

**Crash Report**
[crash-2023-12-07_18.10.33-server.txt](https://github.com/DaFuqs/Spectrum/files/13603596/crash-2023-12-07_18.10.33-server.txt)

**Comment by DaFuqs** [comment]
Fixed in 1.7.2 ✅
