### ISSUE TITLE
[BUG] 1.20.1 wont work with Quilt

### ISSUE THREAD

**Issue by sleepy-evelyn** [DaFuqs/Spectrum#292]
**Describe the bug**
Unfortunately the Quilted Fabric API is outdated so you can't run the latest Spectrum versions 1.7.1 and 1.7.2 for 1.20.1.
Unless you are using new features from Fabric API it might be worth downgrading to version 0.90.0 of the Fabric API

<img width="805" alt="Screenshot 2023-12-07 at 22 19 06" src="https://github.com/DaFuqs/Spectrum/assets/46009144/0d296e3a-6a53-4da7-bf97-1a19dc7d4dd7">

**Comment by Azzyypaaras** [comment]
_gdude's failed gambit does not work with Spectrum_

And nothing of value was lost.

Also hi Eve :3

**Comment by Azzyypaaras** [comment]
On a more serious note. 

While I cannot speak for Daf, I do not find it proper to undo an upgrade because of an issue on another party's end. Especially given the fact that said party is another modloader who's job is to ensure compatibility. Doubly especially so because this is likely to be a temporary issue.

**Comment by sleepy-evelyn** [comment]
> _gdude's failed gambit does not work with Spectrum_
> 
> And nothing of value was lost.
> 
> Also hi Eve :3

Hi Azzy 👋.

Yeah there is no issue really using the latest version of the fabric API. Quilt is just lagging behind atm. I don't think it's gonna get fixed unfortunately until 1.20.2 :/.

It might be worth declaring on Modrinth + Curseforge that the mod wont work for Quilt for 1.20.1 though until it is fixed.

**Comment by sleepy-evelyn** [comment]
Been testing a bit and it definitely works fine with Fabric API 0.90.0. There isn't anything that relies on 0.90.1 I don't think.
Had to change the advancement registry accessor because apparently that doesn't want to work as well. Although tbf the criteria doesn't need an accessor now :3.

Linked issue: https://github.com/DaFuqs/Revelationary/issues/9

**Comment by sleepy-evelyn** [comment]
Fixed with #294

**Comment by DaFuqs** [comment]
> It might be worth declaring on Modrinth + Curseforge that the mod wont work for Quilt for 1.20.1 though until it is fixed.

Done.

Since it's just a minor downgrade that does not affect anything we're using I have no issue with downgrading FAPI. Especially since FAPI 0.15.0 is still causing issue with lots of other mods, too.
