### ISSUE TITLE
[BUG] Creative screens a Lil' teeny bit laggy

### ISSUE THREAD

**Issue by sleepy-evelyn** [DaFuqs/Spectrum#293]
**Describe the bug**
Creative screen is a bit laggy. With or without REI enabled / disabled.

**To Reproduce**
Open the Spectrum creative screen.

**Mod version**
1.7.2 - 1.20.1

**Video**
https://github.com/DaFuqs/Spectrum/assets/46009144/88f2e402-e5eb-4a98-87f7-b459e6eca05c

**Comment by DaFuqs** [comment]
Spark: https://spark.lucko.me/Kg3sjnOYcR

![image](https://github.com/DaFuqs/Spectrum/assets/26429514/0774a024-1694-4c9a-a44e-3e462af35251)

Looks like the cause if the big amount of draw calls done for the tabs and their font.

**Comment by sleepy-evelyn** [comment]
> Spark: https://spark.lucko.me/Kg3sjnOYcR
> 
> ![image](https://private-user-images.githubusercontent.com/26429514/289109326-0774a024-1694-4c9a-a44e-3e462af35251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTUyMDIsIm5iZiI6MTcwMjE1NDkwMiwicGF0aCI6Ii8yNjQyOTUxNC8yODkxMDkzMjYtMDc3NGEwMjQtMTY5NC00YzlhLWE0NGUtM2U0NjJhZjM1MjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIwNDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZTYwODhkODRiNjc5NmUxNWRmYWYwYTRiYTdkYjM2MTY0MjQ3NTNjYWQ4NjBkODA1YTQ5MGQxNjFiZjAwZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RqVEUwncJlc_QjAPq4g2F2kv4LDlQPpbANiYGwCBWrE)
> 
> Looks like the cause if the big amount of draw calls done for the tabs and their font.

That makes sense actually because it lags the same amount regardless of the tab screen and the background file isn't large at all :3

**Comment by DaFuqs** [comment]
Improved via https://github.com/DaFuqs/Spectrum/commit/b02b443e24b7d7249ddc0bdf02dba5659b83244fthanks to @Noaaan
