### ISSUE TITLE
[BUG] Terrace House Cellar Chests sometimes generate pointed at the wrong loot table

### ISSUE THREAD

**Issue by Castone22** [DaFuqs/Spectrum#295]
**Describe the bug**
Some terrace houses generate with a loot table pointed at terrace_houses_cellar instead of terrace_house_cellar, causing a minecraft error to show up in the console stating this, and the chest to be empty.

**To Reproduce**
Open chests in terrace house cellars in a City Below, you'll get the error at some point

**Expected behavior**
Every chest should have content

**Actual behavior**
Some chests won't contain anything

**Mod version**
1.7.1

**Extra Information**
Lootr may be involved, as our server uses it, however the error is an actual minecraft error for when it tries to roll a loot table that hasn't been defined.

**Comment by Castone22** [comment]
Found a copy of the error.
[07:21:47] [Render thread/INFO]: [CHAT] [07:21:47] [DISCORD] <N8crafter> [Render thread/INFO]: [CHAT] [03:27:22] The loot table for this container [spectrum:chests/city_below/terrace_houses_cellar] resolved to empty and loot could not be generated. Check your `latest.log` for errors.

Latest log doesn't have any errors in it besides this one.

**Comment by DaFuqs** [comment]
done, ty!
