### ISSUE TITLE
[Feature] Allow items to be withdrawn by hand from a placed Bottomless Bundle

### ISSUE THREAD

**Issue by Castone22** [DaFuqs/Spectrum#296]
Bottomless Bundles make fantastic deep storage blocks, except that there's no way to withdraw the items inside of them without picking them up or attaching some sort of withdrawal mechanism like a create chute under it attached to a chest.  It would be nice if punching them would withdraw stacks of items inside of them like a barrel or a storage drawer, and holding a modifier key of some sort would withdraw a single item, maybe even having them render the contained item on the side when in world.

**Comment by DaFuqs** [comment]
Great suggestion, agreed

**Comment by DaFuqs** [comment]
Implemented via https://github.com/DaFuqs/Spectrum/commit/fd9caf851309e8d8e0d75b7974b8e1510a3f6dbf and https://github.com/DaFuqs/Spectrum/commit/f55c52bb29646a6e276eccec07e399ca03b6a8f0
