### ISSUE TITLE
[BUG] Most blocks do not have a MapColor defined (1.20.1)

### ISSUE THREAD

**Issue by unilock** [DaFuqs/Spectrum#297]
**Describe the bug**
Most of the blocks registered by Spectrum do not define a `MapColor`.

**To Reproduce**
N/A

**Expected behavior**
The blocks have a `MapColor` defined via the `FabricBlockSettings` builder.

**Mod version**
1.7.2

**Screenshots**
N/A

**Crash Report**
N/A

**Additional context**
In 1.19.2, this was handled by `FabricBlockSettings.of(Material.<base material>)` (e.g. `Material.AMETHYST` for gemstone storage blocks and `Material.STONE` for Polished Basalt and Calcite), which would copy all settings of a previously defined (vanilla) block, including its `MapColor`.

However, the `Material` enum no longer exists on 1.20 for absolutely no good reason, so `MapColor`s must be defined via `FabricBlockSettings.create().mapColor(DyeColor.<color>)` or `.mapColor(MapColor.<color>)` (as some other blocks already have done).

For comparison, the gemstone storage block settings definition in:
[1.19.2](https://github.com/DaFuqs/Spectrum/blob/7aebcbf68a52a368bc629bfbb90887d46090de0d/src/main/java/de/dafuqs/spectrum/registries/SpectrumBlocks.java#L829)
[1.20.1](https://github.com/DaFuqs/Spectrum/blob/3296def20222964ff3129ea568eef88d7636030a/src/main/java/de/dafuqs/spectrum/registries/SpectrumBlocks.java#L825)

For context, I believe the lack of a `MapColor` defined for each block is the cause of the following issue present in the Xaero's Minimap / Xaero's World Map mods:
<img width="930" alt="image" src="https://github.com/DaFuqs/Spectrum/assets/11802133/6ed6b908-0963-4408-b679-e137f1286a79">

**Comment by thexaero** [comment]
Some info on why the issue isn't on my end:
My mods check for the existence of vanilla map colors because they are required for the optional vanilla color mode.
If some blocks in this mod don't have map colors defined, then they also don't show up on vanilla maps, so the problem goes beyond my map mods.

**Comment by DaFuqs** [comment]
Very much agreed, yes.
