### ISSUE TITLE
[DUPE BUG] Breaking a placed bundle will drop 2

### ISSUE THREAD

**Issue by DocWhoSonicDrive** [DaFuqs/Spectrum#30]
**Describe the bug**
Breaking a placed bottomless bundle instead of shift+right clicking it will drop 2 identical bundles, with the same contents. This will duplicate bottomless bundles as well as the items inside.

**To Reproduce**
Place a bundle on the ground and break it. Fists should work, but I used a pickaxe.

**Expected behavior**
It would either drop the single bottomless bundle or be unbreakable. 

**Mod version**
I am using spectrum-1.2.8-1.18.1-midgame9.

**Screenshots**
![Part1DupeBug](https://user-images.githubusercontent.com/57576279/154100740-ba08c7c4-d033-4c54-97e8-c8caf3f788b5.PNG)
![2022-02-15_10 03 35](https://user-images.githubusercontent.com/57576279/154100765-ac19c284-518d-4c01-9732-61f115c08773.png)
![2022-02-15_10 03 46](https://user-images.githubusercontent.com/57576279/154100788-1d90cfb6-d7be-4025-8261-849cee53bfe9.png)
![Part2DupeBug](https://user-images.githubusercontent.com/57576279/154100798-81c4ea9f-007c-47da-8987-367d89f370b1.PNG)

**Comment by DaFuqs** [comment]
This is already fixed for the upcoming release but ty reporting that! I will leave this issue upen until release.
Until then picking up the bundle via right click will do

**Comment by DaFuqs** [comment]
Fixed in Midgame10.
