### ISSUE TITLE
[BUG] EMI does not display the entire number of items in Cinderhearth

### ISSUE THREAD

**Issue by Kisuny** [DaFuqs/Spectrum#300]
**Describe the bug**
When i added 3+ items in Cinderhearth craft, EMI show only 3 items

**Expected behavior**
show all items for craft

**Mod version**
spectrum-1.7.2
emi-1.0.27

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/56004431/93eea585-66ca-4f22-9e1c-a51e1a36dfc5)
![image](https://github.com/DaFuqs/Spectrum/assets/56004431/ff951250-5b57-4acb-8c4b-1492cc70e592)
![image](https://github.com/DaFuqs/Spectrum/assets/56004431/3e20426b-4c5d-488d-8349-b27d54bdc2ab)

Author of EMI [said to contact you](https://github.com/emilyploszaj/emi/issues/373#issuecomment-1855156590)

**Comment by DaFuqs** [comment]
That's sadly a bit of a limitation of display space.
Even if I modified the EMI display in a way it would display 4+ entries, it would break with REI & the guidebook. While EMI does support displays of varying height, both REI and Patchouli do not, as [documented in the wiki for Cinderhearth Recipes](https://github.com/DaFuqs/Spectrum/wiki/Custom-Cinderhearth-Recipes).
