### ISSUE TITLE
enchantments are always valid

### ISSUE THREAD

**Issue by Linguardium** [DaFuqs/Spectrum#303]
https://github.com/DaFuqs/Spectrum/blob/c8393b363ffd08ef6144ce37f853738a74f696ce/src/main/java/de/dafuqs/spectrum/mixin/EnchantmentMixin.java#L15

looks like some broken logic here.

effectively says: if original value == false, return true

**Comment by Noaaan** [comment]
Looking at commit history this change was specifically made to fix https://github.com/DaFuqs/Spectrum/issues/298
Maybe the best solution is to just drop `cir.getReturnValue()`?
