### ISSUE TITLE
[BUG] Nature's Staff forcing nearby players to right click

### ISSUE THREAD

**Issue by ChiefBjorn** [DaFuqs/Spectrum#310]
**Describe the bug**
When using Nature's Staff, nearby players unwillingly use right click.

**To Reproduce**
Use Nature's Staff, while a nearby player(within LOS, and ~40 block radius) is: holding a block/hoe/shovel/seeds/Radiance Staff/Paintbrush, or looking at a chest/levers/buttons/repeaters.

**Expected behavior**
While using Nature's Staff, the players nearby unwillingly: place blocks/seeds, till/flatten land, place lights, re-paint colored blocks(each depending where applicable), or force open chests, actuate redstone components.

**Mod version**
Spectrum 1.7.1 - AOF7

**Comment by DaFuqs** [comment]
Fix by @imreallybadatnames will be included in the next bugfix-release, thank you!
