### ISSUE TITLE
[BUG] Molten rod enchant

### ISSUE THREAD

**Issue by Kisuny** [DaFuqs/Spectrum#311]
**Describe the bug**
in json «spectrum:foundry» but for now foundry named «spectrum:autosmelt»

**Mod version**
spectrum-1.7.3-deeper-down (MC 1.19.2)

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/56004431/a3a1a9f4-e7a3-47df-821f-43a95ba16b1c)
![image](https://github.com/DaFuqs/Spectrum/assets/56004431/7ce07400-3a8e-4547-bcf2-7b0baae33be0)

**Comment by DaFuqs** [comment]
The enchant has been renamed internally to 'foundry' starting with 1.20.1.
I won't update the registry ID for 1.19.2, since all tools enchanted with it would lose the enchant on update, but a good chunk of players would start a new world for 1.20.1 anyways.
