### ISSUE TITLE
Modpack won't initialize after updating spectrum

### ISSUE THREAD

**Issue by Leonxilofin** [DaFuqs/Spectrum#313]
Updated Spectrum and its dependencies and now the modpack fails to initialize at startup. 

Spectrum 1.7.3, Fabric 1.19.2

It's probably just something simple im missing but im not all that great in reading crashlog's

[crash-2023-12-31_20.27.37-client.txt](https://github.com/DaFuqs/Spectrum/files/13802775/crash-2023-12-31_20.27.37-client.txt)

**Comment by Noaaan** [comment]
For some reason you are missing Fractal, the library used by Spectrum for Item Groups. You can get it here: https://modrinth.com/mod/fractal-lib

**Comment by Leonxilofin** [comment]
thanks! Downloading that made me realize I also need to update my mod loader which ill do at a different time.

**Comment by Leonxilofin** [comment]
Closing this as I no longer need it opened and know where to go from here
