### ISSUE TITLE
[BUG] Constantly Spawning Tearstone

### ISSUE THREAD

**Issue by Gamerbolts** [DaFuqs/Spectrum#32]
I am not sure what the issue is. I am testing my modpack and was going through Spectrum and got timed out. I went back in my world and saw "top right corner' my map had a lot of entities. I did the /remove drops command and it cleared 499 drops. They all started to spawn again. I cleared again and they started coming back. Not sure what is happening or if it is another mod in my modpack causing this.

Not sure if you will be able to reproduce as my modpack is not live yet.

I am not sure if these Tearstones are supposed to spawn once or twice in the water. But I would expect just a few.

Mod Version 1.2.8

![image](https://user-images.githubusercontent.com/20451601/155857167-0b7fbf38-e918-423c-b12c-55ced9213d00.png)

No crash report but here is my latest log from the client and server
Client [latest.log](https://github.com/DaFuqs/Spectrum/files/8147399/latest.log)
Server 
[latest.log](https://github.com/DaFuqs/Spectrum/files/8147400/latest.log)

Any help is appreciated. Thank you!

**Comment by Gamerbolts** [comment]
Sorry not sure why my screen capture captured the screen with REI opened lol

![image](https://user-images.githubusercontent.com/20451601/155857236-d21a4353-9f66-4088-9484-f658d113d4b4.png)

**Comment by DaFuqs** [comment]
Tearstones are growing on plants that release them when fully grown. Anything that messes with random ticks, like /gamerule randomTickSpeed?

**Comment by Gamerbolts** [comment]
LOL oops for testing I put that at 4000. My bad. Thanks! :)
