### ISSUE TITLE
[Feature] Ender Flask

### ISSUE THREAD

**Issue by eehunter** [DaFuqs/Spectrum#321]
Idea: An ender variant of the Ink Flask. When first crafted it does nothing. Right-click with it on a block of pigment to set its color. Once color is set, it becomes linked to the player who set its color. All Ender Flasks of the same color linked to the same player will now hold the same amount of ink at a given time, effectively becoming the same flask.

This is a feature that I wish to implement as either a pull request or an addon mod, depending on whether or not you think it would be too powerful as part of the base mod. The intent is so that I can provide a way to automate the Crystallerium in a modpack I'm making.

**Comment by DaFuqs** [comment]
The next big update will add a way to transfer ink to the crystallarieum using networking, a bit like Pastel Network nodes, so it should be really easy to get it automated.
I still kinda like the idea, so I'm leaving this open to think about it 👌

**Comment by eehunter** [comment]
This is one of several ideas I've had for additional features for Spectrum, but some of them I don't think necessarily fit as well with the base mod. As such, I have decided to make an addon called Spectral Utilities which implements this and some of my other ideas. So far, the Ender Flasks are craftable and work. I have not yet made the lang files for them or added guidebook entries. Also there is almost certainly a bug related to loading an existing save, but I have yet to actually test what impact it might have. This should be relatively easy to fix, however.
![Screenshot from 2024-02-17 15-02-48](https://github.com/DaFuqs/Spectrum/assets/35015228/b6d11bc4-23c4-4578-af0e-90835ce2a45a)

**Comment by eehunter** [comment]
I plan to implement the Moonstone Grow Lamp from my other feature suggestion, as well as some new Crystallerium recipes and additional Create integration (upgraded versions of the Mechanical Drill and Mechanical Saw that can break cloaked blocks).

**Comment by DaFuqs** [comment]
Oh wow, dope! Looking goood.
I haven't found the mod on Modrinth/Curseforge or your github yet. @ me when I can try it out, I would love to take a look at it.

**Comment by eehunter** [comment]
I'm gonna upload the code to github right now, and I'll create a Curseforge project that should become visible in the next couple days.

Edit: Github upload is complete, now I'm going to upload to Curseforge.

**Comment by eehunter** [comment]
Actually, it occurs to me that I don't have an icon for this mod. Is it okay if I use a modified version of the Spectrum icon for the project? I know that the lGPL2 license sorta allows it already, but I figured I'd ask to make sure.

Edit: This is the icon I whipped up: 
![icon](https://github.com/DaFuqs/Spectrum/assets/35015228/96099e84-8998-4878-ac37-18738931ff5a)
Edit 2: I actually think it would work better if the Ender Flask was in the middle, sorta like the icon for Spectrum Jetpacks. Is there somewhere I can find the background for the Spectrum logo without the Pigment Pedestal?

**Comment by DaFuqs** [comment]
Absolutely, go ahead

**Comment by DaFuqs** [comment]
You can find all the images and stuff I made in the images folder: https://github.com/DaFuqs/Spectrum/tree/1.20.1-main/images/icons_banners (Gimp files)

**Comment by eehunter** [comment]
Thanks!

**Comment by eehunter** [comment]
I'm making a few small changes and then uploading a jar to Curseforge. I'll probably upload to Modrinth too, later. 

Edit: Those changes being adding a guidebook entry for the Ender Flask and making it so that unlocking the recipe for each type of Ender Flask requires having obtained the respective pigment.

**Comment by eehunter** [comment]
Curseforge upload is complete, awaiting moderator approval.

**Comment by eehunter** [comment]
I keep running into weird things when looking at Spectrum's code inside my dev environment for Spectral Utilities. I wonder to myself why it was written that way, and then realize a moment later that it wasn't; I'm just looking at a decompiled jar instead of the original source code.

For example, from FusionShrineBlock.class:
`    protected void appendProperties(StateManager.Builder<Block, BlockState> builder) {
        builder.add(new Property[]{LIGHT_LEVEL});
    }`

**Comment by DaFuqs** [comment]
This is now implemented in Spectral Utilities!
