### ISSUE TITLE
[Feature] We've translated the guide book for Chienes, witch from the release v1.7.3_MC1.19.2

### ISSUE THREAD

**Issue by BKLRsk** [DaFuqs/Spectrum#327]
We've translated the guide book for Chienes, witch from the release v1.7.3_MC1.19.2.

My friend and I hope to help with translation for the guidebook, but none of us knew how to work on Github. And we're bad at English.

I know that sounds strange but we did have completed this work and I think we did it very well.

So I hope you may merge our work.
[guidebook.tar.gz](https://github.com/DaFuqs/Spectrum/files/14071458/guidebook.tar.gz)

**Comment by DaFuqs** [comment]
This is great, thank you! ❤️ 
I will add it for 1.19.2 and will make some small changes so your translation also works on 1.20.1

**Comment by BKLRsk** [comment]
> This is great, thank you! ❤️ I will add it for 1.19.2 and will make some small changes so your translation also works on 1.20.1

Love to Spectrum!❤️

**Comment by DaFuqs** [comment]
Done!
