### ISSUE TITLE
[BUG] Incompatibility between Spectrum and Epic Fight via Connector

### ISSUE THREAD

**Issue by thedeerirty** [DaFuqs/Spectrum#328]
**Describe the bug**
When loading Spectrum on Forge via Connector alongside Epic Fight, a crash at mod-loading occurs.

**To Reproduce**
Install all that you need to for Spectrum to work using connector on forge, then add Epic Fight Mod and its dependencies.

**Mod version**
Spectrum Deeper Down 1.7.5 (Compiled the Build from Github as its compatible with Connector.)
I also compiled a Pending fork of Revelationary that is compatible with Connector

**Crash Report**
[latest.log](https://github.com/DaFuqs/Spectrum/files/14071673/latest.log)
Log that reports the error. 

I'm not sure if there can be anything done with this, or if you guys are even willing to make mods that were historically not even possible to play together compatible, but I'd figured I'd report the info. If Connector is gonna be something that gains more traction in the future, makes sense to help bridge compatibility anyway I can. I've reported the issue to Epic Fight as well.

**Comment by DaFuqs** [comment]
Certified Incubus Concern Moment

**Comment by thedeerirty** [comment]
Dang I see lol

Not sure what that really entails but ! If it is somehow fixable I wish you luck in doing so.

**Comment by DaFuqs** [comment]
Outcubus Concern

**Comment by thedeerirty** [comment]
If it isn't too much trouble, can I ask about what's causing this error? What the log is referring to with the Incubus Core library?
I imagine this is pretty low on the priority list and could potentially be a while before its looked at, so I was hoping to kinda take a crack at it myself. I'm just not the uh, most versed when it comes to Java

**Comment by DaFuqs** [comment]
Both Incubus Core and Epic Fight mod try do do an invasive change to the same internal code.
Since minecraft has no way to know which of these changes to choose over the other it crashes.

I may be able to add a workaround for that. No promise, though.

**Comment by eehunter** [comment]
This should theoretically be fixed if Yesssssman/epicfightmod#1533 gets merged. I haven't tested it, though.

**Comment by thedeerirty** [comment]
wow that was a lot faster than I was expecting, sick
as soon as it does I'll get on it for some testing

**Comment by eehunter** [comment]
> wow that was a lot faster than I was expecting, sick as soon as it does I'll get on it for some testing

If you build my fork of Epic Fight, you can test it immediately. That would actually be helpful, since I didn't even do cursory testing, so if I've made a critical mistake it would be better for someone to catch it before the actual dev tries to evaluate it.

**Comment by thedeerirty** [comment]
I was actually already doing it! 

It got to the title menu, so massive improvement so far. Let me make sure it doesn't crash on something weird like world creation real quick.

**Comment by thedeerirty** [comment]
Seems to be working just fine with only epic fight, connector and spectrum/dependencies - Bedrock armor animates incorrectly in its combat mode, but that's to be expected and something I can fix myself.

I had an initial crash when creating a world but that was with other stuff installed. 

edit: checked on that crash, seems unrelated, just throwing a formatting error on a datapack it didn't used to throw. assume its something new with the mod itself.

**Comment by DaFuqs** [comment]
Fixed in dev and will be included in the next bugfix release ✅
