### ISSUE TITLE
[BUG] Sinytra Connector startup crash

### ISSUE THREAD

**Issue by ghost** [DaFuqs/Spectrum#329]
**Describe the bug**
When loading Spectrum and its dependencies with Sinytra Connector the game crashes on launch 

**Mod version**
compiled both the latest github versions for spectrum (1.7.5) and revelationary (1.3.6)

**Crash Report**
[latest.log](https://github.com/DaFuqs/Spectrum/files/14072116/latest.log)
https://mclo.gs/5niimxQ

in the prism log it mentions §6cardinal-components-world§r missing as well, right after a bunch of mixin errors

**Comment by DaFuqs** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getActualReachDistance(DLnet/minecraft/world/level/Level;Lnet/minecraft/world/entity/player/Player;)D in mixins.reach-entity-attributes.json:ItemMixin from mod reach_entity_attributes failed injection check, (0/4) succeeded.

The lib Reach Entity Attributes has a mixin issue somehow.
With 1.20.2 that lib will be obsolete, since vanilla will have that functionality, but it would still be nice if it worked with Sinytra on 1.20.1. Best to report it to them.

**Comment by soleilan** [comment]
Running fine for me on 1.20.1, using Connector Extras prevents a startup crash. Without it the crash will happen though.

**Comment by DaFuqs** [comment]
Sounds like adding Connector Extras does the trick
