### ISSUE TITLE
[Feature] Consider Naming Convention

### ISSUE THREAD

**Issue by xanthian** [DaFuqs/Spectrum#33]
I know this can't be done now as it will break worlds.
But please consider this for 1.19 (as most will restart)

![image](https://user-images.githubusercontent.com/7688001/155877076-e8f992d9-e052-44af-83ac-c0013cdb4048.png)
![image](https://user-images.githubusercontent.com/7688001/155877120-aeb74840-9542-4d82-89ad-5384485d3403.png)
etc...

This does not follow vanilla naming convention, making it somewhat awkward making recipe generation / mod compatibility.

![image](https://user-images.githubusercontent.com/7688001/155877109-01d83cf3-15da-4d4f-abe3-5cc3d484f27d.png)

**Comment by DaFuqs** [comment]
oh yeah, that makes sense. Will do on the next mayor version update

**Comment by xanthian** [comment]
/cry 1.5.0 released and these are the same :(

**Comment by sudo-CuriousLad** [comment]
I'll fixed and push the changes real quick

**Comment by sudo-CuriousLad** [comment]
Should take about 5-10 mins

**Comment by DaFuqs** [comment]
You have not been forgotten. :)

I do not want to break existing worlds, but since 1.5 is now out, I will work on the MC1.19 port.
That one will have the naming convention change, since lots of players will start a new world either way.

**Comment by sudo-CuriousLad** [comment]
> You have not been forgotten. :)
> 
> I do not want to break existing worlds, but since 1.5 is now out, I will work on the MC1.19 port. That one will have the naming convention change, since lots of players will start a new world either way.

Yes but: I already made a PR

**Comment by DaFuqs** [comment]
PR it into the 1.19 dev branch I will create tomorrow :^)

**Comment by xanthian** [comment]
Thought 1.5.0 was 1.19> sorry if I jumped the gun 😁

**Comment by DaFuqs** [comment]
Done for 1.19.
If I forgot anything do not hestitate to open this issue again. We should have catched everything 😊
