### ISSUE TITLE
[BUG] Title

### ISSUE THREAD

**Issue by Tenchu98** [DaFuqs/Spectrum#34]
**Describe the bug**
I am trying to make a recipe for the pedestal, but all I get is water spouting up.

**To Reproduce**
Us the following crafttweaker script.
https://pastebin.com/QC0zZAhG

**Expected behavior**
I was expecting the recipe to take water, poppy, dandelion, and bonemeal then give me botania fertilizer.

**Mod version**
1.2.8

**Comment by Tenchu98** [comment]
I incorrectly stated pedestal when I meant shrine, sorry for the confusion.

**Comment by Tenchu98** [comment]
I meant shrine, not pedestal sorry.

**Comment by DaFuqs** [comment]
No prob. :)
Honestly, I have never worked with KubeJS before. As long as the final recipe.json matches the requirement you should be fine, though. You can find the description here: https://github.com/DaFuqs/Spectrum/wiki/Custom-Fusion-Shrine-Recipes

By looking at your script it seems at least the properties "world_conditions" and "start_crafting_effect" are not specified?

**Comment by Tenchu98** [comment]
I didn't specify them since it said they were optional, but I could add them. I am using crafttweaker, but could probably just make a datapack instead.Sent from my Galaxy
-------- Original message --------From: DaFuqs ***@***.***> Date: 3/8/22  2:59 PM  (GMT-05:00) To: DaFuqs/Spectrum ***@***.***> Cc: Tenchu98 ***@***.***>, Author ***@***.***> Subject: Re: [DaFuqs/Spectrum] [BUG] Title (Issue #34) 
No prob. :)
Honestly, I have never worked with KubeJS before. As long as the final recipe.json matches the requirement you should be fine, though. You can find the description here: https://github.com/DaFuqs/Spectrum/wiki/Custom-Fusion-Shrine-Recipes
By looking at your script it seems at least the properties "world_conditions" and "start_crafting_effect" are not specified?

**Comment by DaFuqs** [comment]
If you can get me the final json how KubeJS would use it I can take a closer look at it tomorrow. :)

**Comment by Tenchu98** [comment]
I posted the one I had for crafttweaker, not sure if kubejs would be different. I also tried changing your golden apple one and removing the advancement requirement, but the recipe still just sits there spewing water particles. Into the air. Do you have an example of how to do one with no advancement required, and is there some strong besides putting the items into the shrine to start the ritual?

**Comment by Tenchu98** [comment]
This is the datapack file I am trying to use, and it says it loads fine, but I get the same hovering items with water particles and nothing else.

{
  "type": "spectrum:fusion_shrine",
  "time": 200,
  "experience": 4.0,
  "fluid": "minecraft:water",
  "ingredients": [
    {
      "item": "minecraft:poppy"
    },
    {
      "item": "minecraft:dandelion"
    },
    {
      "item": "minecraft:bone_meal"
    }
  ],
  "result" : {
    "item": "botania:fertilizer"
  },
  "required_advancement": "nothing",
  "world_conditions": [ "day", "clear_sky" ],
  "start_crafting_effect": "single_visual_explosion_on_shrine",
  "during_crafting_effects": ["visual_explosions_on_shrine", "nothing", "visual_explosions_on_shrine"],
  "finish_crafting_effect": "lightning_on_shrine"
}

**Comment by Tenchu98** [comment]
ok so it was the advancement that was messing it up, is there a way to not require an advancement for a recipe?

**Comment by DaFuqs** [comment]
Oh yeah, I see!
I was making the `"required_advancement"` tag optional in the newest version and already updated the wiki. But because I am still waiting for a few textures the wiki content and actual requirement in the currently released version do not add up. Sorry about all that trouble!

Best to use "spectrum:collect_all_basic_pigments_besides_brown" as the required_advancement. That is the advancement required to craft the fusion shrine itself. This way the player will get a handy popup that the Botania Fertilizer can now be crafted in the Fusion Shrine that they are now able to build, automatically.

**Comment by Tenchu98** [comment]
Thank you that is understandable. Once a skyblock mod is out for 1.18 I am thinking of making a pack based off spectrum.
