### ISSUE TITLE
[Feature] Potion Workshop sidedness

### ISSUE THREAD

**Issue by Aeonsteel** [DaFuqs/Spectrum#344]
I feel that when hoppering Mermaid's Gems into the side of a Potion Workshop they should go into the fuel slot and no other slots. This could make automatic refilling of the slot possible, saving time when brewing large amounts of items (like Liquid Crystal, or Bottles O Enchanting.)

**Comment by DaFuqs** [comment]
Done.
Top: Mermaid's Gems, Ingredients (Gems will always be put into the 
Sides: Reagents
Bottom: output inventory
