### ISSUE TITLE
[BUG] Bottomless Bundle removes NBT tags

### ISSUE THREAD

**Issue by Jazoe** [DaFuqs/Spectrum#35]
**Describe the bug**
If you put an item inside a Bottomless Bundle then right click with it in your hand, the item will come out of the Bottomless Bundle without any NBT tags.

**To Reproduce**
Put an item with any NBT tag into a Bottomless Bundle, like an enchanted item. Then, be outside your inventory and right click with the Bottomless Bundle in your hand. The item that is thrown out of the bundle will be the same item that was put in, however it will no longer have any NBT tags.

**Expected behavior**
When removing the item from the bundle outside your inventory, the item should keep its NBT tags.

**Mod version**
spectrum-1.2.8-1.18.1-midgame9

**Screenshots**
![image](https://user-images.githubusercontent.com/40479210/158097746-c89fe353-e302-4856-948a-4e350f13ecd1.png)
![image](https://user-images.githubusercontent.com/40479210/158097782-505b0f7c-379a-4636-bff1-975b7ca6aa79.png)
![image](https://user-images.githubusercontent.com/40479210/158097800-07116a97-ceb7-4a6b-95ba-c71ebde49093.png)
![image](https://user-images.githubusercontent.com/40479210/158097822-b45b61ed-77ae-4cca-9942-3fa1dd1d4f58.png)
![image](https://user-images.githubusercontent.com/40479210/158097853-cc4a5590-75a7-45d7-afdb-d4b465fc5cec.png)

**Comment by DaFuqs** [comment]
Fixed in Midgame10.
