### ISSUE TITLE
[BUG](ish) chiseled moonstone's texture layout is asymetrical. architect is pain.

### ISSUE THREAD

**Issue by yoopgim** [DaFuqs/Spectrum#350]
![artinpain](https://github.com/DaFuqs/Spectrum/assets/51343338/4b239986-734c-4f3b-9086-7db0483ec581)

version: 1.7.6-deeper-down

**Comment by Robotgiggle** [comment]
On a similar note, it's somewhat annoying that the shading on the chiseled moonstone block rotates along with the block, given that you probably want to have them on the ground with the line flowing in all four directions. Not sure how that could actually be fixed, though.

**Comment by eehunter** [comment]
The shading thing could be fixed by mirroring the texture when in opposing orientations. It would still require two different textures, I think, one for x-aligned and one for z-aligned blocks.

**Comment by DaFuqs** [comment]
Oh no. Yeah, that should get improved.
Having a second texture for the opposing orientations will be easy enough

**Comment by Azzyypaaras** [comment]
You will all suffer until the great resprite is done.
![image](https://github.com/DaFuqs/Spectrum/assets/20349662/be17a994-b738-4a29-be90-d6ddfde2de6e)

**Comment by DaFuqs** [comment]
![image](https://github.com/user-attachments/assets/43b9edfd-e533-4df3-957c-d334f4e819f3)
