### ISSUE TITLE
[BUG] X-ray Gemstone Lamps

### ISSUE THREAD

**Issue by ChiefBjorn** [DaFuqs/Spectrum#352]
**Describe the bug**
All gemstone lamp variants are see through

**Expected behavior**
Gemstone lamps act like Universe Spyhole should

**Mod version**
Spectrum 1.7.6
AOF 7 - 1.20.1
![2024-02-15_22 46 18](https://github.com/DaFuqs/Spectrum/assets/66485552/48bb9c42-c035-431f-9ba6-270520e8d508)

**Comment by DaFuqs** [comment]
Caused by Sodium breaking rendering on translucent stuff.

Try without Sodium or try out their recent nightly, they improved transparency handling by a lot: https://nightly.link/CaffeineMC/sodium-fabric/workflows/build-commit/dev/sodium-artifacts-dev.zip

**Comment by ChiefBjorn** [comment]
Removing Sodium fixes the issue, thanks!

**Comment by DaFuqs** [comment]
Np!

Keeping this open until Sodium 0.6.0 is available for MC 1.20.1

**Comment by eehunter** [comment]
I know this is an issue with Sodium, but wouldn't it be possible to fix it by setting isFullCube() to false or something? Probably not an ideal solution, but I doubt it would impact performance much and it would probably fix the issue.

**Comment by DaFuqs** [comment]
I've added that in dev (or the most recent release). The lamps rendering is still broken, but at least you can't see through them anymore
