### ISSUE TITLE
[Feature] Crystal Apothecary compatibility with Mythic Upgrades & Geode+ budding crystals

### ISSUE THREAD

**Issue by Mieridduryn** [DaFuqs/Spectrum#361]
Hi! I've got a neato little crystal farm going in the modpack I've been playing. The Crystal Apothecaries are ensuring that I don't have to manually mine up my Spectrum and AE2 crystals.

However, I have several budding crystals from the [Mythic Upgrades](https://www.curseforge.com/minecraft/mc-mods/mythic-upgrades) & [Geode+](https://www.curseforge.com/minecraft/mc-mods/geode-plus) mods around the same Crystal Apothecaries. They do not get automatically harvested by the Apothecaries. My current solution is a couple of black hole chests and FTB Ultimine.

Would it be possible to implement compatibility for the budding crystals from these two mods? I'm a bit worried that allowing automation of the Geode+ crystals would make growing certain pure resource clusters less appealing to the player. (Geode+ offers budding diamonds, lapis, redstone, echo, ancient debris, gold, glowstone, etc.)

**Comment by DaFuqs** [comment]
I can add that, absolutely!

**Comment by Mieridduryn** [comment]
Would it be possible to make Resonance compatible with Mythic Upgrades buds as well? It's compatible with Geode+ in the modpack I'm playing (unsure if this is Spectrum or the pack itself), but not MU.

Er... if it's a Spectrum thing for Geode+, could you please extend it to MU? Haha.

**Comment by DaFuqs** [comment]
Absolutely. I will just have to add a few block tags

**Comment by Mieridduryn** [comment]
Oh, shoot, sorry to ask for another thing on this issue, but Biome Makeover's Illunite is also incompatible with Resonance, would you mind looking into that?

**Comment by Mieridduryn** [comment]
Also also, this just came to mind - could Geode+ crystals mined with Resonance (the gold, diamond, lapis, redstone, netherite crystals, not the budding blocks) be made to drop their respective Pure mineral, much like how mining their ore with Resonance would? I understand if this is a bit too OP. There is Spectrum's crystallarium, after all!

**Comment by DaFuqs** [comment]
Oooh, looks like Geode+ changed their mod id from "geode" to "geode_plus", so all the integrations I added in the past did not work anymore.

**Comment by DaFuqs** [comment]
Done!

I did not add any pure resource interactions yet, cause having each resource farmable so easy would make them quite easy to get, like you described. But I could very well see that in the future. Also since those drops can be added via data pack by modpack makers, they are free to add them for specific packs anyways.
