### ISSUE TITLE
[BUG] 1.19.2 Deep down crashes whole server + 1.7.6 version causes issue

### ISSUE THREAD

**Issue by Deaugh83** [DaFuqs/Spectrum#362]
**Describe the bug**
2 problems : The deep down has a flower that cause a big explosion, that killed me and created a grave. Then when i tried to reach it to collect my stuff the server i am on crashes. We tried to update to the 1.7.6 version of the 1.19.2 minecraft but now we also have a problem 

**To Reproduce**
1.7.6 version on a 1.19.2 server

**Expected behavior**
Not crash

**Minecraft version**
1.19.2

**Mod version**
1.7.3 : deep down crashes after death by explosion
1.7.6 : crash when rendering azuredike

**Screenshots**

**Crash Report**
1.7.3 : 
[2024-02-29-3.log](https://github.com/DaFuqs/Spectrum/files/14453930/2024-02-29-3.log)

1.7.6 error : The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void de.dafuqs.spectrum.render.HudRenderers.renderAzureDike(net.minecraft.class_4587, int, int, net.minecraft.class_1657)'

**Comment by DaFuqs** [comment]
If you still have it, can you post the full error from the 1.7.6 Azure Dike renderer, please?
