### ISSUE TITLE
[BUG] "What Happened Below" only unlocks after finding all 7 DD biomes

### ISSUE THREAD

**Issue by Robotgiggle** [DaFuqs/Spectrum#363]
**Describe the bug**
The "What Happened Below" page in the guidebook, which contains a checklist of things to investigate in the Deeper Down, is currently unlocked by visiting all 7 biomes in the Deeper Down. Due to the way biomes generate, it's possible (and quite likely, in fact) to never find one or more of the required biomes until you're practically done with all the progression. This means that in most cases, you'll only unlock the checklist page once it's nearly (or even entirely) filled out.

`noaaan` on the Discord has confirmed that it's intended for this page to be made available "fairly quickly" after entering the Deeper Down, which at the moment it definitely is not.

**To Reproduce**
Obtain the Biomes Below Bedrock advancement and see that it unlocks the What Happened Below page.

**Expected behavior**
The wording of each checklist item really feels like they're intended to be hints on what to look for as soon as you enter the DD (ie "Was the place below Bedrock inhabited" and "Can you find Geodes here, too?"), so only getting access to them by the time you're nearly finished feels very odd. In my first run, it felt like I'd somehow missed a hint/tutorial page that I was supposed to have had this whole time.

Some potential unlock conditions that make a little more sense to me:
- as soon as you enter the Deeper Down
- as soon as you find one biome that isn't Deep Barrens
- as soon as you obtain one of the checklist items (which will likely be the 'collect moonstone' one)

**Minecraft version**
Minecraft 1.20.1

**Mod version**
Spectrum 1.7.7

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/88736742/14007743-8636-4e6f-bca3-b56aee531b49)

**Comment by DaFuqs** [comment]
Implemented in 145961fe1d289c04706ac197af938cf870aa9d65
