### ISSUE TITLE
[BUG] Enchantment Upgrade Recipes does not work properly

### ISSUE THREAD

**Issue by Kisuny** [DaFuqs/Spectrum#364]
**Describe the bug**
In the process of adding new ench. update crafting, I found that enchantment improvements only work for the last item in the list of levels, thus, it is possible to make enchantments of only the last level, REI also shows the recipe of only the last level.

It works the same way for vanilla enchantments and new spectrum enchantments.

**Minecraft version**
1.19.2. fabric

**Mod version**
spectrum-1.7.6-deeper-down

**Screenshots**
This example shows the recipe for only the last enchantment level, but two levels have been added, according to the [documentation](https://github.com/DaFuqs/Spectrum/wiki/Custom-Enchantment-Upgrade-Recipes#enchantments)!
![image](https://github.com/DaFuqs/Spectrum/assets/56004431/b2e97961-c7ac-4e68-aded-345be83f0444)
![image](https://github.com/DaFuqs/Spectrum/assets/56004431/529ddbd3-9027-46b3-a0d3-00342f93341e)

**Comment by DaFuqs** [comment]
Could you try it out without mods that override the default recipe viewer, or support adding/removing recipes via scripting languages, like KubeJS

**Comment by Kisuny** [comment]
> Could you try it out without mods that override the default recipe viewer, or support adding/removing recipes via scripting languages, like KubeJS

Without kubejs, everything works as it should.

Do I need to write to the kubejs authors? 

If the problem is with kubejs, why is the problem only with crafting this type? I have not encountered the problem of custom recipes yet.
All crafting of this type breaks down in the same way, it's strange.

**Comment by Kisuny** [comment]
I'm sorry, I'm an idiot.

Somehow we had 2 versions of kubejs in our modpack, deleting the second one made everything work.

**Comment by DaFuqs** [comment]
Huh, I did not even know that was possible. Interesting.
Glad it worked out!

**Comment by Kisuny** [comment]
> Huh, I did not even know that was possible. Interesting. Glad it worked out!

In fact, the problem appears after a /reload
As soon as you rejoin into the world, crafts reappear

**Comment by DaFuqs** [comment]
In that case it very much sounds like https://github.com/KubeJS-Mods/KubeJS/issues/293

**Comment by Kisuny** [comment]
> In that case it very much sounds like [KubeJS-Mods/KubeJS#293](https://github.com/KubeJS-Mods/KubeJS/issues/293)

We noticed the same problem in the NeepMeat mod - https://github.com/MeatWheeze/NeepMeat/issues/5
The author rewrote his crafts to vanilla recipe manager
