### ISSUE TITLE
[BUG] Game crashes when attempting to craft Fresh Chocolate

### ISSUE THREAD

**Issue by craft90** [DaFuqs/Spectrum#365]
**Describe the bug**
I tried to make Fresh Chocolate in the Titration Barrel. I added the ingredients as indicated by the guide book (4 cocoa beans, 1 clotted cream and 2 sweet berries). However when I tried to seal the barrel with a colored plank, the game crashes with the error being Invalid Fluid ingredient. There's no fluid in the recipe. When I tried to add a fluid (water) I got the error that it won't make anything drinkable. Am I missing something or is the recipe bugged?

**To Reproduce**
Add 4 cocoa beans to Titration Barrel.
Add 1 clotted cream to Titration Barrel
Add 2 sweet berries to Titration Barrel.
Attempt to seal with an orange colored plank.
Game crashes.

**Expected behavior**
I would have expected the barrel to seal up and start fermenting.

**Minecraft version**
1.20.1

**Mod version**
1.7.6 - Deeper Down

**Crash Report**
If it is a crash bug add your crash log here
[crash-2024-03-06_17.10.13-server.txt](https://github.com/DaFuqs/Spectrum/files/14512701/crash-2024-03-06_17.10.13-server.txt)

**Comment by DaFuqs** [comment]
Upgrading to Spectrum 1.7.7 should fix that

**Comment by craft90** [comment]
Does 1.7.7 support Quilt? Because that's the modloader I'm using.

Edit. It seems to work so far. No crash on load or error message. The recipe also works.

**Comment by DaFuqs** [comment]
> 1.7.7 support Quilt

Absolutely! I try to have compat with Fabric, Quilt and Forge (via Connector) where ever possible.
