### ISSUE TITLE
[BUG] mod incompat 

### ISSUE THREAD

**Issue by chakkenmoo** [DaFuqs/Spectrum#368]
**Describe the bug**
With "Infinity cave" mod installed, the portal to the "Deeper Down" dimension will not be created.

**To Reproduce**
Install both the "Infinity cave" and the "spectrum" mod, and break the bedrock layer in the overworld to make a portal

**Expected behavior**
portal be created when you break the last bedrock layer

**Minecraft version**
1.20.1

**Mod version**
1.7.7

**Comment by DaFuqs** [comment]
Infinity Cave: https://github.com/Frozeh/infinity-cave

**Comment by DaFuqs** [comment]
Seems to work nicely for me using just Spectrum and https://modrinth.com/datapack/infinity-cave/version/9JfHAyhU, converting Bedrock with Ruin at y=-128 and then breaking it.
Maybe an other mod is interfering?

**Comment by chakkenmoo** [comment]
Maybe so... Anyway I deleted the Infinity cave mod (because there is no problem without the mod)
Let me know if you need any other information

---------------------------------------------------------
Loading 289 mods:
	- amecs 1.3.10+mc.1.20.1
	   \-- amecsapi 1.4.0+mc1.20-pre1
	- archers 1.0.7+1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- architectury 9.2.14
	- armorstatues 8.0.5
	   \-- puzzlesapi 8.1.4
	        |-- cardinal-components-base 5.2.2
	        |-- cardinal-components-entity 5.2.2
	        \-- puzzlesaccessapi 8.0.7
	- armourers_workshop 2.1.0
	   |-- com_electronwill_night-config_core 3.6.5
	   \-- com_electronwill_night-config_toml 3.6.5
	- artifacts 9.3.0
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- expandability 9.0.0
	   |-- porting_lib_attributes 2.1.1093+1.20
	   |    |-- porting_lib_core 2.1.1093+1.20
	   |    \-- porting_lib_gametest 2.1.1093+1.20
	   \-- step-height-entity-attribute 1.2.0
	- autofish 0.9.10-SNAPSHOT
	- azurelibarmor 2.0.3
	- balm-fabric 7.2.2
	- betteradvancements 0.3.2.162
	- bettercombat 1.8.4+1.20.1
	- betterf3 7.0.2
	- betterthirdperson 1.9.0
	- bettertridentreturn 1.20.1-1.0.2
	- bobby 5.0.1
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- bookshelf 20.1.9
	- bowinfinityfix 2.6.0
	- camerautils 1.20.1-1.0.5
	- carryon 2.1.2.7
	- chesttracker 1.1.22
	   |-- libgui 8.0.0+1.20
	   |    |-- jankson 5.0.1+j1.2.2
	   |    \-- libninepatch 1.2.0
	   \-- whereisit 1.14.17
	- chunkloaders 1.2.8+a
	- citresewn 1.1.3+1.20
	   \-- citresewn-defaults 1.1.3+1.20
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- collective 7.39
	- combatroll 1.3.1+1.20.1
	- comforts 6.3.5+1.20.1
	   \-- spectrelib 0.13.15+1.20.1
	- conjuring 1.0.29+1.20
	   \-- lavender 0.1.0-pre.18+1.20
	        |-- lavender-md 0.1.0-pre.3+1.20
	        \-- lavender-md-owo-ui 0.1.0-pre.3+1.20
	- continuity 3.0.0-beta.4+1.20.1
	- copperhopper 0.5.1+1.20.1
	- cpm 0.6.15a
	- crawl 0.12.0
	   \-- mm 2.3
	- ctov 3.4.2
	- cupboard 1.20.1-2.6
	- diagonalfences 8.1.3
	   \-- diagonalblocks 8.0.2
	- durability101 0.0.4
	- easyanvils 8.0.2
	- eco 2.4.4
	- emotecraft 2.2.7-b.build.50
	   \-- bendy-lib 4.0.0
	- enchdesc 17.0.14
	- entity_model_features 1.3
	- entity_texture_features 5.2.3
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.2-mc1.20.1
	- equipmentcompare 1.3.8
	- fabric-api 0.92.0+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.4+1802ada577
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- fastasyncworldsave 1.20.1-1.4
	- ferritecore 6.0.1
	- fog-looks-good-now 2.2.0+1.20.1
	   \-- yet_another_config_lib_v3 3.2.1+1.20
	        |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	        |-- org_quiltmc_parsers_gson 0.2.1
	        \-- org_quiltmc_parsers_json 0.2.1
	- followersteleporttoo 2.4
	- forgeconfigapiport 8.0.0
	- forgivingvoid 10.0.0
	- galosphere 1.20.1-1.4.1
	- gazebo 1.1.1+1.20.1
	- gpumemleakfix 1.20.1-1.8
	- grindenchantments 3.1.2+1.20
	   \-- codec-config-api 1.0.2+1.19.3
	- icarus 1.16
	- iceberg 1.1.18
	- improved-signs 1.3.1
	   \-- omega-config 1.2.3-1.18.1
	- indium 1.0.27+mc1.20.1
	- indypets 1.3.3
	- infinity-cave 0.4
	- interactic 0.2.0+1.20
	- inventoryprofilesnext 1.10.9
	- iris 1.6.11
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- jewelry 1.2.3+1.20.1
	- koreanpatch 1.3.1-1.20.1
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- lazydfu 0.1.3
	- libipn 4.0.1
	- lithium 0.11.2
	- lithostitched 1.1.5
	- majruszlibrary 7.0.5
	- majruszsaccessories 1.5.2
	- merenc 3.2
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- mob-fight-utils 1.0.0+mc.1.20.1
	- modmenu 7.2.2
	- morebannerfeatures 1.2.0
	- mru 0.4.0+1.20
	- nets 0.3.5.5
	- nimble 5.0.1
	- notenoughanimations 1.7.1
	- owo 0.11.2+1.20
	   \-- blue_endless_jankson 1.2.2
	- paladins 1.0.5+1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- peek 1.20.1-1.3.1
	- pehkui 3.7.12+1.14.4-1.20.4
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- persistentinventorysearch 1.4
	- petnames 3.3
	- pickupnotifier 8.0.0
	- player-animator 1.0.2-rc1+1.20
	- polymorph 0.49.1+1.20.1
	   |-- cardinal-components-block 5.2.1
	   \-- cardinal-components-item 5.2.1
	- projectile_damage 3.2.2+1.20.1
	- puzzleslib 8.1.17
	   \-- puzzlesaccessapi 8.0.7
	- quickshulker 1.4.0-1.20
	   |-- kyrptconfig 1.5.4-1.20
	   \-- shulkerutils 1.0.4-1.19
	- radiantgear 2.1.0+1.20.1
	- reeses-sodium-options 1.6.5+mc1.20.1-build.95
	- reinfbarrel 2.4.1+1.20
	   \-- reinfcore 3.1.2+1.20
	- reinfchest 2.4.2+1.20
	   \-- reinfcore 3.1.2+1.20
	- reinfshulker 2.5.0+1.20
	   \-- reinfcore 3.1.2+1.20
	- resourcify 1.3.1
	   \-- universalcraft 323
	- revelationary 1.3.7+1.20.1
	- roughlyenoughitems 12.0.684
	   \-- error_notifier 1.0.9
	- roughlyenoughprofessions 2.0.2
	- roughlyenoughresources 2.9.0
	- runes 0.9.11+1.20.1
	- serversleep_mr 1-datapack
	- shifty-hotbar 1.1
	- shulkerboxtooltip 4.0.4+1.20.1
	- simplebackup 2.0-1.20
	   |-- com_github_spoorn_tar-lz4-java 1.0.3
	   |-- net_lingala_zip4j_zip4j 2.11.5
	   \-- omega-config 1.2.3-1.18.1
	- simpleshulkerpreview 2.4.0
	- simplyswords 1.54.0-1.20.1
	   \-- spruceui 5.0.0+1.20
	- smoothchunk 1.20.1-3.6
	- sodium 0.5.3
	- spectrum 1.7.7
	   |-- additionalentityattributes 1.4.0+1.20.0
	   |-- arrowhead 1.2.0-1.19.4
	   |-- cardinal-components-item 5.2.1
	   |-- cardinal-components-level 5.2.1
	   |-- fractal 1.1.0
	   |-- matchbooks 0.1.0
	   |-- org_jgrapht_jgrapht-core 1.5.1
	   |-- org_jheaps_jheaps 0.13
	   |-- reach-entity-attributes 2.4.0
	   \-- reverb 1.0.0
	- spell_engine 0.12.5+1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- spell_power 0.9.19+1.20.1
	- structure_pool_api 1.0+1.20.1
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.17
	- taxfreelevels 1.3.9
	- tectonic 2.2
	- things 0.3.3+1.20
	   \-- lavender 0.1.0-pre.18+1.20
	        |-- lavender-md 0.1.0-pre.3+1.20
	        \-- lavender-md-owo-ui 0.1.0-pre.3+1.20
	- togenc 1.0
	- toms_storage 1.6.5
	- trashslot 15.1.0
	- trinkets 3.7.2
	- universal-graves 3.0.1+1.20.1
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- placeholder-api 2.1.3+1.20.1
	   |-- polymer-core 0.5.19+1.20.1
	   |    |-- polymer-networking 0.5.19+1.20.1
	   |    |    \-- polymer-common 0.5.19+1.20.1
	   |    |         \-- packet_tweaker 0.4.0+1.19.4
	   |    \-- polymer-registry-sync-manipulator 0.5.19+1.20.1
	   |-- polymer-resource-pack 0.5.19+1.20.1
	   |    \-- polymer-common 0.5.19+1.20.1
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   |-- polymer-virtual-entity 0.5.19+1.20.1
	   |    \-- polymer-common 0.5.19+1.20.1
	   |         \-- packet_tweaker 0.4.0+1.19.4
	   |-- predicate-api 0.2.1+1.20.1
	   |-- server_translations_api 2.0.0+1.20
	   |    \-- packet_tweaker 0.4.0+1.19.4
	   \-- sgui 1.2.2+1.20
	- vanityslots 1.2.9
	- villagernames 7.3
	- villagersrespawn 7
	- way2wayfabric 0.0.6
	- waystones 14.1.3
	- wizards 1.0.5+1.20.1
	   \-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	- wmitaf 3.2.0
	- wso16 1.2
	- xaerominimap 23.9.7
	- xaeros-map-chest-tracker-integration 1.0.2
	   \-- conditional-mixin 0.4.0
	- xaeroworldmap 1.37.8
	- yeetusexperimentus 2.3.1-build.6+mc1.20.1

**Comment by DaFuqs** [comment]
If you can, try to figure out the minimun combination of mods that cause this.
I will not be at my PC for quite some time.
