### ISSUE TITLE
[BUG] - Unsupported root entry "credits"

### ISSUE THREAD

**Issue by pioheh** [DaFuqs/Spectrum#369]
**Describe the bug**
Im getting - Unsupported root entry "credits" prompt when i try to start a server with this mod

**To Reproduce**
Add this mod to BigChadGuys+ NC on 1.20.1

**Expected behavior**
I expected it to just work normally

**Minecraft version**
1.20.1
**Mod version**
1.7.7

**Screenshots**

**Crash Report**
- Unsupported root entry "credits" at line 10 column 14

**Comment by DaFuqs** [comment]
Can you add a full crash log as attachment, please?
