### ISSUE TITLE
[BUG] Spectrum does not work with the latest versions of Patchouli

### ISSUE THREAD

**Issue by KianKhadempour** [DaFuqs/Spectrum#37]
**Describe the bug**
The latest version of Spectrum (1.2.9-1.18.1-midgame10-trinkets-brewing), does not work with the latest 1.18.1 version of Patchouli (Patchouli-1.18.1-65). It also does not work with version 64, 63, or 62.1. It does work with version 61. The problem is (I think) that it does not recognize that version of Patchouli.
**To Reproduce**
Install Spectrum, Patchouli, Trinkets, Fabric API, and owo-lib. In this case, I also have World Edit, Pehkui, and WorldEdit installed. Try to open the game, and an error message will occur.

**Expected behavior**
The game should load as normal with no error message.

**Mod version**
1.2.9-1.18.1-midgame10-trinkets-brewing

**Comment by DaFuqs** [comment]
Can you please attach the log? I am running Spectrum midgame10 together with Patchouli 1.17.1-56-FABRIC just fine

**Comment by KianKhadempour** [comment]
MultiMC version: 0.6.14-3001


Launched instance in online mode

authserver.mojang.com resolves to:
    [65.8.60.72]

session.minecraft.net resolves to:
    [3.211.39.224, 3.224.239.34, 52.205.99.166]

textures.minecraft.net resolves to:
    [65.8.66.82, 65.8.66.59, 65.8.66.48, 65.8.66.34]

api.mojang.com resolves to:
    [65.8.58.195]


Minecraft folder is:
C:/Users/User/Documents/My Games/MultiMC/instances/Spectrum/.minecraft


Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe


Checking Java version...
Java is version 17, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/User/Documents/My Games/MultiMC/instances/Spectrum/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/net/fabricmc/intermediary/1.18.1/intermediary-1.18.1.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/mojang/minecraft/1.18.1/minecraft-1.18.1-client.jar

Native libraries:
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/User/Documents/My Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] cloth-config-6.2.57-fabric
  [✔️] fabric-api-0.46.6+1.18
  [✔️] owo-lib-0.5.2+1.18
  [✔️] Patchouli-1.18.1-65
  [✔️] spectrum-1.2.9-1.18.1-midgame10-trinkets-brewing
  [✔️] trinkets-3.2.0

Params:
  --username  --version MultiMC5 --gameDir C:/Users/User/Documents/My Games/MultiMC/instances/Spectrum/.minecraft --assetsDir C:/Users/User/Documents/My Games/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx8912m, -Duser.language=en]


Minecraft process ID: 14216


Using onesix launcher.

[09:45:26] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
[09:45:26] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
[09:45:26] [main/WARN]: Mod resolution failed
[09:45:26] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE spectrum 1.2.9-1.18.1-midgame10-trinkets-brewing {depends patchouli @ [*]}, ROOT_FORCELOAD_SINGLE spectrum 1.2.9-1.18.1-midgame10-trinkets-brewing]
[09:45:26] [main/INFO]: Reason: [HARD_DEP spectrum 1.2.9-1.18.1-midgame10-trinkets-brewing {depends patchouli @ [*]}]
[09:45:26] [main/INFO]: Fix: add [add:patchouli 1 ([(-?,?)])], remove [], replace []
[09:45:26] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install patchouli, any version.
Unmet dependency listing:
	 - Mod 'Spectrum' (spectrum) 1.2.9-1.18.1-midgame10-trinkets-brewing requires any version of patchouli, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1.
Clipboard copy at: 20 Mar 2022 09:45:33 -0700

**Comment by KianKhadempour** [comment]
> Patchouli 1.17.1-56-FABRIC

Are you supposed to use the 1.17.1 version? Shouldn't it be 1.18.1?

**Comment by DaFuqs** [comment]
Oh yeah, I mistyped, sorry. I meant Patchouli 1.18.1-56-FABRIC, correct

**Comment by DaFuqs** [comment]
Hmmm. Could not reproduce, sadly. And works fine in other packs, like AoF, or Benchmark II. Maybe take a look at those?
