### ISSUE TITLE
[Feature] Compatibility and Integration with Dye Depot

### ISSUE THREAD

**Issue by SharkboiOwen** [DaFuqs/Spectrum#370]
Just a simple request, compatibility and integration with Dye Depot.

**Comment by Gronglegrowth** [comment]
Given each color in Spectrum has specific meaning and symbolism, that's not a simple request, I'd think,,,

**Comment by noukherne** [comment]
> Given each color in Spectrum has specific meaning and symbolism, that's not a simple request, I'd think,,,

I guess they are talking about the fact that Dye Depot currently crashes with spectrum installed (at least with sinytra, the only one I have tried), not specifically about having some special integration

**Comment by Gronglegrowth** [comment]
They did say "compatibility **and integration**".

**Comment by DaFuqs** [comment]
I will look into the crashes. ✅ 

As Grongle has mentioned, adding another 16 colors to Spectrum is not feasible, sadly. Color references are everywhere, this would need a moderately sized addon mod to integrate properly.

**Comment by SharkboiOwen** [comment]
Yeah, I should've made this just Compatability with Dye Depot as when I attempt to use it with Spectrum, it crashes.
