### ISSUE TITLE
[BUG] Advancements for collecting and revealing Amaranth Grains have different conditions

### ISSUE THREAD

**Issue by Robotgiggle** [DaFuqs/Spectrum#373]
**Describe the bug**
The advancement `spectrum:collect_amaranth` is used to unlock recipes that use Amaranth Grains, and is triggered by having Amaranth Grains in your inventory while also having the `spectrum:collect_vegetal` advancement.

However, the advancement `spectrum:milestones/reveal_amaranth`, which is used to unshroud the Amaranth Grains item, can only be triggered by obtaining `spectrum:solve_color_mixing_preservation_ruin`.

This means that if you solve a color-mixing ruin with a friend, both players will unlock the recipes using Amaranth Grains as soon as they get some from the loot chest, but _only_ the player who actually "solved" the ruin will be able to see what the Amaranth Grains actually are.

**To Reproduce**
Pick up some Amaranth Grains while having `spectrum:collect_vegetal`, and observe that this unlocks all the recipes that use Amaranth Grains but doesn't unshroud the item itself.

**Expected behavior**
I'd expect the advancement for collecting Amaranth Grains would also unshroud them, so you don't have to find a new color-mixing ruin to unshroud an item that you've already unlocked recipes for. Alternatively, go the other way and lock the Amaranth Grains recipes behind the `spectrum:reveal_amaranth` advancement, so you can't do anything with the shrouded grains until you properly unshroud them.

**Minecraft version**
1.20.1

**Mod version**
1.7.8

**Comment by DaFuqs** [comment]
That is a tricky one, since the same argument can very well be made for each resource. But for now that will do.
