### ISSUE TITLE
[BUG] Titration Barrel missing recipes

### ISSUE THREAD

**Issue by Elvensong117** [DaFuqs/Spectrum#375]
The recipe for Clotted Cream in the Titration Barrel now only calls for 4 sugar, instead of 4 sugar and 1 bucket of milk. Additionally, the recipe for Lager has disappeared entirely.

I am playing on 1.20.1 and Spectrum is the latest update, 1.7.8. Also, I am playing on Fabric.

![Clotted Cream](https://github.com/DaFuqs/Spectrum/assets/44024289/f9b26cc8-723f-4055-b62d-5ec4ff29368a)

![Lager Gone](https://github.com/DaFuqs/Spectrum/assets/44024289/806a3135-4dc4-49d5-a9f7-6098d64cba65)

**Comment by DaFuqs** [comment]
This is with Create or Bumblezone installed int he same instance, right?

**Comment by Elvensong117** [comment]
It is, yes, both are installed alongside Spectrum. I thought the recent patch notes said the recipes were reworked to provide support, but I wasn't sure if it was intentional that the barrels now don't even require a fluid at all. I did find the recipe for Lager using EMI, and like the clotted cream, it only requires 6 wheat, no fluid.
