### ISSUE TITLE
[BUG] oudated anvil_crushing.nbt structure file

### ISSUE THREAD

**Issue by Linguardium** [DaFuqs/Spectrum#377]
**Describe the bug**
minor issue. anvil_crushing.nbt is using dataversion 3120 which is outdated for 1.20.1 so it hits dfu. surprisingly its the only structure in the version of the mod aof7 uses that is outadated.

**Mod version**
Which version of the mod are you currently using?
1.7.7 but i just checked https://github.com/DaFuqs/Spectrum/commit/6659baddd94a31b2d44b5aa665d54eee64729b71 and its the same

**Comment by DaFuqs** [comment]
Damn. I thought I upgraded all of them. Thx!
