### ISSUE TITLE
[BUG] So the mod page says works with Sinytra for forge but it keeps crashing giving a mixin error todo with InGameHUD

### ISSUE THREAD

**Issue by fabton** [DaFuqs/Spectrum#379]
**Describe the bug**
So i try to load the mod via sinytra connecter for forge on 1.20.1 since i wanted to play the mod along with a bunch of forge mods i wanted to try. i have tried running the mod with the needed parts with my mod list and alone with just the parts it needs to run via sinytra and no matter what it gives the same crash error. 

**To Reproduce**
Load spectrum with all the stated parts for forge Revelationary, Trinkets, Forgified Fabric API, Patchouli (forge), Sinytra Connector, Connector Extras and cardinal-components-api since it requests it in the logs to keep going and it just crashes with a Mixin Error for InGameHUD. 

**Expected behavior**
mod to load into minecraft on forge via Sinytra as stated by the curseforge page

**Minecraft version**
Which version of Minecraft are you currently using?
1.20.1

**Mod version**
Which version of the mod are you currently using?
1.7.8

**Screenshots**
https://imgur.com/a/RmYswca

**Crash Report**
Crash Report
https://mclo.gs/eKpK4nx
Latest Logs
https://mclo.gs/eyKGzXm

**Note**
Thought ill put a issue incase you didn't know about it not working Via Sinytra on 1.20.1 currently while the curseforge page says it does. The error is pointing towards something todo with spectrum as well so might be fixable but understand your focus is it for fabric.

**Comment by DaFuqs** [comment]
Wack. That has certainly worked in the past. Does spectrum-1.7.6 work?

**Comment by fabton** [comment]
Just tried 1.7.6 spectrum and it didnt work, but i've seem to have found the issue looks like something broken within sinytra in more recent updates and had to downgrade to Connector-1.0.0-beta.34+1.20.1, seems to start issues from Connector-1.0.0-beta.35+1.20.1 where it crashes trying to press singleplayer and then after that just crashes on start up with any version of sinytra after that.

also Spectrum 1.7.8 seems to also work with Connector-1.0.0-beta.34+1.20.1 so for sure looks to be a broken issue via some change in sinytra connector latest versions. just wondering what version was used of connector when yous first got it to work? since that might be the best and most stable version of connector to use atleast with spectrum.

**Comment by LyonGalaxy** [comment]
I am having the exact same problem, had to downgrade (just after updating) to Connector-1.0.0-beta.34+1.20.1 to make the game start with Spectrum. I also had to downgrade to ConnectorExtras-1.9.2+1.20.1

**Comment by DaFuqs** [comment]
Good catch, you two! And thanks for letting me know.
Since it is nothing I can fix myself I will close this issue, but I pinned it so everyone with the same issue will find it quickly

**Comment by furtabs** [comment]
Update thjis is now fixed you just have to use the additional entity attributes forge port and remove the jar in jar for additional entity attributes fabric inside the latest spectrum jar.
