### ISSUE TITLE
need hint for enchanting mastery and overenchanting 

### ISSUE THREAD

**Issue by DylanGonthier** [DaFuqs/Spectrum#380]
We are a group of friends on a server and really like your mod, it's reaaly well made and all but really hard to advance in it if you don't know where to go, per chance i've already played on the 1.6.9 version so it was fast enough for the start and midgame but late was ok too, but for the secret advancement i'm really lost, i'm the sheeper for this mod for my friends, so if you can give us some hints for these two things cause it's been 3 hours and we didn't find anything for these two ones, so can you give hints or the solutions ?

thank you a lot for this great mod and the hints/solutions in advance 
ps: we're on the 1.7.7 version if that change something and on the modpack all of fabric 7
2ps: i'm french and i'm sorry if the text is really ugly to read

**Comment by Gronglegrowth** [comment]
Unless you're playing the mod in certain modpacks, those are not unlockable. All of Fabric 7 is not one of those modpacks.

**Comment by Robotgiggle** [comment]
If you want to manually unlock them, you can use commands to grant yourself the `spectrum:milestones/unlock_conflicted_enchanting_with_enchanter` and `spectrum:milestones/unlock_overenchanting_with_enchanter` advancements. Apart from that, they're unobtainable in survival.
