### ISSUE TITLE
[BUG] Soul Soil/Sand creates Primordial Fire when lit

### ISSUE THREAD

**Issue by LokiY2K** [DaFuqs/Spectrum#385]
**Describe the bug**
Instead of creating Soul Fire as intended, setting Soul Soil on fire creates Primordial Fire. Soul Sand will also create Primordial Fire when set on fire.

**To Reproduce**
Use any fire starting item (Flint & Steel, Fire Charge, etc.) on either Soul Soil or Soul Sand.

**Expected behavior**
Flint & Steel (or any other fire source) should set Soul Soil on Soul Fire.

**Minecraft version**
1.20.1

**Mod version**
1.7.8

**Screenshots**
![image](https://github.com/DaFuqs/Spectrum/assets/67063563/7082bd49-cfd2-447a-b13c-1a6c090edb80)

**Crash Report**
N/A

**Comment by 800020h** [comment]
already fixed in dev
