### ISSUE TITLE
[Feature] Better bismuth hints

### ISSUE THREAD

**Issue by DADA30000** [DaFuqs/Spectrum#386]
I may be dumb, but I don't understand how to grow bismuth crystals, it says they grow "in proximity with other metals", I placed it on block of raw iron ore, iron block and on iron block, it doesn't grow, maybe give better hints?

**Comment by Gronglegrowth** [comment]
Bismuth growth isn't too fast; you’ll need to wait longer before assuming one of your attempted solutions is incorrect.

Imo, the hint works fine. You did, after all, find one of the correct blocks - you just didn't wait long enough...

**Comment by DADA30000** [comment]
> Bismuth growth isn't too fast; you’ll need to wait longer before assuming one of your attempted solutions is incorrect.
> 
> Imo, the hint works fine. You did, after all, find one of the correct blocks - you just didn't wait long enough...

Oh, ok then, but I still think it needs to be mentioned that it's gonna take a lot of time)
