### ISSUE TITLE
[BUG] Zenith Gems not working on Spectrum Workstaffs

### ISSUE THREAD

**Issue by ShadowFox88** [DaFuqs/Spectrum#391]
**Describe the bug**
Issue also created at; https://github.com/TheWinABagel/Zenith/issues/156

**To Reproduce**
Linked above to other issue. - Tested on AOF7 2.1.2

**Expected behavior**
Both the second pickaxe with both gems and the workstaff with both gems should have a similar amount of items

**Minecraft version**
1.20.1

**Mod version**
1.7.8

**Screenshots**
Linked above in referenced issue.

**Crash Report**
N/A

**Comment by TheWinABagel** [comment]
This is not a spectrum issue, and is being tracked the zenith repo (https://github.com/TheWinABagel/Zenith/issues/156)

**Comment by DaFuqs** [comment]
Awesome! Thank you for taking care of it. If you would like anything changed from my side @ me in the Zenith issue
