### ISSUE TITLE
[Feature] Set the sounds to stream: true

### ISSUE THREAD

**Issue by JordanPlayz158** [DaFuqs/Spectrum#403]
I notice that the 18MB of sounds don't have the `stream: true` flag but it is undefined/unset which sets stream to false which means all of those are loaded into memory, I know it is not a lot of memory usage but it would be nice to set stream to true when appropriate like I notice a 4 minute ogg that is 3.2MB which can probably be streamed from disk without issue.

**Comment by DaFuqs** [comment]
Very much true, I will add those flags. Ty!

**Comment by JordanPlayz158** [comment]
Thank you so much and thanks for making and maintaining the mod <3

**Comment by DaFuqs** [comment]
done
