### ISSUE TITLE
[BUG] Vague file name for release 1.7.11 on Modrinth

### ISSUE THREAD

**Issue by JordanPlayz158** [DaFuqs/Spectrum#404]
**Describe the bug**
The file name for Release 1.7.11 on Modrinth is "1.7.11-1.20.1.jar" which based on past names, looks like a 1 time fluke but just wanted to inform you of that.

**To Reproduce**
https://modrinth.com/mod/spectrum/version/1.7.11 Scroll to bottom to "Files" section

**Expected behavior**
ModID or ModName + Version + MC Version

**Minecraft version**
1.20.1

**Mod version**
1.7.11

**Screenshots**

**Crash Report**
If it is a crash bug add your crash log here

**Comment by DaFuqs** [comment]
Yeah, I fucked up a bit with that one. Sadly both CF & MR do not allow changing the file name after upload. Next version will have the proper name again.

**Comment by JordanPlayz158** [comment]
Oh I see, thank you!
