### ISSUE TITLE
Spawners change to pig when mined with silktouch

### ISSUE THREAD

**Issue by Kasax007** [DaFuqs/Spectrum#41]
Hey there, 
I have a mod pack called Dreamcraft and I got a bug report for spawners turning into pig when mined with a silk touch pickaxe, once they are placed again. I was wondering if you have any insight or idea on this issue. Another Idea I have would be to just disable spawners dropping for my mod pack if there is any way to do so. 
Any help would be greatly appreciated. 
Here is the original bug report: 
https://github.com/Kasax007/Modpack-Development/issues/26

Spectrum Version: 
spectrum-1.2.8-1.18.1-midgame9.jar

**Comment by DaFuqs** [comment]
I will take a look at it ✔

**Comment by DaFuqs** [comment]
I cannot reproduce your issue with just Spectrum, I am afraid. Using a Silk Touch enchanted Diamond Pickaxe drops nothing. Can you try find out what other mod may interfering here, please?

**Comment by linaraincalzando** [comment]
I am the origional submitter of the the bug. Vanilla Tweaks allows spawners to be silk touched. This is also about 2 versions of Spectrum ago. Spawners now show not available yet.
![2022-03-27_16 29 36](https://user-images.githubusercontent.com/99147940/160301826-ebe185d6-b0a1-40a1-861f-00983b219f51.png)

**Comment by Kasax007** [comment]
It was a vanilla tweaks-related issue. There seems to be a conflict between these two mods. Disabled it in the configs of it and now it works.

**Comment by linaraincalzando** [comment]
What did you disable in the configs? While I am not a full modpack developer I do like building custom mod packs?

**Comment by Kasax007** [comment]
Vanilla tweaks config file: silkSpawners = true --> false

**Comment by linaraincalzando** [comment]
I am confused on how this fixes spectrum taking ownership of a silk-touched spawner? Spectrum has spawners as an item, that is how spectrum is taking ownership of the spawners in the first place. That is why I submitted the new screenshot, they are not just the ones that were silk-touched after Spectrum was added to the modpack but the ones that were silk touched before.

**Comment by Kasax007** [comment]
The only thing that I can tell you is that it fixes spawners that are now mined with silk touch won't be spectrum spawners but Vanilla ones which keep the NBT data when placed down again. Apparently Vanilla Tweaks mod and Spectrum don't get along in this regard. I don't know if you will ever be able to place down the spectrum versions of them and get the correct mob. That is out of my control.

**Comment by DaFuqs** [comment]
This one, I assume?
https://www.curseforge.com/minecraft/mc-mods/vanillatweaks

**Comment by Kasax007** [comment]
Yes
