### ISSUE TITLE
[BUG] Spectrum crashing with Enchantment descritpions latest version

### ISSUE THREAD

**Issue by DarianStardust** [DaFuqs/Spectrum#411]
**Describe the bug**
Makes the game crash right after the "Play" button is done, I reported  it on Enchantment Descriptions but they said the issue is caused by Spectrum

**To Reproduce**
Have Enchantment Descriptions 17.0.16, and Spectrum 1.7.10

**Expected behavior**
Minecraft to load and open the main menu

**Minecraft version**
1.20.1, Fabric

**Mod version**
1.7.10

**Crash Report**
[crash-2024-06-06_13.12.36-client.txt](https://github.com/user-attachments/files/15652790/crash-2024-06-06_13.12.36-client.txt)

**Comment by Chicxilulb** [comment]
I got the same crash
[crash-2024-06-10_14.22.19-client.txt](https://github.com/user-attachments/files/15777663/crash-2024-06-10_14.22.19-client.txt)

**Comment by DaFuqs** [comment]
Implemented in https://github.com/DaFuqs/Spectrum/commit/5584cce30cc84805add2e9a2c04790cfb3d3a827

**Comment by DaFuqs** [comment]
release 1.7.12 is out!
