### ISSUE TITLE
[BUG] Crashing the server when the potion workshop brews anything in the Potion Workshop Crafting section

### ISSUE THREAD

**Issue by spencer012** [DaFuqs/Spectrum#413]
**Describe the bug**
Whenever I try to craft anything under the "Potion Workshop Crafting" section the server crashes (even in singleplayer). It does not crash if I remove "Item Obliterator" or "Polymorph", so if this is better suited on their projects, tell me.

**To Reproduce**
I have not been able to replicate it on a new profile, but here is the modpack I am playing: https://modrinth.com/modpack/stripes-journey-vibes
Unlock the potion workshop
Try to brew a bucket of water/liquid crystal
The server crashes when it starts to brew

**Expected behavior**
Not crashing

**Minecraft version**
1.20.1

**Mod version**
1.7.11

**Crash Report**
https://mclo.gs/NIwIWZy

**Comment by spencer012** [comment]
I ran into another issue, the Color Picker also immediately crashes the server when any pigment is put into the slot. https://mclo.gs/AWDeOlg

**Comment by DaFuqs** [comment]
I am able and will fix the crash, but just as a short disclaimer: with the way Item Obliterator is coded currently, it is not able to handle dynamic recipes at all.

**Comment by DaFuqs** [comment]
Done. If it still crashes for you, update Item Obliterator to the newest version. They fixed some stuff on their side, too.
