### ISSUE TITLE
[BUG] Mod has mixin errors on 1.18.2

### ISSUE THREAD

**Issue by Sunconure11** [DaFuqs/Spectrum#42]
https://pastebin.com/5VJ5ypsX

**Comment by Niketats** [comment]
mod is incompatible with 1.18.2, only 1.18.1

**Comment by DaFuqs** [comment]
> mod is incompatible with 1.18.2, only 1.18.1

this. Working on it :)

**Comment by Niketats** [comment]
Oh, yes, i already tested dev builds, looks nice ;)

**Comment by DaFuqs** [comment]
done in upcoming 1.18.2 release.
