### ISSUE TITLE
[BUG] crash upon entering world with black materia

### ISSUE THREAD

**Issue by annahla** [DaFuqs/Spectrum#424]
we just did the whole fucked-up-infusion-creating-midnight-solution thing, and when trying to clean up some midnight solution, accidentally placed water next to it. this created black materia that crashes the game every time the chunk is loaded. black materia created from block collisions did not result in a crash.

as both of us in the mp game were in the area, we can't load the world at all.

running spectrum 1.7.13 (though originally 1.7.11; updated and the crash still happens) on sinytra for mc 1.20.1.

crash report: https://mclo.gs/scQve8c

**Comment by annahla** [comment]
whoops it's a compat issue w immersive weathering for forge (on their side)

**Comment by DaFuqs** [comment]
Thank you for letting us know. If there is anything we can do on our side just open this issue again 👌
