### ISSUE TITLE
[Feature] Slush + Sugar cane

### ISSUE THREAD

**Issue by GameOnne** [DaFuqs/Spectrum#425]
Being described as "ever-moist", I believe that sugar cane should be able to grow on slush regardless of whether or not theres water nearby. This would make farming sugar cane easier, especially if you're using something like the Create mod.

**Comment by DaFuqs** [comment]
Definitely. Good idea!

**Comment by DaFuqs** [comment]
Added for next patch ✔️

**Comment by f-raZ0R** [comment]
Should this also be done for quitoxic reeds?
