### ISSUE TITLE
[Feature] Crystal Apothecary collects #c:clusters

### ISSUE THREAD

**Issue by EntityinArray** [DaFuqs/Spectrum#433]
Crystal Apothecary should collect clusters with #c:clusters tag. This will impove mod compatibility, such as allow collecting Certus Crystals from Applied Energistics and other mods in the future.

**Comment by DaFuqs** [comment]
It collects blocks from the tag `spectrum:crystal_apothecary_harvestable`, which is 
```json
{
  "values": [
    "#c:clusters",
    "#spectrum:crystallarieum_growable_clusters"
  ]
}
```
so this is already a thing. Anything in particular you are missing?

**Comment by EntityinArray** [comment]
This setup doesn't work, it doesn't collect certus quartz.
`#spectrum:crystal_apothecary_harvestable` doesn't seem to include `#c:clusters`

This is on Minecraft 1.19.2 with Spectrum 1.6.12-1.19.2-leisure_time

![image](https://github.com/DaFuqs/Spectrum/assets/18554021/43b88c42-57d5-48a0-ba9f-b5893485ce35)
![image](https://github.com/DaFuqs/Spectrum/assets/18554021/eefd4cf6-0890-425c-9b46-e77fc965b113)


![image](https://github.com/DaFuqs/Spectrum/assets/18554021/a3d1a1b6-0fb4-472d-963e-76719ff36ea5)

**Comment by DaFuqs** [comment]
Aaaaah, that is a quite outdated version you are running. In that case updating will do :>

**Comment by EntityinArray** [comment]
Thank you, the new 1.7.11 version works! But Apothecary name got replaced with a placeholder for some reason
![image](https://github.com/DaFuqs/Spectrum/assets/18554021/881b788d-c23e-4f2b-9fc4-727bbd23be0d)
