### ISSUE TITLE
[BUG] (incompatibility?) Crash when opening creative inventory

### ISSUE THREAD

**Issue by Kikithecat12345** [DaFuqs/Spectrum#435]
**Describe the bug**
When opening the creative menu, the game crashes.

**To Reproduce**
1. Open the creative menu.

**Expected behavior**
The game doesn't crash.

**Minecraft version**
Fabric 1.20.1

**Mod version**
1.7.13

**Crash Report**
https://mclo.gs/f4xBHAp

This may not be a spectrum issue, but it's the only mod in the crash log, so I have to start somewhere.

**Comment by DaFuqs** [comment]
Sorry I am just answering now.

The crash by Spectrum here is not the source, but more of a symptom, really.
Any mod that modifies enchantments?

**Comment by DaFuqs** [comment]
From what I have seen, this issue arises when a mod messes up load order, for example by constructing stuff on startup that should only be messed with when loading worlds after startup has finished (like loot tables)
