### ISSUE TITLE
[BUG] Crash on startup when Enchancements mod is present

### ISSUE THREAD

**Issue by CookieGD** [DaFuqs/Spectrum#436]
**Describe the bug**
When adding Spectrum to a modpack with the Enchancements mod present the game will crash on startup.

**To Reproduce**
Install latest 1.20.1 versions of Spectrum and Enchancements on Quilt for 1.20.1

**Expected behavior**
Regular startup without issues.

**Minecraft version**
1.20.1 (Quilt)

**Mod version**
1.7.14-1.20.1-deeper-down

**Screenshots**

**Crash Report**
https://mclo.gs/tS5t28y

**Comment by DaFuqs** [comment]
Funky.

relevant mixins in the stack trace:
- at net.minecraft.class_2960.handler$bcn000$**entity_texture_features**$etf$illegalPathOverride(class_2960.java:1019)
- net.minecraft.class_2588.localvar$cjf000$**[enchancement$spectrum**$replaceDisallowedEnchantments](https://github.com/MoriyaShiine/enchancement/blob/main/src/main/java/moriyashiine/enchancement/mixin/vanillachanges/disabledisallowedenchantments/client/integration/spectrum/TranslatableTextContentMixin.java)(class_2588.java:3018)


Looks like one of Enchancements compat mixins for Spectrum and possibly Entity Texture Features are fighting. Does the crash still occur without Entity Texture Features?

This one has to be fixed on Enchancement's side.

Hi, @MoriyaShiine! Do you still support 1.20.1? I see your repo is on 1.20.6 at the moment.

**Comment by MoriyaShiine** [comment]
I unfortunately do not and am currently already working on the 1.21 version, which will be the new supported version. That mixin in specific doesn't look like it has any reason to break, though. It's just a regular ModifyVariable that doesn't even rely on Spectrum code and is just a basic string comparison.

**Comment by CookieGD** [comment]
does that mean that you can't really help with this issue? :/

**Comment by CookieGD** [comment]
It seems like ETF causes the issues and not Enchancement. Removing ETF (and EMF) fixed the startup crash.

**Comment by DaFuqs** [comment]
Since this should be fixed by the others, I will close this issue. I will watch the mentioned issue, though, in case I can help out some way or another.
