### ISSUE TITLE
[BUG] Update caused all dicovered recipies to disappear

### ISSUE THREAD

**Issue by EntityinArray** [DaFuqs/Spectrum#437]
**Describe the bug**
After updating spectrum-1.6.12-1.19.2-leisure_time.jar to 1.7.11-1.19.2.jar all recipies are gone and items are obscured and I'm unable to wear circlets.

**To Reproduce**
Update the mod from spectrum-1.6.12-1.19.2-leisure_time.jar to 1.7.11-1.19.2.jar

**Expected behavior**
Update shoudn't drop all discoveries

**Minecraft version**
1.19.2 Fabric

**Mod version**
1.7.11-1.19.2

**Screenshots**
![image](https://github.com/user-attachments/assets/15e19718-97e0-4a29-9d69-3019135cb0ce)
![image](https://github.com/user-attachments/assets/3ec00c0f-219a-479d-87e7-ff77b82ec930)

**Comment by EntityinArray** [comment]
It might be difficult to pinpoint the cause from limited information I provided.
Is there a way to disable this progression unlocking system entirely as a workaround?

Feel free to ask for any info

**Comment by DaFuqs** [comment]
The update from 1.6.12 -> 1.7.11 is one full year of dev time. Sadly with the insane amount of changes, some things are bound to break.

I builtin an upgrade mechanism from 1.6.x => 1.7.x in the guidebook opening, so opening the guidebook once should fix most unlocks. For a few I missed picking up items from chests might do the rest. After that take a look at your advancements - they will show you what is missing exactly.

**Comment by EntityinArray** [comment]
thank you very much, you are our saviour
