### ISSUE TITLE
[BUG] Everpromise Ribbon works on all mob types, including bosses

### ISSUE THREAD

**Issue by Robotgiggle** [DaFuqs/Spectrum#439]
**Describe the bug**
The everpromise ribbon is currently usable on literally any mob, including hostile ones and even bosses. This means that you can use it to get a memory of any mob in the game, by simply applying the ribbon and then killing the mob.

**To Reproduce**
- Name an everpromise ribbon
- Apply ribbon to a hostile mob
- Observe that it works, and causes the mob to drop a Broken Promise of itself on death

**Expected behavior**
I would expect the ribbon to work as described in the tooltip, ie only on animals.

**Minecraft version**
1.20.1

**Mod version**
1.7.14

**Screenshots**
This is a wither
![image](https://github.com/user-attachments/assets/f649da32-0628-43b7-af87-453fd0a8107d)

**Comment by DaFuqs** [comment]
Done!
