### ISSUE TITLE
Just a slfish request, sorry if people have already asked.

### ISSUE THREAD

**Issue by Tenchu98** [DaFuqs/Spectrum#44]
I am wondering if there will be a forge port for this mod, as I really like the mod but would like to use it with some forge only mods.

I apologize if this has been asked before, and am only trying to settle my own curiosity.

**Comment by DaFuqs** [comment]
I worked with forge, bukkit and fabric and forge was an absolute pain, to be honest.

Someone offered to port Spectrum to forge, but I have not heard an update since January. But who knows. :)
