### ISSUE TITLE
[BUG] Incompatible with Tree Harvester

### ISSUE THREAD

**Issue by SuperKnux** [DaFuqs/Spectrum#440]
**Describe the bug**
Spectrum is incompatible with Serilum's Tree Harvester. If you harvest a colored tree, or have quick leaf delay on, the tree gives oak logs and saplings along with no pigment.

**To Reproduce**
Use Spectrum along with [Tree Harvester](https://www.curseforge.com/minecraft/mc-mods/tree-harvester).
Enter a world, grow a Colored Tree, and try to use the harvesting ability on it.

**Expected behavior**
The tree should drop colored drops.

**Minecraft version**
1.20.1

**Mod version**
1.7.14

**Comment by DaFuqs** [comment]
TreeHarvester [does not respect the player breaking the block](https://github.com/Serilum/Tree-Harvester/blob/b60bab973f076944b78c74b9492e8f3763ba77b9/Common/src/main/java/com/natamus/treeharvester/events/LeafEvents.java#L36).

You will notice breaking a block using that mod will neither increase your mined block stats, or uses the enchants on your tool.
That has to be properly handled by Tree Harvester, sorry.
