### ISSUE TITLE
[BUG] Incompatible with mishanguc 

### ISSUE THREAD

**Issue by ERroooooR** [DaFuqs/Spectrum#441]
**Describe the bug**
https://github.com/SolidBlock-cn/mishanguc/issues/8

**Minecraft version**
1.20.1

**Mod version**
spectrum 1.7.7
mishanguc 1.3.0

**Crash Report**
https://mclo.gs/Wd8W6Qn

**Comment by DaFuqs** [comment]
Oh no, not this again. I know this issue very well.
This is a change that should be fixed on Mishang Urban Construction's side and I have communicated to them before, why:
- Mishang builds recipes/loot tables while the game is still initializing. This has to be done in the world loading phase after the game is finished initializing (when vanilla loads its recipes/loot tables).
- Same is true for the PointOfInterestTypeMixin, which triggers the actual issue. Adding blocks to a point of interest - or a point of interest in general, can be done without mixin. This code also runs at init accessing blocks & items, when blocks & items of other mods are not registered yet.

[Botania](https://github.com/VazkiiMods/Botania/blob/1.20.x/Fabric/src/main/java/vazkii/botania/fabric/mixin/ItemPredicateFabricMixin.java) and presumably other mods use the same code to make their shears work, so Mishang Urban Construction may also have trouble with those.

**Comment by ERroooooR** [comment]
The latest build is already ready to start,But I opened the backpack and there was a new problem. 
log: https://mclo.gs/9KUwHGd

**Comment by DaFuqs** [comment]
Yeah, at the moment the fix is still very nonfunctional, as I noticed it breaks quite a few vanilla assumptions.
I will try another few things, but I can't promise I will be able to fix it on my end. (I can't do certain things until Spectrum's mod initializer got executed, which would only be true when being at the main menu)

**Comment by DaFuqs** [comment]
I tried everything I could, but everything comes down to trying to load stuff after startup that would have to be done at startup to not cause any issues.
I'm afraid I'll have to give that back to mishanguc to fix to move their after-init stuff to actual after-init, sorry
