### ISSUE TITLE
[BUG] Embeddium breaks fluid rendering

### ISSUE THREAD

**Issue by Azzyypaaras** [DaFuqs/Spectrum#442]
![image](https://github.com/user-attachments/assets/58c3ff12-a2c7-4cf0-9908-67a72147bdc2)

Shit's fucked

**Comment by Azzyypaaras** [comment]
Oh right ehem. 
**Mod version**: the ufcking dev env

**Comment by imreallybadatnames** [comment]
what's the embeddium ver?

**Comment by Azzyypaaras** [comment]
0.3.25
