### ISSUE TITLE
Crystallaerium não faz o menor sentido

### ISSUE THREAD

**Issue by glittertai** [DaFuqs/Spectrum#447]
Tenho jogado Spectrum no All of Fabric 7 e segundo meu progresso preciso fazer crescer clusters em meu Crystallaerium. No livro não há nada de intuitivo! Inúmeras setas indicando algo e embaixo um tempo em segundos. fiz o que o livro supostamente manda fazer e por mais de 3 horas NENHUM cristal cresceu, além disso não está claro se as receitas que ainda nao desbloqueei são devido a estar presa nesse Crystallaerium ou se simplesmente elas ainda não foram criadas por quem desenvolveu o mod. O tempo descrito de crescimento NÃO CONDIZ COM O TEMPO DOS CRISTAIS CRESCEREM. Já esperei horas e não houve nenhuma mudança. Todos continuam no estágio inicial e estou presa nisso. Um final frustrante pois tenho um grande amor ao mod. Só gostaria de saber como realmente funciona o Crystallaerium pois o criador do mod não posta nem um único vídeo de explicação e você precisa ficar perdido eternamente já que não é compreensível.

**Comment by TheTrueYak** [comment]
Not a developer for Spectrum, but I also struggled with the Crystallarieum my first time, so I made a little mini tutorial video that can hopefully show how to use it. As the book says, it requires raw ore, which is thrown on top, a catalyst item, which is listed next to the item in the book entry for growing it, and a flask of ink, the color of which is dependent on the color of the Crystallarieum's ring. As shown in the video, the color of the ring for any given material is also shown in the tooltip of the Crystallarieum in the book entry of whatever it is you are growing. In the video's case, this is malachite, which requires white ink. There is a slight particle indicator of whether or not the Crystallarieum is working or not, but it's not exactly obvious unless you know what to look for. I hope this helps with your confusion. Apologies for this response being in English, I don't speak Portuguese.


https://github.com/user-attachments/assets/65cd44ac-9de9-4302-a4af-10bc4ad7abe2

**Comment by glittertai** [comment]
Isso realmente foi de grande ajuda! Muito obrigada pelo vídeo, consegui entender muito bem agora. Realmente não conseguia entender a lógica da cor do frasco de tinta que seria necessário. O que me deixa mais confusa são as setas mostradas no livro abaixo do catalisador. Algumas são setas verdes apontadas para cima, algumas são laranja apontadas para noroeste ou coisas do tipo. Acredito que verde seja positivo e vermelho seja negativo porém as setas apontadas "em diagonal" parecem sem sentido. Seu video foi de grande ajuda e esclarecimento. Realmente gostaria que houvessem tutorias disponíveis no youtube mas há pouquíssimos conteúdo. Novamente obrigada
