### ISSUE TITLE
Many errors in the registration

### ISSUE THREAD

**Issue by YOUNIN15** [DaFuqs/Spectrum#449]
**Describe the bug**
Sometimes when I add one or another mod to my server when I join the server after a few seconds the game crashes. In the log there are many errors related to spectrum, most of the time it just fixes itself by removing and adding mods again, it's quite rare, I don't know if it's a problem with another mod.

**To Reproduce**
1. Join the server.
2. Wait a few seconds.
3. The game stops and does not respond.

**Expected behavior**
A concise description of what you expected to happen.

**Minecraft version**
fabric 0.16.0, minecraft 1.20.1

**Mod version**
Spectrum 1.7.15-deeper-down

**Screenshots**
![image](https://github.com/user-attachments/assets/b24b6149-1e0a-44fe-a8fe-01e5167cac48)

**Crash Report**
[If it is a crash bug add your crash log here](https://mclo.gs/RKgBLOj)

**Comment by DaFuqs** [comment]
That is certainly not a vanilla or spectrum error message you see here.
Some kind of recipe tweaking mod?

**Comment by YOUNIN15** [comment]
> That is certainly not a vanilla or spectrum error message you see here. Some kind of recipe tweaking mod?

I think so, I do not remember well, but this error happened sometimes, I guess it was a problem of another modification, it has not happened again so far.

**Comment by DaFuqs** [comment]
Huh, really weird. Let me know if you found a way to reproduce it!
