### ISSUE TITLE
[BUG] Azure Dike points not protection from all damage

### ISSUE THREAD

**Issue by GoldenAlpharex** [DaFuqs/Spectrum#45]
**Describe the bug**
Not every type of damage is currently blocked by Azure Dike, making it a bit awkward, especially considering how the main sources of damage I've found to not respect it are coming from Spectrum itself.

**To Reproduce**
Walk on some Fading, or some Failing, and see that you're taking damage, even if you have Azure Dike that should take the damage first.

**Expected behavior**
For Azure Dike to fully work like Absorption hearts that regenerate.

**Mod version**
`spectrum-1.2.13-1.18.1-midgame14-trinkets-brewing`

**Comment by DaFuqs** [comment]
Azure Dike is set to not protect from unblockable (like hunger) and void damage sources. that part seems fine.
But Decay damage was indeed set to unlockable, which is a bit silly.
