### ISSUE TITLE
[BUG] Spectrum 1.7.16 is not working on connector with the create mod (forge)

### ISSUE THREAD

**Issue by xg787** [DaFuqs/Spectrum#456]
**Describe the bug**
load crash

**To Reproduce**
load Spectrum 1.7.16 on connector beta 45 with the create mod (forge)

**Expected behavior**
Loads

**Minecraft version**
1.20.1

**Mod version**
1.7.16

**Crash Report**
[crash-2024-08-15_19.39.55-client.txt](https://github.com/user-attachments/files/16631227/crash-2024-08-15_19.39.55-client.txt)

(1.7.15 works fine tho)

**Comment by DaFuqs** [comment]
Looks like the new create compat breaks on forge.

**Comment by thedeerirty** [comment]
I understand that its not quite a priority, but it would be cool to see this fixed eventually. Perhaps just an optional toggle of disabling compact if like, trying to make it compatible with both fabric and forge create is too much? idk I'm spitballing.

**Comment by DaFuqs** [comment]
Does it still crash when you add `create` to the Spectrum configs `IntegrationPacksToSkipLoading` list?

**Comment by xg787** [comment]
it loads with the config change

**Comment by f-raZ0R** [comment]
Fixed in dev
(I do not have the perms to close this issue, so somebody else please do this!)
