### ISSUE TITLE
[BUG] Inventory Insertion does not seem to work

### ISSUE THREAD

**Issue by GoldenAlpharex** [DaFuqs/Spectrum#46]
**Describe the bug**
I have Inventory Insertion on a diamond pickaxe (with some other enchantments), and it simply doesn't get in my inventory when I mine said items.

**To Reproduce**
Have the enchantment on a pickaxe, try to break a block, see it not go directly in your inventory.

**Expected behavior**
For the broken block to go directly in my inventory.

**Mod version**
`spectrum-1.2.13-1.18.1-midgame14-trinkets-brewing`
I'm also playing on All of Fabric 5, just in case there's possible compatibility issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/58045821/162585527-1970d78f-ca7d-4f0b-88b9-a420242eca2a.png)

**Comment by DaFuqs** [comment]
I have seen that myself, only on the AoF pack, though. Some mod is interfering with this enchantment. Sadly noone who reported that before did tell me what mod exactly and I always had more pressing issues to find out the conflict myself.
Leaving it open as a reminder.

**Comment by DaFuqs** [comment]
It was a conflict with Incantationem and me wanting to do the same thing. 
Fixed via https://github.com/DaFuqs/Spectrum/commit/115302929fcc794c859f133740589c26d9e3894b
