### ISSUE TITLE
[BUG] Quitoxic Reeds can be placed on land, where they will never grow

### ISSUE THREAD

**Issue by f-raZ0R** [DaFuqs/Spectrum#463]
**Describe the bug**
Literally just found out that this is actually a BUG, and not intended behavior. You can place quitoxic reeds on land. Out of water. They also generate naturally like this. Due to how the reeds work, they will never grow. This has caused many many people to be confused why their reeds arent growing

**To Reproduce**
Place quitoxic reeds on land. Suffer, as the book never tells you that they “need water”, and be confused as your reeds never grow despite being on clay

**Expected behavior**
Either the reeds refuse to be placed where they can never grow, or the reeds grow where they can be placed

**Minecraft version**
1.20.1

**Mod version**
1.7.16, and also the latest alpha

**Comment by DaFuqs** [comment]
Fixed in e71212c82b832650f2401fff09ea0034968c0bca
