### ISSUE TITLE
[Feature] Abyssal Vines and Nightdew Vines should be shearable like glow berry vines, to make them stop growing

### ISSUE THREAD

**Issue by f-raZ0R** [DaFuqs/Spectrum#466]
Cave vines can be made to stop growing, by using shears on them. This is a really great way to use these for decoration, without requiring awkwardly placing midair string, or constantly trimming them. However, this does not also work for the cave vine-like vines that spectrum adds. For consistency, these should act the same way.

**Comment by Azzyypaaras** [comment]
Perhaps this is broken in some way, but unless it is a very sneaky bug this is already a thing? 
![image](https://github.com/user-attachments/assets/e3faad46-e550-417b-b453-7439fb074c70)

**Comment by f-raZ0R** [comment]
Okay yeah it does work now, either it wasn't a thing in the version i tested, or I'm big stupid
