### ISSUE TITLE
[BUG] Being on Primordial fire does not make damage sounds, and causes a damage tilt every tick

### ISSUE THREAD

**Issue by f-raZ0R** [DaFuqs/Spectrum#468]
**Describe the bug**
Being on primordial fire directly lowers your hp, without doing a lot of damage stuff. Because of this, it is A: completely silent, something i wouldn't expect my very soul burning away to be, and B: happens every single tick, causing horrendous looking screen smearing, as the screen constantly tilts back and forth.

**To Reproduce**
Set yourself on primordial fire. Suffer

**Expected behavior**
Being on primordial fire would make some kind of sound, and would not look extremely visually buggy from taking damage every single tick

**Mod version**
1.8.0 alpha2

**Comment by KatTheFox** [comment]
a. You're right, we should get some horrible screaming sfx for it /j

**Comment by f-raZ0R** [comment]
Still doesn’t have any damage sounds, so I don’t think this issue should be closed just yet
