### ISSUE TITLE
[Feature] Make Quitoxic be able to grow (to allow for it to be farmed)

### ISSUE THREAD

**Issue by GoldenAlpharex** [DaFuqs/Spectrum#47]
Unless it's a bug and it's actually meant to grow, Quitoxic Reeds, as it stand, do not grow past whatever height they're at when generated, or when placed down in the world.

It would be quite nice to have them work basically like Sugar Cane, as I'm pretty sure they're based off of it to an extent, but it could still require you to be in the swamp for it to work (or perhaps even adding a new magical item that could make a "Swamp Containment Field" to allow for the Quitoxic Reeds to grow outside of a swamp? Could be interesting.)

**Comment by DaFuqs** [comment]
It is already farmable. They really, really like clay. :^)
