### ISSUE TITLE
[BUG] Incompatibility with the "Camerapture" mod breaks crafting

### ISSUE THREAD

**Issue by JoaquinAguilera** [DaFuqs/Spectrum#472]
**Describe the bug**
When both Spectrum and [Camerapture](https://github.com/chrrs/camerapture) are installed Spectrum's pigment table crafting will no longer work

**To Reproduce**
* Enter any world in singleplayer or multiplayer
* Progress through spectrum to the first pigment table to ensure the crafting recipes are unlocked
* Attempt any crafting recipe (neither Vanilla nor Spectrum work)
* Nothing happens

**Minecraft version**
Minecraft 1.20.1 with Fabric 0.92.2

**Mod versions**
Spectrum version 1.7.15 and Camerapture 1.6.0

**Screenshots**
![image](https://github.com/user-attachments/assets/e0c0fd67-8fde-4888-bc13-df9e84b5f113)

The exact same setup with the Camerapture mod removed does work.

**Comment by Loppy-Hausen** [comment]
Thank you for having reported this. I'd have a miniature riot if I removed Camerapture from my server. But thanks to you I was able to find the compatibility issue relatively quickly. Here's to hoping it's an easy/ eventual fix!

**Comment by DaFuqs** [comment]
The bug is on Cameraptures side.
I created a bug report for them https://github.com/chrrs/camerapture/issues/30

**Comment by DaFuqs** [comment]
Was just fixed on their end ✔️
