### ISSUE TITLE
[Feature] Feature Parity with regular bundles for the Bottomless Bundle

### ISSUE THREAD

**Issue by GoldenAlpharex** [DaFuqs/Spectrum#48]
It would be nice to be able to take things in and out of the Bottomless bundle by keeping on right-clicking while dragging it across different inventory slots, much like the vanilla bundles allow you to.

It makes inserting and extracting items from them much easier and intuitive, which is nice.

**Comment by DaFuqs** [comment]
Definitely.

**Comment by DaFuqs** [comment]
Funnily, this feature seems to be added by another mod and is not in vanilla. To keep that identical I would rather not, albeit I very much would see the use.
