### ISSUE TITLE
[BUG] Honey Does not cure Fatal Poison

### ISSUE THREAD

**Issue by f-raZ0R** [DaFuqs/Spectrum#488]
one of the most niche mechanics in minecraft makes a return.

Honey, when drank, cures poison.
However, it does not cure fatal poison.

Expected behavior: as fatal poison is poison, it should be cured by drinking honey

**Comment by Azzyypaaras** [comment]
wha -
![image](https://github.com/user-attachments/assets/ad849b15-6815-4f0c-8506-4b99afdbe146)
HUH???

**Comment by KatTheFox** [comment]
modded players when vanilla mechanics

**Comment by Azzyypaaras** [comment]
Fixed with https://github.com/DaFuqs/Spectrum/commit/2f53ff73d09c06a10814b439cc1c5d72490d139c
