### ISSUE TITLE
[Feature] Disenchanting with the Enchanter

### ISSUE THREAD

**Issue by GoldenAlpharex** [DaFuqs/Spectrum#49]
It would be nice to be able to extract enchantments from an item and transfer them to a book (without breaking the original item, to be consistent with how the Enchanter doesn't consume enchantment books), disenchanting it in the process.

It would make the enchanting setup feel even more useful than it already does, making it truly stand out.

Another interesting thing could be to allow some pigments to be used to extract only one specific enchantment from an item (could require an additional item to preserve the enchantment and move it over to a book), with certain pigments equating a certain position in the item's enchantment list (i.e., magenta for first, cyan for second, yellow for third, red for fourth, orange for fifth, light blue for sixth, blue for seventh, etc.). It'd be a massive QoL feature that doesn't exist in *most* modpacks, and that would make enchanting even less annoying.

**Comment by DaFuqs** [comment]
> It would be nice to be able to extract enchantments from an item and transfer them to a book (without breaking the original item, to be consistent with how the Enchanter doesn't consume enchantment books), disenchanting it in the process.

This is already a thing on the dev branch :)

> extract only one specific enchantment from an item

Interesting take. I can absolutely see why that might be useful. I will think of a solution how exactly. This should definitely be a thing.

**Comment by DaFuqs** [comment]
done. Albeit... a bit more tricky ;)
