### ISSUE TITLE
[BUG] Universe Spyholes placed on top of Overgrown blackslag (or other blocks who's model extends past a full block) do not see through them

### ISSUE THREAD

**Issue by f-raZ0R** [DaFuqs/Spectrum#493]
![2024-09-15_20 39 18](https://github.com/user-attachments/assets/5f8af413-f505-4d3b-a131-aeda60ec4738)
![2024-09-15_20 41 27](https://github.com/user-attachments/assets/7aff385a-ec59-4334-9161-ea9dac9c1d83)

found in a dev instance

**Comment by DaFuqs** [comment]
May be that the top texture of overgrown blackslag and similar other blocks do not have their fulling faces set properly, @Azzyypaaras ?
