### ISSUE TITLE
Crash upon viewing recipes from within pigment pedestal

### ISSUE THREAD

**Issue by Gronglegrowth** [DaFuqs/Spectrum#5]
With REI installed, clicking the recipe arrow to view valid recipes for the pigment pedestal appears to result in a game crash.

[crash-2021-12-15_10.05.02-client.txt](https://github.com/DaFuqs/Spectrum/files/7720541/crash-2021-12-15_10.05.02-client.txt)

**Comment by DaFuqs** [comment]
Ty for reporting this. Should be fixed.
