### ISSUE TITLE
[BUG] Anvil crushing without damaging it

### ISSUE THREAD

**Issue by Qendolin** [DaFuqs/Spectrum#505]
**Describe the bug**
When dropping an anvil on a block where it cannot manifest, the crushing repice is performed while the anvil drops as an item without ever taking damage.

**To Reproduce**
1. Place a bottom slab (or a sign or a pressure plate)
2. Drop a crushable item on it, eg. Amethyst shards 
3. Let an anvil fall down on it 

Result:
The item is crushed.
The anvil drops as an item.
The anvil is never damaged.

**Expected behavior**
This bug report is more of a question, if it is intended to perform crushing without damaging / using up any anvils.

IMO I like that there is a way to crush items without breaking the anvil. But from looking at the code, I am not sure if this is intentional. I think you should keep this behavior and close the issue as Won't Fix. I wanted to make you aware regardless.

**Minecraft version**
1.20.1

**Mod version**
1.7.16

**Comment by DaFuqs** [comment]
Fun fact: I was not aware at first that you could keep anvils from breaking this way myself at first!
But I agree, I kind of like the mechanic as a insider for people who know about it. ✅
There is even a hint in one of the worldgen structures about it now.
