### ISSUE TITLE
[BUG] Misleading entries in the guide book

### ISSUE THREAD

**Issue by GoldenAlpharex** [DaFuqs/Spectrum#51]
**Describe the bug**
The Azure Dike trinkets are described as providing one less point than they actually provide, in the guide, which is likely an oversight.

**To Reproduce**
Open the book, go to the Azure Dike page, read the numbers, then hover over the items and realize that the description says 4, while the text says 3, for the ring, and 6, whereas the text says like 4, for the belt. 

**Expected behavior**
For the numbers to match their real value, it's just a tiny inconsistency.

**Mod version**
`spectrum-1.2.13-1.18.1-midgame14-trinkets-brewing`

**Comment by DaFuqs** [comment]
Oh yeah. I buffed them a bit, changed the values and tooltips, but seem to have forgotten the guidebook entries. Ty!

**Comment by DaFuqs** [comment]
fixed.
