### ISSUE TITLE
[BUG] Crash after Deeper Down

### ISSUE THREAD

**Issue by nick-zh** [DaFuqs/Spectrum#513]
**Describe the bug**
First: Thank you so much for this awesome mod, I have played it many times and it's awesome how it progresses and how it grew over time!
I really loved discovering the deeper down yesterday 🤩 
My MC server wont start anymore. The stack suggests it might be related to Spectrum.

**To Reproduce**
I am not sure, I went to the deeper down yesterday, explored and flew around.

**Minecraft version**
All of Fabric 7: 2.5.2
Minecraft: 1.20.1
Fabric: 0.16.0

**Mod version**
1.7.16

**Crash Report**
This is what i found in the log: [mc-log.txt](https://github.com/user-attachments/files/17289096/mc-log.txt)
I checked all the issues and ony found [this](https://github.com/DaFuqs/Spectrum/issues/291) that seems related, but that's an old one 😅 
Let me know if I can provide anything else 🙏

**Comment by Gronglegrowth** [comment]
That looks like a corrupted Create config, and not a Spectrum problem?

**Comment by nick-zh** [comment]
Might be, i checked the trace but it seems to me the other mods mentioned are more helper / porting libs, also the only thing I did before the crash was progressing in Spectrum, I haven't even started with the create mod. I was trying to find out more, but just with that short trace I didn't find anything useful 😢 
I checked the other repos for `ConcurrentModificationException` but did not find anything. I am not really versed with MC debugging tbh though 😅

**Comment by DaFuqs** [comment]
Happy to read you enjoy the mod!

Can you upload your whole latest.log, please?
Usually that had the full info about what happened.

**Comment by nick-zh** [comment]
Sure thing and thx again for all the work on this mod 🚀 
[latest.log](https://github.com/user-attachments/files/17289252/latest.log)

**Comment by Gronglegrowth** [comment]
That is indeed a corrupted config preventing the server from starting. Delete the Hephaestus configs from the server and let them regenerate?

That this can happen is very annoying,,,

**Comment by nick-zh** [comment]
Many thanks for the feedback 🙇‍♂️ 
1. Can you tell me how you saw this, so the next time I don't bother the wrong people?
2. Anything I can do to avoid this in the future?
3. Also can you tell me roughly in which path that file is? Search on the FS on my hoster is quite limited 😅 

Many thanks to both of you for the fast replies, really appreciate it 🙏

**Comment by DaFuqs** [comment]
Like 1551 in the log mentions
`[06:21:38] [Thread-3/WARN]: Configuration file ./config/tconstruct-common.toml is not correct. Correcting`, which is one of the last log entries before the failure with `Failed to start the minecraft server - java.util.ConcurrentModificationException: null`. Between that log entry mentioning the file and the crash there are only errors about the file bing corrupted (or outdated, maybe?). Hephaestus is the Fabric port of Tinkers, hence the config file being named that.

You can find the file in your mc servers install folder in the subfolder `/config/`

**Comment by Gronglegrowth** [comment]
You *may* be able to add [this mod here](https://modrinth.com/mod/night-config-fixes) to avoid the problem in the future. I tended to simply deal with it though.

The config you're looking for is specifically `tconstruct-common.toml`, I think.

**Comment by nick-zh** [comment]
That did the trick, many thanks again to both of you for the help and all the explanations. You saved my MC game time tonight ❤️ 
Wish you both an awesome day 💪

**Comment by DaFuqs** [comment]
Happy to help. Enjoy your gaming session!

Also godspeed, Grongle
