### ISSUE TITLE
[BUG] Midnight Solution causing copies of music disk 13 to replicate infinitely

### ISSUE THREAD

**Issue by stardrifter21** [DaFuqs/Spectrum#517]
**Describe the bug**
In cities where midnight solution has spawned in the market areas it has a possibility to break the item frames in the music disk shop, causing the disks to fall into the liquid and generate a copy of 11, this appears to continue infinitely

**To Reproduce**
Could probably put a music disk into midnight solution but traveling to a deep dark city with said generation appears to do the trick

**Expected behavior**
Music disks fall into solution and turn in 11, not duplicate in the process

**Minecraft version**
1.20.1

**Mod version**
1.7.16

**Crash Report**
It does seem to crash my game and the server that im playing on,
[crash-2024-10-10_19.02.08-client.txt](https://github.com/user-attachments/files/17347242/crash-2024-10-10_19.02.08-client.txt)

**Comment by DaFuqs** [comment]
I threw a bunch of music discs into Midnight Solution, but while they turned all into music disc 11, they did not duplicate or anything.

Do you have an idea if another mod might be interfering? Maybe changing stack sizes, or similar?

The crash log you attached does seem unrelated. It is caused by REI trying to render items in its menu.

**Comment by stardrifter21** [comment]
entirely possible it might be a mod conflict, its part of all the fabric 7 which seems to have some other stability issues along with it

**Comment by DaFuqs** [comment]
I launched the newest AoF7, gave myself all the advancements, went to the DD and dropped music discs into Midnight Solution. They did not duplicate.

Are you sure it really were lots of duplicated music discs, or just a lot of item entities of various sorts?

**Comment by stardrifter21** [comment]
Ive got about 300 copies of 11 in my storage system, and ive seen it occur twice in seperate cities but only with that item so im fairly confident that its specific to the music disk, im not sure if its a structure generation bug where it tries to fill the item frames with disks

**Comment by Noaaan** [comment]
We will see if this issue reoccurs, as with the recent changes lakes in general should spawn less frequently (or not at all) inside cities
