### ISSUE TITLE
[BUG] Cannot make clotted cream

### ISSUE THREAD

**Issue by TeaJeep** [DaFuqs/Spectrum#518]
Trying to seal a titration barrel containing milk and 4 sugar does not work. Additionally, the recipe book does not show milk in the recipe.  Trying without milk also does not work.

**Minecraft version**
1.20.1 Fabric

**Mod version**
Spectrum 1.8.0-alpha3

I believe it may be related to this previous (now closed) issue:
https://github.com/DaFuqs/Spectrum/issues/375

I have both Create and Bumblezone installed, but not sure if it is on their end.

**Comment by DaFuqs** [comment]
Does it mysteriously start working when you quit the world and rejoin? Cause in this case it will be fixed in alpha4
EDIT: Ah, disregard that. Got it!
