### ISSUE TITLE
[BUG] fails to load modpack with spectrum-1.3.0-1.18.2-midgame15-trinkets-brewing

### ISSUE THREAD

**Issue by TheRanker** [DaFuqs/Spectrum#52]
**Describe the bug**
[latest.log](https://github.com/DaFuqs/Spectrum/files/8466306/latest.log)

failed mixing
**To Reproduce**
load mod up on 1.18.2 fabric
**Expected behavior**
shouldnt crash

**Mod version**
spectrum-1.3.0-1.18.2-midgame15-trinkets-brewing

**Screenshots**

**Crash Report**
no crash.. lastest .log in dexscript bug section

**Comment by Alec153** [comment]
Discussed to be caused by arcanus in the discord. Daf is looking for a fix

**Comment by DaFuqs** [comment]
Fixed in newest version.
