### ISSUE TITLE
[BUG] Quarry plus mod crashes game if radiating ender is mined

### ISSUE THREAD

**Issue by WinterPhoenix-602** [DaFuqs/Spectrum#522]
**Describe the bug**
When using the chunk destroyer from the additional enchanted miner mod, if radiating ender is in the area to be mined the game will crash when it tries to interact.

**To Reproduce**
Steps to reproduce the behavior.
1. Find or place radiating ender in the world.
2. Place and activate a chunk destroyer with the radiating ender inside the mining area.
3. The game should crash.

**Expected behavior**
A concise description of what you expected to happen.
The block should just be mined like any other.

**Minecraft version**
1.20.1

**Mod version**
Which version of the mod are you currently using?
1.8.0-alpha3

**Crash Report**
[crash-2024-10-18_16.33.47-server.txt](https://github.com/user-attachments/files/17441654/crash-2024-10-18_16.33.47-server.txt)

**Comment by Robotgiggle** [comment]
This is already fixed in dev.
![image](https://github.com/user-attachments/assets/53c02f53-4160-48f3-83e0-62b968c12cbf)
