### ISSUE TITLE
[BUG] Item textures displaying incorrectly for weapons with unique models

### ISSUE THREAD

**Issue by anarchyarcheval** [DaFuqs/Spectrum#533]
**Describe the bug**
Weapons that have custom models of which differ from their inventory sprites (draconic twin sword, glass great sword, nectar lance, etc) are failing to display properly and are defaulting to their inventory versions, just at the size the models would supposedly be.

Any help resolving this visual bug would be greatly appreciated!

**To Reproduce**
Linked here (https://drive.google.com/file/d/1Mj3dGQs2bllZooxX3OzimfyNk4xHU5z0/view?usp=sharing) is the mrpack file for the modpack i use this version with, however note i have tried updating, downgrading, and deleting mods that affect model sprites (notably cit resewn, vanity, and model gap fix) and have achieved nothing.

**Expected behavior**
In previous versions of spectrum ive played, these weapons have sprites that are more complex and display correctly in the player model hand.

**Minecraft version**
1.20.1 minecraft, fabric version 0.16.7

**Mod version**
1.8.0 alpha 4

**Screenshots**
![2024-10-27_20 03 06](https://github.com/user-attachments/assets/c580de86-7fcd-4353-a9af-6e852378dbf6)
![2024-10-27_20 02 59](https://github.com/user-attachments/assets/610703c2-b005-4812-9a41-b74b95b53977)
![2024-10-27_20 03 01](https://github.com/user-attachments/assets/f85fb3a3-1135-4c57-91b6-aad8ec30c546)
![2024-10-27_20 03 02](https://github.com/user-attachments/assets/0941bcd9-2f68-4935-bbb9-2902b4bbe066)
![2024-10-27_20 03 04](https://github.com/user-attachments/assets/23ccd73c-974b-4753-8e88-69cb598d5bed)

**Crash Report**
If it is a crash bug add your crash log here [N/A]

**Comment by Noaaan** [comment]
Already fixed in latest dev
