### ISSUE TITLE
[BUG] Preservation buildings seem to generate too frequently

### ISSUE THREAD

**Issue by ori-sky** [DaFuqs/Spectrum#56]
**Describe the bug**
From a fresh mod install, preservation stone buildings appear to be generating at a frequency far greater than I would imagine to be intentional.

**To Reproduce**
Generate a new world and explore around.

**Expected behavior**
I would expect the structures to occur far less frequently or for there to be a configuration option to change this frequency (I looked for one although couldn't find anything that looked like it).

**Mod version**
v1.3.2-1.18.2-midgame17-trinkets-brewing

**Screenshots**
![image](https://user-images.githubusercontent.com/4142775/164339761-bcca17aa-fbe2-4b04-bda8-cabc9a8c8fe0.png)

**Comment by DaFuqs** [comment]
fixed in newest release.
