### ISSUE TITLE
[BUG] Glass arrows are worse underwater than vanilla arrows

### ISSUE THREAD

**Issue by Robotgiggle** [DaFuqs/Spectrum#565]
**Describe the bug**
The guidebook claims that Glass Arrows "can be fired underwater", which presumably implies that they fly better underwater than vanilla arrows. However, the opposite is true - Glass Arrows fired underwater are slowed down even more than vanilla arrows. This applies no matter what type of bow is used.

**To Reproduce**
1. Shoot a vanilla arrow underwater
2. Shoot a Glass Arrow at the same angle
3. Observe that the vanilla arrow flies much further

**Expected behavior**
Either Glass Arrows should actually fly further underwater, or the book should stop suggesting that they do

**Minecraft version**
1.20.1

**Mod version**
1.8

**Screenshots**
Both arrows were shot with a vanilla bow from the position of the armor stand, facing straight forward
![image](https://github.com/user-attachments/assets/ea8bb056-d225-4e54-a5ef-fb088e62aa5b)

**Comment by DaFuqs** [comment]
Fixed in https://github.com/DaFuqs/Spectrum/commit/1cf8c90afd5106b51c1204df5b571753d0f5730e
