### ISSUE TITLE
[BUG] Glass arrows missed target after immediately pass through a transparent block 

### ISSUE THREAD

**Issue by EndlessLeo** [DaFuqs/Spectrum#566]
**Describe the bug**
When aiming at a target right next to a transparent block (or even 4 blocks away) with glass arrows, the glass arrow passes through both the transparent blocks and the target.

**To Reproduce**
Set up a platform with a glass wall, and place a mob at one side of the glass wall, about 3-4 blocks away. Stand at the other side of the glass wall, and shoot the mob with any glass arrow.

**Expected behavior**
Mob gets hurt by glass arrow

**Minecraft version**
1.20.1

**Mod version**
1.8.0

**Screenshots**
![image](https://github.com/user-attachments/assets/21cd5e96-7dea-4b2f-a08a-2e9b9d8d3b2b)

**Comment by DaFuqs** [comment]
I tried to improve that for an hour now, but in the end it all boils down that you can't make entities conditionally pierce some blocks and not others. Big sad. Sorry. I will update the guidebook entry accordingly.
