### ISSUE TITLE
[BUG] Unable to Retrieve Dragon Talon 

### ISSUE THREAD

**Issue by EndlessLeo** [DaFuqs/Spectrum#568]
**Describe the bug**
Dragon talon sometimes cannot be retrieved and starts flying to the player infinitely from where it lands

**To Reproduce**
Put a dragon talon on the left hand and toss it to an Enderman and you can reproduce it statically. Hitting a moving mob may also cause this.

**Expected behavior**
Dragon talon retrieved to player's inventory

**Minecraft version**
1.20.1

**Mod version**
1.8.0

**Screenshots**
![image](https://github.com/user-attachments/assets/b2bd9f9f-d090-47d4-bb8a-03ffe6cf1b85)

**Comment by EndlessLeo** [comment]
https://discord.com/channels/906264467636109333/911958718067929118/1305699663357284443
Thank Athebyne recorded a video for it

**Comment by DaFuqs** [comment]
I could preproduce that 100% consistently by throwing it at an enderman

**Comment by DaFuqs** [comment]
The `hasDealtDamage` flag gets set after hitting Endermen. But Endermen should not get hit by projectiles at at all.
So a bug causing another bug
