### ISSUE TITLE
[BUG] Erasers are not count as mobs in mobcap.So staying too long in Deeper Down will make server MSPT grow for there are thousands of Erasers.

### ISSUE THREAD

**Issue by Ethanolgie** [DaFuqs/Spectrum#569]
**Describe the bug**
AFK in deeper down and lots of Eraser kept spawning.

**To Reproduce**
Stay in deeper down,not move to far.

**Expected behavior**
Count Erasers as mobs in mobcap,and when reached mobcap,Erasers will spawn much less.
**Minecraft version**
1.20.1

**Mod version**
1.8.0

**Screenshots**
Sorry I didn't shot one

**Crash Report**
Game not crashed,but TPS is less than 10.0

**Comment by DaFuqs** [comment]
Sadly I could not reproduce your issue.
I teleported to a Black Langast, spawned 200 erasers, switched to survival, but not a single additional one did spawn after that.
Mod conflict, maybe?

**Comment by Ethanolgie** [comment]
I'm so sorry,I found that I can't reproduce in another server.

**Comment by DaFuqs** [comment]
Weird. But thank you for trying again. If you notice it happening again lmk!
