### ISSUE TITLE
[BUG] Conflict with Combat Enchantments

### ISSUE THREAD

**Issue by Happy1speed** [DaFuqs/Spectrum#584]
**Describe the bug**
Mixin conflict with Combat Enchantments and Spectrum 1.8.0 (Fabric 1.20.1)

**To Reproduce**
Get Combat Enchantments 2.14.9 and Spectrum 1.8.0 on Fabric 1.20.1.

**Expected behavior**
No crash

**Minecraft version**
1.20.1

**Mod version**
1.8.0 release

**Screenshots**
None

**Crash Report**
[crashlog.txt](https://github.com/user-attachments/files/17810203/crashlog.txt)

**Comment by DaFuqs** [comment]
> InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1309::spectrum$preventStatusClear with priority 1000 cannot inject into net/minecraft/class_1309::method_6012()Z merged by com.dsfhdshdjtsb.CombatEnchants.mixin.CenchantsLivingEntityMixin with priority 1000 [INJECT_PREPARE Applicator Phase -> spectrum.mixins.json:compat.quilt_status_effect.absent.LivingEntityPreventStatusClearMixin from mod spectrum

Looking at their code, Combat Enchantments really does use an Override, causing it's transformation to conflict with everything else that touches this piece of code:

https://github.com/dsfhdshdjtsb/enchantments/blob/aecd7d4a26cfd90a49c0d6c2257068569cec7712/src/main/java/com/dsfhdshdjtsb/CombatEnchants/mixin/CenchantsLivingEntityMixin.java#L259-L261

That one will have to be fixed on their end.

**Comment by DaFuqs** [comment]
I created them an issue. Ty!
