### ISSUE TITLE
[BUG] Conflict with Enchancement mod

### ISSUE THREAD

**Issue by Happy1speed** [DaFuqs/Spectrum#585]
**Describe the bug**
Mixin conflict between Spectrum 1.8.0 and Enchancement 1.20-26

**To Reproduce**
Get Enchancement 1.20-26 and Spectrum 1.8.0. (Fabric 1.20.1)

**Expected behavior**
No crashing

**Minecraft version**
1.20.1 Fabric

**Mod version**
Spectrum 1.8.0 (1.20.1)

**Screenshots**
none

**Crash Report**
[crashlog.txt](https://github.com/user-attachments/files/17810376/crashlog.txt)

**Comment by DaFuqs** [comment]
Caused by an outdated mixin into Spectrum on Enchantments side.
Sadly Enchancement will not get updated anymore for 1.20.1, so we are out of luck.

See https://github.com/MoriyaShiine/enchancement/issues/198:
> Enchancement for 1.20 is unsupported so I suggest doing that for the time being until Spectrum updates to a new Minecraft version
