### ISSUE TITLE
[BUG] Fatal Slumber vs Immunity

### ISSUE THREAD

**Issue by Robotgiggle** [DaFuqs/Spectrum#589]
**Describe the bug**
Currently, Immunity does not work to prevent or cure Fatal Slumber. This is intended, with the reasoning that Fatal Slumber is a particularly rare and powerful effect and thus should not be easily prevented.

However, normal milk (or anything that replicates its effect, such as clotted cream) _can_ cure Fatal Slumber. In fact, doing so is part of the solution for the aether gloves puzzle in the Undergrowth Manor. It seems strange to me that milk should be able to cure Fatal Slumber, when Immunity - which is supposed to be an upgraded version of the same effect - cannot.

This is especially relevant since, when exploring the Undergrowth Manor, the player will likely have easier access to Immunity (via loot alcohol) than to normal milk, unless they happen to have brought some from the overworld. If such a player attempts the glove puzzle and sees that Immunity does not work to cure Fatal Slumber, they would have absolutely no reason to think that normal milk _would_ work, and thus they may have a very hard time figuring out how to solve the puzzle.

**Expected behavior**
I would expect that anything curable via milk should also be curable via Immunity, since Immunity is much harder to obtain and is presented as a strictly better version of milk.

**Minecraft version**
1.20.1

**Mod version**
1.8.0

**Comment by DaFuqs** [comment]
Related to https://github.com/DaFuqs/Spectrum/pull/594
Agreed.
I would assume Immunity having the same effect as drinking Milk. Having weird edge cases for certain single status effects sounds very jank.
