### ISSUE TITLE
[BUG] You can create Potion Pendants of "instant" effects which results in the effect applying every single tick

### ISSUE THREAD

**Issue by f-raZ0R** [DaFuqs/Spectrum#59]
**Describe the bug**
You can create Potion Pendants of Saturation/Instant Health/Instant Damage, which causes their effects to apply every tick.
With instant damage, you pretty much instantly die. With instant health, you pretty much become immortal. With saturation, you never need to eat. Ever again. Safe to say that this is probably unintended.

**To Reproduce**
Place a Lesser Potion Pendant inside of a Potion Workshop, and brew either saturation, instant health, or instant damage. Equip the pendant. Break the game.

**Expected behavior**
I would not be able to put "instant effects" on a potion pendant.

**Mod version**
spectrum-1.3.3-1.18.2-midgame18-trinkets-brewing

**Screenshots**
![2022-05-29_14 24 50](https://user-images.githubusercontent.com/30442287/170885846-bf68d585-c25b-4030-835c-109ffbd59483.png)
![Screenshot (653)](https://user-images.githubusercontent.com/30442287/170886081-98ff3b19-1648-48bf-8d53-b7ef41d312b0.png)

**Comment by RealSonarX** [comment]
This is known and will be fixed next version, along with Instant + Storm Stone reagents.

Saturation has also been nerfed on it's own.
