### ISSUE TITLE
[BUG] BookErrorInfo

### ISSUE THREAD

**Issue by Llyneuf** [DaFuqs/Spectrum#592]
**Describe the bug**
After installing the new spectrum 1.8.0 update in the colorful world book instead of the guide, an error pops up:
BookErrorInfo{
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:general/jades_vines'.
context='Link:
entry://creating_life/spirit_instiller,
Category: spectrum:general,
Entry: spectrum:general/jade_vines,
Page: 1',
exception='java.lang.IllegalArgumentException:
Invalid entry link, entry not found in book:
creating_life/spirit_instiller'}

(12 more errors, see log)

Logs:

[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:general/jade_vines'', 
context='Link: entry://creating_life/spirit_instiller, 
Category: spectrum:general, 
Entry: spectrum:general/jade_vines, 
Page: 1', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: creating_life/spirit_instiller'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:general/preservation_ruins'', 
context='Link: entry://equipment/trinkets/azure_dike_equipment, 
Category: spectrum:general, 
Entry: spectrum:general/preservation_ruins, 
Page: 3', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: equipment/trinkets/azure_dike_equipment'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:general/fusion_shrine'', 
context='Link: entry://decoration/gemstone_storage_blocks, 
Category: spectrum:general, 
Entry: spectrum:general/fusion_shrine, 
Page: 3', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: decoration/gemstone_storage_blocks'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:general/liquid_crystal'', 
context='Link: entry://magical_blocks/mud, 
Category: spectrum:general, 
Entry: spectrum:general/liquid_crystal, 
Page: 2', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: magical_blocks/mud'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:general/pedestal'', 
context='Link: entry://equipment/crafting_tablet, 
Category: spectrum:general, 
Entry: spectrum:general/pedestal, 
Page: 5', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: equipment/crafting_tablet'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:dimension/malachite'', 
context='Link: entry://ink/crystallarieum, 
Category: spectrum:dimension, 
Entry: spectrum:dimension/malachite, 
Page: 1', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: ink/crystallarieum'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:dimension/jadeite'', 
context='Link: entry://brewing/potion_workshop_reagents, 
Category: spectrum:dimension, 
Entry: spectrum:dimension/jadeite, 
Page: 0', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: brewing/potion_workshop_reagents'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:dimension/moonstone_cores'', 
context='Link: entry://ink/ink, 
Category: spectrum:dimension, 
Entry: spectrum:dimension/moonstone_cores, 
Page: 0', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: ink/ink'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:dimension/nephrite'', 
context='Link: entry://brewing/effects/toughness, 
Category: spectrum:dimension, 
Entry: spectrum:dimension/nephrite, 
Page: 1', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: brewing/effects/toughness'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:dimension/glass_crest_tools'', 
context='Link: entry://enchanting/enchantments/resonance, 
Category: spectrum:dimension, 
Entry: spectrum:dimension/glass_crest_tools, 
Page: 1', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: enchanting/enchantments/resonance'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:dimension/bismuth'', 
context='Link: entry://ink/crystallarieum, 
Category: spectrum:dimension, 
Entry: spectrum:dimension/bismuth, 
Page: 1', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: ink/crystallarieum'
}
[02:08:58] [Render thread/WARN]: BookErrorManager.error() called for book: spectrum:guidebook with error: BookErrorInfo{ 
errorMessage='Failed to render markdown in book 'spectrum:guidebook' for entry 'spectrum:dimension/malachite_tools'', 
context='Link: entry://equipment/tools_and_armor/multitool, 
Category: spectrum:dimension, 
Entry: spectrum:dimension/malachite_tools, 
Page: 1', 
exception='java.lang.IllegalArgumentException: Invalid entry link, entry not found in book: equipment/tools_and_armor/multitool'

**Minecraft version**
1.20.1

**Mod version**
1.8.0

**Fabric version**
0.16.9

![javaw_nrYK4ogNQF](https://github.com/user-attachments/assets/e5840bee-481f-4166-a2d1-bb87840c13e0)
[latest.log](https://github.com/user-attachments/files/17837854/latest.log)

**Comment by DaFuqs** [comment]
Thank you for the detailed logs!
Can you update Modonomicon to 1.77.3 and see if that solves the issue, please?

**Comment by Llyneuf** [comment]
It worked, thanks a lot

**Comment by DaFuqs** [comment]
No prob, have fun!
I will make sure to check for that on startup
