### ISSUE TITLE
[BUG] 1.8.0 via connector crashes with Alloy Forgery due to Exclusionslib

### ISSUE THREAD

**Issue by Xplodin** [DaFuqs/Spectrum#593]
**Describe the bug**
crash
**To Reproduce**
Steps to reproduce the behavior.
Install spectrum, its dependencies, and alloy forgery + mythic metals.
**Expected behavior**
A concise description of what you expected to happen.
no crash
**Minecraft version**
Which version of Minecraft are you currently using?
1.20.1
**Mod version**
Which version of the mod are you currently using?
1.8.0
**Screenshots**

**Crash Report**
If it is a crash bug add your crash log here
https://gist.github.com/Xplodin/73959777c2d01b52e34189efd5f5160f

I believe this is related to exclusionslib but am unsure about where to post this honestly due to Spectrum using this library, and alloy forgery not

**Comment by f-raZ0R** [comment]
Downgrade exclusions-lib to 0.6, 1.0.2 currently crashes with connector

**Comment by DaFuqs** [comment]
Is there a way to make exclusion lib optional until the crash with connector is resolved?
