### ISSUE TITLE
[BUG]Playing with Wizard's Reborn Arcane Staff causes a crash

### ISSUE THREAD

**Issue by sybsysj** [DaFuqs/Spectrum#595]
**Describe the bug**
crash

**To Reproduce**
Install spectrum, its dependencies,wizards reborn and fluffy fur,hold wizard's reborn arcane wand,press V to its ui to select crystal,crash

**Expected behavior**
Currently, only this causes a crash.

**Minecraft version**
1.20.1 Forge 47.3.10

**Mod version**
spectrum 1.8.0
wizard's reborn 0.2.3
fluffy fur 0.1.4

**Screenshots**
![image](https://github.com/user-attachments/assets/d3879caa-77ff-4921-b18f-0d3a92bf593e)

**Crash Report**
[crash.zip](https://github.com/user-attachments/files/17841861/crash.zip)

**Comment by DaFuqs** [comment]
> java.lang.UnsupportedOperationException: The finalised model does not have an override list
> at mod.maxbogomol.fluffy_fur.client.model.item.CustomFinalisedModel.m_7343_(CustomFinalisedModel.java:67)
> at net.minecraft.client.renderer.entity.ItemRenderer.modifyExpressionValue$zlb000$spectrum$handleOversizedItemModels(ItemRenderer.java:542)

**Comment by DaFuqs** [comment]
https://github.com/MaxBogomol/WizardsReborn/issues/28+

Fixed on their end ✅
