### ISSUE TITLE
[BUG] Title

### ISSUE THREAD

**Issue by Ethanolgie** [DaFuqs/Spectrum#597]
**Describe the bug**
Try acending kindling,and ANY block will be set to Magma Block in 2.5%,even bedrock,Preservation Blocks,Heartbound chest and Manxi

**To Reproduce**
Use Omni-accelerator to feed Kindling with Evernectar

**Expected behavior**
Make a blacklist that Acending kindling will not destroy,just like Bottle of Ruin.

**Minecraft version**
1.20.1

**Mod version**
1.8.0

**Screenshots**
![image](https://github.com/user-attachments/assets/b771994d-5386-439d-955b-bb95e0981ea5)

**Crash Report**
Not crashed

**Comment by Robotgiggle** [comment]
This is already fixed in dev (9c8655f)

**Comment by Ethanolgie** [comment]
> This is already fixed in dev ([9c8655f](https://github.com/DaFuqs/Spectrum/commit/9c8655f570db0aed040e3291e5a9f56d29b499d6))

Oh! I didn't know that,sorry
