### ISSUE TITLE
[BUG] Can Only enchantment upgrade depth strider at enchanter

### ISSUE THREAD

**Issue by f-raZ0R** [DaFuqs/Spectrum#60]
**Describe the bug**
When first unlocked, the only enchantment that you can upgrade on the enchanter is depth strider.

**To Reproduce**
Progress to the point where you can build an enchanter. Build one, then check the REI recipes. Notice how the only one there is depth strider. 

**Expected behavior**
I would be able to upgrade every enchantment that I have unlocked the ability to craft.

**Mod version**
spectrum-1.3.3-1.18.2-midgame18-trinkets-brewing

**Screenshots**
![Screenshot (657)](https://user-images.githubusercontent.com/30442287/171060704-7a9d6104-6a9d-4efe-9496-6e76f22eec89.png)

**Comment by DaFuqs** [comment]
Related to https://github.com/KubeJS-Mods/KubeJS/issues/293

Spectrums upcoming update that will release this week will have a workaround for that.
