### ISSUE TITLE
[Feature]Could Midnight Aberration get a least retaining time ?

### ISSUE THREAD

**Issue by Ethanolgie** [DaFuqs/Spectrum#603]
For example,make Midnight Aberration can stay for 4s and then begin to tick.

**Comment by DaFuqs** [comment]
What is your use case exactly?

**Comment by Ethanolgie** [comment]
> What is your use case exactly?

to prevent sometimes it directly disapeared in too short to move to Spirit instiller.I heard that blackhole chest+nodes can solve,but I still wish it can get a least stable time.

**Comment by DaFuqs** [comment]
Ah, I see. That makes total sense.
I will think about a good solution.

**Comment by Ethanolgie** [comment]
> I will think about a good solution.

Thank you!

**Comment by DaFuqs** [comment]
Done!

Like before, it has a 20% chance of crumbling, but now only after min of 2 seconds in the players inventory.
