### ISSUE TITLE
[BUG] Weeping gala door drops nothing when I break it.

### ISSUE THREAD

**Issue by Ethanolgie** [DaFuqs/Spectrum#607]
**Describe the bug**
I broke weeping gala door with bedrock axe,but it did not drop anything.

**To Reproduce**
Break weeping gala door.

**Expected behavior**
I wish it able to drop itself.

**Minecraft version**
1.20.1

**Mod version**
1.8.0

**Screenshots**
![image](https://github.com/user-attachments/assets/92d52cfe-ec65-4745-97ea-2c57b3901f80)

**Crash Report**
Not crashed

**Comment by DaFuqs** [comment]
![image](https://github.com/user-attachments/assets/a31e1f9c-f4b9-4b3c-b005-7e652a8236bb)

Ofc, what else could have been
