### ISSUE TITLE
[BUG] Book doesn't follow my progress

### ISSUE THREAD

**Issue by w3ricardo** [DaFuqs/Spectrum#61]
When I updated to the latest version of All of Fabric 5 (1.2.3, 5/25/2022) I lost all the progress in the book. But the progress is completed in the achievements, and in the avancemenents .json file. But everything shows at not discovered yet.  I tried discovering everything again, but it doesn't work. I guess because they are marked as completed. Is there anything I can do?

![2022-05-30_19 41 32](https://user-images.githubusercontent.com/8992156/171065689-2e1f47a4-79aa-4f2d-8460-6985028ac844.jpg)

**Comment by DaFuqs** [comment]
I have seen that happen in AoF before, with Advancements failing to sync at login. Does the problem persist after you restart the instance and rejoin?

**Comment by w3ricardo** [comment]
Yes, the problem persists. But the whole Achievements windows (L) for all mods is gone. I can only see them in the quest book.

**Comment by f-raZ0R** [comment]
This was caused by a bug with Charm which erased all advancements. Spectrum progress, is done based on advancements.

**Comment by w3ricardo** [comment]
It was fixed in the latest release of the modpack. I thought it was a Spectrum problem, because the book of quests showed the quests as completed.

**Comment by DaFuqs** [comment]
The best bugs are those, that aren't :>
