### ISSUE TITLE
[BUG] Light & button dupe

### ISSUE THREAD

**Issue by LeoBeliik** [DaFuqs/Spectrum#613]
**Describe the bug**
You can use a sticky piston to dupe all shimmerstone lights and non wood buttons

**To Reproduce**

- Place a sticky piston
- Put a shimmerstone light or a non wooded button on the sticky part
- Activate the piston twice
- Observe

**Expected behavior**
The lights and buttons should break on the piston extension not contraction, like vanilla counterparts do (or don't break at all) and not dupe themselves

**Minecraft version**
1.20.1

**Mod version**
spectrum-1.8.0
trinkets-3.7.2
revelationary-1.3.9+1.20.1
modonomicon-1.20.1-fabric-1.77.3
fabric-api-0.92.2+1.20.1
exclusions_lib-1.0.2
cloth-config-11.1.136-fabric

**Screenshots**
If applicable, add screenshots to help explain your problem. *what about a video instead*

https://github.com/user-attachments/assets/d4e9fe58-3398-47b8-8b9d-f771eac596e7

**Crash Report**
no crashy

**Comment by DaFuqs** [comment]
Actually genius
