### ISSUE TITLE
[BUG] Crash when changing audio devices with Spectrum on Connector

### ISSUE THREAD

**Issue by Xplodin** [DaFuqs/Spectrum#614]
**Describe the bug**
changing audio devices will crash
**To Reproduce**
Steps to reproduce the behavior.
Install spectrum, dependencies including 0.6 version of exclusionlib
**Expected behavior**
A concise description of what you expected to happen.
no crash
**Minecraft version**
Which version of Minecraft are you currently using?
1.20.1
**Mod version**
Which version of the mod are you currently using?
1.8.0
**Screenshots**

**Crash Report**
If it is a crash bug add your crash log here
https://gist.github.com/Xplodin/03dc3306fa149d51cdb6fd44b60a260e

I havent personally replicated, but a user in my discord has

**Comment by DaFuqs** [comment]
=> [https://github.com/DaFuqs/DimensionalReverb](https://github.com/DaFuqs/DimensionalReverb)

**Comment by Xplodin** [comment]
Found out this was due to a corrupt install, as I couldnt replicate it at all
