### ISSUE TITLE
[BUG] Most crafting recipes don't show up in REI when Malum is installed

### ISSUE THREAD

**Issue by goldenapple3** [DaFuqs/Spectrum#62]
**Describe the bug**
* A lot of crafting recipes (incl. vanilla and other mods) stop showing up in REI when Spectrum and Malum are both installed.
* This seems to apply only to some categories of recipes (e.g. Automated Shaped/Shapeless Crafting and Bulk Blasting from Create always shows, which I guess is kind of a workaround, even when most workbench and furnace recipes don't work)
* Not all recipes in that category are affected but most are
* Recipes themselves still work
* this happens regardless of "hide undiscovered recipes" config setting

**Mod version**
```
architectury-4.4.68.jar
cloth-config-6.2.57-fabric.jar
malum-quilt-b1.0.6.jar
owo-lib-0.7.2+1.18.jar
Patchouli-1.18.2-69-FABRIC.jar
qsl-1.1.0-beta.14_qfapi-1.0.0-beta.17_fapi-0.54.0_mc-1.18.2.jar
RoughlyEnoughItems-8.2.471.jar
spectrum-1.4.0-1.18.2-chaos-and-exploration.jar
trinkets-3.3.1.jar
```

**Screenshots**
![rei screenshot](https://user-images.githubusercontent.com/53568168/172465362-77cd85f4-4b4c-4a49-aee1-17d456412b43.png)
Block of Copper only shows scraping recipes

I might cross-post this to the Malum Quilt repo as well because I don't know which one is to blame. Taking out one of the mods solves the issue.

**Comment by DaFuqs** [comment]
Can you attach a log please? Does this happen only on quilt, or fabric, too?

**Comment by RealRTTV** [comment]
The Malum port is only on quilt

**Comment by goldenapple3** [comment]
[latest.log](https://github.com/DaFuqs/Spectrum/files/8856635/latest.log)
Ah, right, logs are great, aren't they?

**Comment by goldenapple3** [comment]
Seriously though, spent so long bisecting this in a large modpack when I could've just taken a closer look at the logs...
https://github.com/devs-immortal/Incubus-Core/issues/5
Incubus Core breaks on Quilt so I suppose Spectrum by extension does not work either, that's a shame (though interesting that it does work without Malum)

**Comment by DaFuqs** [comment]
Incubus Concern

**Comment by Azzyypaaras** [comment]
Quilt cum

**Comment by goldenapple3** [comment]
Fixed by https://github.com/RealRTTV/malum-quilt/issues/8
