### ISSUE TITLE
[BUG] X-ray Vision Through Weeping Gala Light

### ISSUE THREAD

**Issue by EndlessLeo** [DaFuqs/Spectrum#620]
**Describe the bug**
Players have X-ray vision when seeing the edge of Weeping Gala Light, and other noxwood lights. Adding Sodium will make this X-ray vision more obvious.

**To Reproduce**
Place a Weeping Gala Light next to a block

**Expected behavior**
Seeing the surface of the block next to the light

**Minecraft version**
1.20.1

**Mod version**
1.8.0/1.8.1

**Screenshots**
Without Sodium
![image](https://github.com/user-attachments/assets/2399047d-0389-49c9-94f9-82c8ff0e1939)

With Sodium
![image](https://github.com/user-attachments/assets/cbe4457c-c944-4c25-8c26-a0f4b9c48c31)

**Comment by Robotgiggle** [comment]
This also applies to Weeping Gala Lanterns when placed on top of any wall block
![2024-11-01_14 38 57](https://github.com/user-attachments/assets/96203f8b-b49e-402c-8d9e-548691b40355)

**Comment by DaFuqs** [comment]
The lantern is a very easy fix
