### ISSUE TITLE
[BUG] SHOOTING AT KINDLING WITH FATAL SLUMBER WILL DESTROY YOUR SAVE

### ISSUE THREAD

**Issue by EndlessLeo** [DaFuqs/Spectrum#624]
**Describe the bug**
SHOOTING AT KINDLING WITH FATAL SLUMBER WILL DESTROY YOUR SAVE

**To Reproduce**
SHOOTING AT KINDLING WITH FATAL SLUMBER 

**Expected behavior**
Explode normally like what will happen in 1.8.0

**Minecraft version**
1.20.1

**Mod version**
1.8.1

**Screenshots**
It crashed

**Crash Report**
[crash-2024-12-02_01.48.07-server.txt](https://github.com/user-attachments/files/17974531/crash-2024-12-02_01.48.07-server.txt)

**Comment by imreallybadatnames** [comment]
AAAAAAAAAAAAAAAAAAAAAAA!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Robotgiggle** [comment]
Note: this is not an issue with Fatal Slumber specifically. Anything that triggers the kindling explard will brick your save.

**Comment by DaFuqs** [comment]
> AAAAAAAAAAAAAAAAAAAAAAA!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by DaFuqs** [comment]
Common Protection Api classloading issue, by not using GenericClaimModsCompat in the exclusion check.

We should also check other parts of the code. The CPAPI code should only ever be referenced by that wrapper class (make everything package private?)
