### ISSUE TITLE
[BUG] Crash when Malum are present in start up

### ISSUE THREAD

**Issue by hexqua** [DaFuqs/Spectrum#627]
**Describe the bug**
Crash when start up.
`net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'spectrum' at 'de.dafuqs.spectrum.SpectrumCommon'!`

**To Reproduce**
Install the following mods.

- Cloth Config (Forge)
- Connector Extras (Forge)
- Curios API (Forge)
- Exclusions Lib (Fabric)
- Forgified Fabric API (Forge)
- Lodestone (Forge)
- Malum (Forge)
- Modonomicon (Forge)
- Revelationary (Fabric)
- Sinytra Connector (Forge)
- Spectrum (Fabric)
- Trinkets (Fabric)

**Expected behavior**
No crash.

**Minecraft version**
- Minecraft : 1.20.1
- Forge : 47.3.12

**Mod version**
All mods is newest in today.

- Cloth Config : 11.1.136
- Connector Extras : 1.11.2+1.20.1
- Curios API : 5.11.0
- Exclusions Lib : 1.0.2
- Forgified Fabric API : 0.92.2+1.11.8+1.20.1
- Lodestone : 1.6.4.1
- Malum : 1.6.5.1
- Modonomicon : 1.77.3
- Revelationary : 1.3.9
- Sinytra Connector : 1.0.0 beta46
- Spectrum : 1.8.1
- Trinkets : 3.7.2

As for Exclusions Lib, the same crash occurs after downgrading to 0.6.

**Screenshots**
No

**Crash Report**
[crash-2024-12-04_10.46.23-client.txt](https://github.com/user-attachments/files/18001583/crash-2024-12-04_10.46.23-client.txt)

**Comment by DaFuqs** [comment]
Add "malum" to the entry "disabled mod integrations" in spectrum's config.

Since mod integrations caused quite a few issues with connector lately I will make sure to never load any in case connector is present.

**Comment by DaFuqs** [comment]
Fixed for the next update automatically. Ty!
