### ISSUE TITLE
Incompatibility with Minecraft Comes Alive

### ISSUE THREAD

**Issue by Luke100000** [DaFuqs/Spectrum#63]
From https://github.com/Luke100000/minecraft-comes-alive/issues/239

MCA uses a Mixin to inject custom translations into `TranslationStorage`.  Together with Spectrum 1.4.0 this no longer works (and the untranslated keys are shown instead).

![image](https://user-images.githubusercontent.com/64183602/172129300-84ff8b2b-9edf-4d14-96ce-9a84a9119060.png)

spectrum-1.4.0-1.18.2-chaos-and-exploration does not work, spectrum-1.3.3-1.18.2-midgame18-trinkets-brewing works fine.

Log does not provide any information (failed mixins etc).

I would like to resolve this issue, but wasn't able to find any translation/text related code at all. Any ideas?

**Comment by DaFuqs** [comment]
Looks like something converts TranslatableTexts to LiteralTexts?
While Spectrum itself does not tamper with chat text, maybe one of the libraries that I added in that Version of Spectrum may.
I will take a look at it.

**Comment by Luke100000** [comment]
Thanks for the quick response!

I tried all dependencies without Spectrum, it works. It might be indirectly.

The error happens outside the chat too, `drawCenteredText(new TranslatableText("key"))` for example fails. That means the error should be somewhere in `TranslatableText` or `TranslationStorage`.

**Comment by DaFuqs** [comment]
It get's even worse: It seems to work one time and acting up out another time?

**Comment by DaFuqs** [comment]
![image](https://user-images.githubusercontent.com/26429514/172898175-08ed80a3-7049-4930-9bf1-c552a09b8b0c.png)

In the cases, where translations do not work, the translation strings cannot be resolved. The culprit seems to lie in TranslationStorage/MixinTranslationStorage somewhere.
I am afraid that is prob. the furthest I can come, without debugging MCA directly, though.

**Comment by Luke100000** [comment]
Thanks a lot! I will debug this further and let you know once I found the issue.

**Comment by DaFuqs** [comment]
Fixed in the next version of https://github.com/devs-immortal/Incubus-Core
