### ISSUE TITLE
[BUG] some bug with reflections?

### ISSUE THREAD

**Issue by asdfghjkl403622** [DaFuqs/Spectrum#634]
**Describe the bug**
I'm not entirely sure what this bug is, I was simply told it had something to do with reflections by someone of fabricord
the server will fail to load the world, spam crash reports a few times, and then ultimately freeze to where I have to open btop and kill the java instance the server is running in

**To Reproduce**
run spectrum on a debian 12 server, not really sure what else to do since this issue does not occur on my desktop running arch for some reason

**Expected behavior**
server starts like normal

**Minecraft version**
1.20.1

**Mod version**
1.8.2

**Screenshots**

**Crash Report**
[here](https://mclo.gs/6B1etZq)

**Comment by DaFuqs** [comment]
It's the OnPrimordialFireComponent crash that was fixed but not yet released in https://github.com/DaFuqs/Spectrum/pull/632

**Comment by asdfghjkl403622** [comment]
so if I just compile the mod from source I'll have the fixes? that's great! but when is this bugfix being put in a release?

**Comment by DaFuqs** [comment]
Fixed in v1.8.3
