### ISSUE TITLE
[BUG] Most Amphoras break on any left-click

### ISSUE THREAD

**Issue by joakibj** [DaFuqs/Spectrum#639]
**Describe the bug**
Wooden Amphoras and Colored Amphoras (from Spectral Decorations) break with a single left-click. 

Other late-game Amphoras do not.

Not sure if this is a bug or working as intended/designed.

**To Reproduce**
1. Create an Oak Amphora and place it down in survival
2. Left-click it with an empty hand
3. Observe that it breaks, dropping all contents

**Expected behavior**
Amphoras breaking similar to a barrel, faster with an axe.

Can be impractical/frustrating if misclicking when redesigning base/rooms or otherwise interacting with storage.

If working as designed, an entry in the book could inform the player of this feature.

**Minecraft version**
1.20.1

**Mod version**
1.8.3

**Comment by Gronglegrowth** [comment]
Those are from Spectral Decorations, not base Spectrum, but I'm certain that is not intended.

**Comment by joakibj** [comment]
Ah yes, thank you. I'll close this and report it there
