### ISSUE TITLE
[BUG] Crash when clicking on vanilla item

### ISSUE THREAD

**Issue by GameOnne** [DaFuqs/Spectrum#650]
**Describe the bug**
Clicking on a vanilla item with EMI+JEI installed will crash the game.

**To Reproduce**
Open the Colorful World book, find an entry where a vanilla item is mentioned (for example: mud dipping four-leaf clover into a scute) and click the said item (in this case, the highlighted text mentioning the scute).

**Expected behavior**
I'm not sure what is the expected behavior in this case.

**Minecraft version**
1.20.1

**Mod version**
1.8.3

**Screenshots**
[image](https://github.com/user-attachments/assets/ab0b3746-1d99-456f-a488-71ed2389871a)

**Crash Report**
[crash-2024-12-30_03.24.17-client.txt](https://github.com/user-attachments/files/18275103/crash-2024-12-30_03.24.17-client.txt)

**Comment by DaFuqs** [comment]
That is something that needs to be fixed on Modonomicons side.
I opened KliKli an issue with all your info ✅
