### ISSUE TITLE
[Feature] Repair Mending items with Knowledge Gem

### ISSUE THREAD

**Issue by GameOnne** [DaFuqs/Spectrum#651]
To put it simply, if experience is withdrawn from the gem while an item with Mending is held, the item is repaired with that experience. This would be very helpful because then the player is able to use the experience they already have instead of having to obtain more.

**Comment by DaFuqs** [comment]
You can already do that in a way by using the Knowledge Gem in the Potion Workshop to brew Bottles o' Enchanting.
Mending is already the most powerful enchant there is in vanilla, I feel adding even utility (especially in early-midgame, when the Knowledge Gem is unlocked) would be a bit much
