### ISSUE TITLE
[BUG] Various blocks flashing blue

### ISSUE THREAD

**Issue by BrekiTomasson** [DaFuqs/Spectrum#66]
**Describe the bug**

When running `spectrum`, various blocks (sometimes all faces, sometimes just specific faces) flash regularly with a blue overlay. This affects both the blocks and the items. While this *could* be the result of an incompatibility with another mod, disabling `spectrum` while keeping all other mods intact returns Magma Blocks to their ordinary look.

Strangely enough, this also seems to affect some blocks added by mods, such as `adorn:crimson_coffee_table`, `adorn:warped_coffee_table`, `promenade:dark_amaranth_stem` and `promenade:dark_amaranth_hyphae`

**To Reproduce**

Start Minecraft running `spectrum` and look at any of the following blocks:

- Magma Block
- Crimson Stem
- Warped Stem

**Expected behavior**

I expect these blocks/items not to be flashing blue... :) 

**Mod version**

`spectrum-1.4.1-1.18.2-chaos_and_exploration.jar`

**Screenshots**

<img width="2545" alt="image" src="https://user-images.githubusercontent.com/7026735/174124982-8b73a61a-a531-4fb9-ae81-bc1f03839ae3.png">

<img width="2550" alt="image" src="https://user-images.githubusercontent.com/7026735/174126247-d6293191-4bf9-4e1a-8e40-18a270bbecf3.png">

**Comment by Fourmisain** [comment]
Happens only in combination with [thorium](https://www.curseforge.com/minecraft/mc-mods/thorium).
Most likely a conflict with their fix for [MC-144761](https://bugs.mojang.com/browse/MC-144761).

**Comment by Fourmisain** [comment]
Btw, [MC-144761](https://bugs.mojang.com/browse/MC-144761) is now fixed in 23w33a!
