### ISSUE TITLE
Archive crash when updating from 1.3.3 to 1.4.x

### ISSUE THREAD

**Issue by Alvin-YS** [DaFuqs/Spectrum#70]
**Describe the bug**
Serious issue of save crash when server mods are updated from 1.3.3 to 1.4.x

**To Reproduce**
Updated the original 1.3.3 version in the server mod pack to 1.4.x version

**Expected behavior**
I hope this problem can be solved quickly and perfectly! Because this bug has brought us a serious problem of corrupted archives

**Mod version**
1.3.3->1.4.1

**Screenshots**
[![jiT50e.png](https://s1.ax1x.com/2022/06/24/jiT50e.png)](https://imgtu.com/i/jiT50e)

**Crash Report**
We found this bug through testing

**Comment by DaFuqs** [comment]
That looksk like an ID mismatch. Do both client and server use 1.4.1? I probably renamed this specific entry from 1.4.0 => 1.4.1 (can check later)
