### ISSUE TITLE
[Feature] reward for going the extra mile

### ISSUE THREAD

**Issue by yoopgim** [DaFuqs/Spectrum#72]
Maybe there could be a reward for completing the mod without using any of the hints THEN using the resources and time to unlock the hints after? Its a stupid idea but I think the mad lads and completionists would be happy, not saying you have to add it of course bc its kinda useless but hey, i cant think of a saying to put here

**Comment by DaFuqs** [comment]
yes, why not. 👌

**Comment by DaFuqs** [comment]
Better: these unlock automatically when the player get's to that stage.
