### ISSUE TITLE
a few minor tweaks

### ISSUE THREAD

**Issue by yoopgim** [DaFuqs/Spectrum#73]
I noticed a few things that. while relatively minor, kind of ruin immersion slightly (and I wasn't quite sure whether to put it under bugs or feature suggestions as it is somewhere in between)

only shards and buds activate the first progression advancement, while blocks do not
4 leaf clovers drop regular clovers when supporting block is removed
some text below pictures in the guide book could be moved to the side for better effect, gui friendlyness, and mabye room for captions.

I dont claim to know anything about your ability developer-wise and i will respect whatever you do as a creator of such an interesting mod

**Comment by DaFuqs** [comment]
> only shards and buds activate the first progression advancement, while blocks do not

Done

> 4 leaf clovers drop regular clovers when supporting block is removed

That is sadly unfixable, since the block cannot know in this position who harvested the block underneath, sorry

> some text below pictures in the guide book could be moved to the side for better effect, gui friendlyness, and mabye room for captions.

Will gladly change that, sure! Which ones are you thinking of?
