### ISSUE TITLE
[Feature] Tech Reborn Integration?

### ISSUE THREAD

**Issue by BrekiTomasson** [DaFuqs/Spectrum#76]
I think several of the Anvil Crushing recipes would make sense if they could be done via the "Grinder" blocks made available through Tech Reborn. If nothing else, then at least the gemstones to gemstone powder make sense to me.

**Comment by DaFuqs** [comment]
definitely

**Comment by Technici4n** [comment]
What about MI compat recipes? 😋

**Comment by DaFuqs** [comment]
That is pretty much one of the reasons why I wanted to play with MI on the AoF server. 😋
I have no idea about MI at all currently and therefore am wary of adding stuff I do not fully understand, but I am happy for all kinds of suggestions

**Comment by Technici4n** [comment]
Ok that's great. I'm going to play with Spectrum one day and make suggestions then. ^^

**Comment by DaFuqs** [comment]
done.
