### ISSUE TITLE
[BUG] Dike Gate block can't be destroyed when wearing Azure Dike trinkets

### ISSUE THREAD

**Issue by Jenny77** [DaFuqs/Spectrum#77]
Once I tried if Azure Dike trinkets can enable a player to go through a Dike Gate block,and I put that block in a wrong place. Though I succeeded in going through the block,I found that I couldn't destroy those blocks,even in Creative Mode.
Is that a bug or an intentional feature?

**Comment by DaFuqs** [comment]
It did not come to my mind that people played around with those blocks much in creative. I agree, a easier way to interact with outside of /setblock would be nice.

**Comment by DaFuqs** [comment]
Improved via 20917c43a46d10ab76607587ce1bf65c2142f579
