### ISSUE TITLE
Archive crash caused by RandomTick

### ISSUE THREAD

**Issue by Alvin-YS** [DaFuqs/Spectrum#78]
I'm back! I'm sorry to bother you again, but we really need to fix this bug
The following is the log generated by the game crash

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2022/7/3 上午11:46
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at java.util.Objects.requireNonNull(Objects.java:208)
	at java.util.ImmutableCollections$SetN.contains(ImmutableCollections.java:937)
	at net.minecraft.util.registry.RegistryEntry$Reference.isIn(RegistryEntry:176)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.isIn(AbstractBlock:984)
	at de.dafuqs.spectrum.blocks.decay.DecayBlock.tryConvert(DecayBlock.java:106)
	at de.dafuqs.spectrum.blocks.decay.DecayBlock.randomTick(DecayBlock.java:86)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.randomTick(AbstractBlock:923)
	at net.minecraft.server.world.ServerWorld.redirect$cka000$redirectBlockStateTick(ServerWorld:7671)
	at net.minecraft.server.world.ServerWorld.tickChunk(ServerWorld:486)
	at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager:378)
	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager:322)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:311)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.ImmutableCollections$SetN.contains(ImmutableCollections.java:937)
	at net.minecraft.class_6880$class_6883.method_40220(class_6880.java:176)
	at net.minecraft.class_4970$class_4971.method_26164(class_4970.java:984)
	at de.dafuqs.spectrum.blocks.decay.DecayBlock.tryConvert(DecayBlock.java:106)
	at de.dafuqs.spectrum.blocks.decay.DecayBlock.method_9514(DecayBlock.java:86)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:923)
	at net.minecraft.class_3218.redirect$cka000$redirectBlockStateTick(class_3218.java:7671)
	at net.minecraft.class_3218.method_18203(class_3218.java:486)
	at net.minecraft.class_3215.method_14161(class_3215.java:378)
	at net.minecraft.class_3215.method_12127(class_3215.java:322)
	at net.minecraft.class_3218.method_18765(class_3218.java:311)

-- Affected level --
Details:
	All players: 1 total; [class_3222['ShengEr_Alvin'/226, l='ServerLevel[world]', x=-460.51, y=72.00, z=-596.34]]
	Chunk stats: 5852
	Level dimension: minecraft:overworld
	Level spawn location: World: (74,69,-172), Section: (at 10,5,4 in 4,4,-11; chunk contains blocks 64,-64,-176 to 79,319,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 464809587 game time, 12593560 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 134372 (now: false), thunder time: 8166 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 18.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3002012104 bytes (2862 MiB) / 6928990208 bytes (6608 MiB) up to 6979321856 bytes (6656 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f99
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1640
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9ba4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8853
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23675.80
	Virtual memory used (MB): 20714.40
	Swap memory total (MB): 7424.00
	Swap memory used (MB): 59.28
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx6652m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		adorn: Adorn 3.5.0+1.18.2
		advancementplaques: Advancement Plaques 1.4.4
		ae2: Applied Energistics 2 11.0.0
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.4.68
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 3.0.0+0
		better_runtime_resource_pack: Better Runtime Resource Pack 0.6.2
			advanced_runtime_resource_pack: Advanced Runtime Resource Pack 0.6.2
		betterpingdisplay: Better Ping Display 1.1.1
		botania: Botania 1.18.2-434-FABRIC
			fiber: fiber 0.23.0-2
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		chipped: Chipped 1.2
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		computercraft: CC: Restitched 1.100.6
			cloth-utils-v1: Cloth Utils v1 2.0.54
			com_electronwill_night-config_core: core 3.6.3
			com_electronwill_night-config_toml: toml 3.6.3
		create: Create mc1.18.2_v0.4.1+637
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 1.18-0.7.0.26
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.0
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			noindium: No Indium? 1.0.1+1.18.2
				omega-config: OmegaConfig 1.2.3-1.18.1
			porting_lib: Porting Lib 1.1.317-beta+1.18.2-dev.7ad1f24
				com_github_llamalad7_mixinextras: MixinExtras 0.0.10
				mm: Manningham Mills 2.3
				serialization_hooks: Serialization Hooks 0.2.0+1.18.f5d4aa6
			registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
		createaddition: Create Crafts & Additions ${version}
			team_reborn_energy: Energy 2.2.0
		creativecore: CreativeCore (Fabric) 2.6.12
		croptopia: Croptopia 2.0.5
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		extshape: Extended Block Shapes 1.5.1
		fabric: Fabric API 0.56.1+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.5+22138a0260
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+e747827960
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.1+0ca3bd2b60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricgc: Fabric GC 1.0.3
		fabricloader: Fabric Loader 0.14.8
		fatxporbs: Fat Experience Orbs 2.0.0
		held-item-info: Held Item Info 1.2.0
		highlighter: Highlighter 1.1.2
		iceberg: Iceberg 1.0.38
		indium: Indium 1.0.3+mc1.18.2
		indrev: Industrial Revolution 1.14.0-BETA
			libblockattributes_core: LibBlockAttributes (Core) 0.10.0
			libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
			libblockattributes_items: LibBlockAttributes (Items) 0.10.0
			libgui: LibGui 5.3.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			magna: Magna 1.7.0-1.18-pre1
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.5.0
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		itemphysiclite: ItemPhysic Lite (Fabric) 1.5.0
		jade: Jade 5.99.5
		java: Java HotSpot(TM) 64-Bit Server VM 18
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		legendarytooltips: Legendary Tooltips 1.2.4
		lithium: Lithium 0.7.10
		majobroom: Majo's Broom 1.3
		malilib: MaLiLib 0.12.1
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.2.2
		mtr: Minecraft Transit Railway 1.18.2-3.0.1
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		owo: oωo 0.7.2+1.18
		patchouli: Patchouli 1.18.2-69-FABRIC
		phosphor: Phosphor 0.8.1
		presencefootsteps: Presence Footsteps 1.5.0
			kirin: Kirin UI 1.10.0
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		roughlyenoughitems: Roughly Enough Items 8.2.470
		skinlayers: 3d Skin Layers 1.4.6-mc1.18.2
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.4+mc1.18.2-build.39
			caffeineconfig: CaffeineConfig 1.1.0
		spectrum: Spectrum 1.4.2-1.18.2-chaos_and_exploration
			additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
			bannerpp: Banner++ 2.0.6-teb.1+mc.1.18.2
			incubus_core: Incubus Core 1.7-rc.4
			satin: Satin 1.7.2
		techreborn: Tech Reborn 5.2.0
			reborncore: Reborn Core 5.2.0
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		tpshud: TPS Hud 1.2-SNAPSHOT
			me_obsilabor_alert: alert 1.0.4
		trinkets: Trinkets 3.3.1
			cardinal-components-base: Cardinal Components API (base) 4.1.3
			cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		wildfire_gender: Wildfire's Female Gender Mod 2.9
		xaerominimap: Xaero's Minimap 22.9.3
		xaeroworldmap: Xaero's World Map 1.23.3
		zyfdroid-myessentialx: MyEssentialX 1.0.4
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['ShengEr_Alvin'/226, l='ServerLevel[world]', x=-460.51, y=72.00, z=-596.34]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	Suspected Mods: Spectrum (spectrum), Minecraft (minecraft)

**Comment by DaFuqs** [comment]
Sounds like something is messing with object load order. I think I can fix that...

**Comment by DaFuqs** [comment]
Did it happen after updating spectrum / adding another mod?

**Comment by Alvin-YS** [comment]
Version 1.3.3 works perfectly on our server, but when we updated to version 1.4.2, he had this problem after entering the game for a while
