### ISSUE TITLE
[BUG] Game crashed while adding items into item bowls

### ISSUE THREAD

**Issue by Wudji** [DaFuqs/Spectrum#8]
**Describe the bug**
see title

**To Reproduce**
see title

**Expected behavior**
-

**Screenshots**
-
[crash-2021-12-19_13.06.55-server.txt](https://github.com/DaFuqs/Spectrum/files/7740344/crash-2021-12-19_13.06.55-server.txt)
the world cannot be loaded now :(

**Comment by DaFuqs** [comment]
The Enchanter is still very much WIP, at least 2 of the 3 ways of working. Seems you found the second one, congratulations! (one of the main reasons survival has an artificial lock shortly before it).

But honestly, sorry about that. An updated version tomorrow will both resolve that crash an add functionality for the Enchanter.

**Comment by DaFuqs** [comment]
Resolved with 1.1.3
