### ISSUE TITLE
[Feature] Stripped stained log variants needed

### ISSUE THREAD

**Issue by Jenny77** [DaFuqs/Spectrum#80]
As a tester of this mod and a dedicated builder,I found that all kinds of these stained wood have their logs,leaves,planks,pressure plates,fences,fence gates,plank stairs and button variants,but there's no stripped log variants.
Since there are stripped log variants of vanilla logs,why not make them?

**Comment by DaFuqs** [comment]
The single one real reason why is time, actually. Our texture artist is pretty busy with other textures already, so there never was time. If anyone can come up with nice ones I will happily add them.

Leaving it open for reference.

**Comment by Jenny77** [comment]
Don't worry! I will be the one who adds those textures!

**Comment by DaFuqs** [comment]
Sure! Feel free to talk to @Azazelthedemonlord about any non-programmer art textures before.

**Comment by Azzyypaaras** [comment]
hmmm. Very well.

Join the Serpent King, as famileee

Togetha, we shall devour the very gods!

**Comment by SollyW** [comment]
Azzy, have you forgotten some medication?

**Comment by Jenny77** [comment]
And excuse me? I'm an exorist,freed two lost souls,tried to exorise my dad (well,that's so difficult though,but I'm sure I successfully made him less crazy and found the reason of why he had been possessed) and wanted to beat Satan on my college entrance exam! Though I'm not completely Christian,but I'm a Taoist!
(Sorry everyone,if you hate those stuff above,forget that tangent)
Anyways,if you don't care about our identities,I will be very happy to work with you!

**Comment by Jenny77** [comment]
Sorry for I'm too excited to write correctly.

**Comment by Jenny77** [comment]
Well,Azazel. I know that adding a bunch of textures of those stained stripped logs is pretty easy,and you can make original textures of them,as well as I make their Programmer Art variant.

**Comment by DaFuqs** [comment]
This is now a thing in the alpha builds.
