### ISSUE TITLE
[BUG] Build script is not in kootlin

### ISSUE THREAD

**Issue by SollyW** [DaFuqs/Spectrum#81]
**Describe the bug**
Build script is written in groovy. Build script is not written in kootlin. Sad.

**To Reproduce**
kootlin

**Expected behavior**
kootlin

**Mod version**
kootlin

**Screenshots**
kootlin.png

**Crash Report**
kootlin.log

**Comment by DaFuqs** [comment]
Implemented via No 👌❤✔
