### ISSUE TITLE
[Feature (Maybe bug idk)] Enforce a max height for Geodes to spawn at

### ISSUE THREAD

**Issue by Fnige** [DaFuqs/Spectrum#82]
![image](https://user-images.githubusercontent.com/35159947/177685068-54ac1cea-feb1-4d79-97d0-ef39ea5520ad.png)
I think this shows it nicely!

Making it spawn below y=50 would be nice that way something like this doesnt happen

**Comment by DaFuqs** [comment]
You can adjust the generation height of the geodes via Spectrums config. Just keep in mind to adjust the descriptions in the guidebook accordingly.
Depending on the world generator you use, these values can take a little tweaking in general (like if you have a lof of mountains decrease topaz generation chances a bit)
