### ISSUE TITLE
Mod Conflict: FPS is capped at 30 when used with Figura [SOLVED: Issue on Figura's side]

### ISSUE THREAD

**Issue by enchanted-sword** [DaFuqs/Spectrum#84]
Whenever I open a game instance also using Figura, the FPS is hard-capped at 30 during normal gameplay, even in a void with no entities or light updates. My FPS slider is set to unlimited, and it behaves as intended when I remove either mod.

A log file for my client can be found here: [https://pastebin.com/eTHtG6u6](url)

**Comment by Aquaeyes** [comment]
FPS is capped at 300 when I add spectrum to my modpack - as opposed to the 1100 it was getting otherwise.

**Comment by SollyW** [comment]
Please install [spark](https://spark.lucko.me/download), run `/sparkc profiler --timeout 15`, then share the results here

**Comment by enchanted-sword** [comment]
[https://spark.lucko.me/OEd4Va95vA](https://spark.lucko.me/OEd4Va95vA)

**Comment by DaFuqs** [comment]
The profiler seems to only report the server thread. Is there a -client parameter, or something?

**Comment by enchanted-sword** [comment]
I tried running the sparkclient command as opposed to the spark command
[https://spark.lucko.me/urgZhCQrRn](https://spark.lucko.me/urgZhCQrRn)

**Comment by ghost** [comment]
Is **Satin** the problem?
[https://github.com/Ladysnake/Satin/issues/23](url)

**Comment by enchanted-sword** [comment]
From what I can tell, Figura does not use the Satin API, and none of my other mods had similar conflicts.

**Comment by ghost** [comment]
> From what I can tell, Figura does not use the Satin API, and none of my other mods had similar conflicts.

**Spectrum** uses and includes **Satin**. Any mod that uses **Satin** with **Figura** will cause lag

**Comment by enchanted-sword** [comment]
Ah, I thought you were implicating the opposite case. That indeed solves it.
