### ISSUE TITLE
[BUG] Potion Workshop doesn't work when Minecraft is running on Java 17

### ISSUE THREAD

**Issue by Jenny77** [DaFuqs/Spectrum#86]
A couple of weeks ago I installed Java 17 and tried if it can make Minecraft with this mod run better,but as I tried using Potion Workshop,putting all the indegrients in,but it didn't work. Even if I unlocked all the achivements in the first part of this mod,and almost all in the second part,it still doesn't work.
So is this a bug or something else is required?

**Comment by DaFuqs** [comment]
I am using Java 17 and it is running perfectly fine. Recently I changed the Potion Workshops special new Potions to require having brewed a mundane vanilla potion first. Sadly I forgot to reflect this change in the guidebook. Maybe that is what is missing?

**Comment by Jenny77** [comment]
Oh,that's a forgivable reason! Be careful next time,and don't forget to update the manual if you modify any recipes and item mechanics!

**Comment by DaFuqs** [comment]
will do :)
