### ISSUE TITLE
[Feature] A config option to disable new moon for Onyx Crafting

### ISSUE THREAD

**Issue by AverageTurtle** [DaFuqs/Spectrum#87]
The title says it all pretty much. Would be nice and make the mod more playable on servers :D

**Comment by DaFuqs** [comment]
You can do that already, using a data pack. Modify the Onyx Shard recipe by removing the "new moon" world condition. https://github.com/DaFuqs/Spectrum/blob/1.18.2/src/main/resources/data/spectrum/recipes/fusion_shrine/onyx_shard.json

(why has every server ever sleep percentage at like 1 % though ಠಿ_ಠ)
