### ISSUE TITLE
[BUG] Client Crash when pressing shift on Amethyst Shards or other items to inspect it via Patchouli

### ISSUE THREAD

**Issue by DaFuqs** [DaFuqs/Spectrum#9]
**Describe the bug**
Inspecting some items via Patchouli crashes the client.

**To Reproduce**
Have an Amethyst Shard and the Spectrum manual in the inventory. Hold shift on the Amethyst Shard.

**Expected behavior**
The manual to open on the Amethyst Shards page in the book.
Instead, the client crashes with an error of "this.leftPage is null"

**Issue**
This is related to an issue in Patchouli itself.
Issue to track: https://github.com/VazkiiMods/Patchouli/issues/389

**Comment by feitan523** [comment]
> **Describe the bug** Inspecting some items via Patchouli crashes the client.
> 
> **To Reproduce** Have an Amethyst Shard and the Spectrum manual in the inventory. Hold shift on the Amethyst Shard.
> 
> **Expected behavior** The manual to open on the Amethyst Shards page in the book. Instead, the client crashes with an error of "this.leftPage is null"
> 
> **Issue** This is related to an issue in Patchouli itself. Issue to track: [VazkiiMods/Patchouli#389](https://github.com/VazkiiMods/Patchouli/issues/389)

Hey, I got the same error "this.leftPage is null" when I click (Shift-Click For Recipe) on Gunpowder

**Comment by DaFuqs** [comment]
I should have a workaround ready in the next update

**Comment by DaFuqs** [comment]
Fixed in 1.2.0
