### ISSUE TITLE
[BUG] Jade Vine Always Dies When Roots Spread to Second Oak Fence

### ISSUE THREAD

**Issue by boilpoil** [DaFuqs/Spectrum#91]
Trying to grow a jade vine, but found that it always died soon when roots spread upwards to a second oak fence, even when it was still the middle of the night (i.e. having never seen so much as a speck of sunlight)

**Comment by boilpoil** [comment]
This is running on All of Fabric 5, Java 17.0.1

**Comment by DaFuqs** [comment]
That is a first. Can you post a screenshot / have light emitting blocks close-by?
