### ISSUE TITLE
FPS is limited to 15 only spectrum installed

### ISSUE THREAD

**Issue by ghost** [DaFuqs/Spectrum#93]
The title says it. Besides, I also tried Spectrum with 77 mods and the fps are still at 15.
I tried the mod on another PC four times better than mine and the fps was 100.

I think the mod is not very optimized.

**CPU**: Intel i5-4590 (4) @ 3.700GHz
**GPU**: NVIDIA GeForce GT 610
**RAM**: 4G

**Comment by youmukonpaku1337** [comment]
errrr my friend has a gtx 710 and FPS is at 26 in fullscreen (and i'm quite sure the cause isn't spectrum)... get a better GPU

**Comment by youmukonpaku1337** [comment]
but let me see if it *is* spectrum

**Comment by youmukonpaku1337** [comment]
nope, spectrum does NOT affect FPS

**Comment by ghost** [comment]
In my Mod Pack I play at 60 FPS with Spectrum installed, it drops to 15.

**¿What would be the reason Spectrum needs a better GPU?**

**Comment by youmukonpaku1337** [comment]
first of all, you're running a 10 year old GPU and expecting minecraft to perform well
also, this is either a mod conflict, an old version of spectrum, or another mod

**Comment by youmukonpaku1337** [comment]
I'm running [my own modpack](https://modrinth.com/modpack/supercharged) at 100fps and it has spectrum installed, either your GPU sucks or you have a mod conflict

**Comment by youmukonpaku1337** [comment]
and my GPU is a quadro m1000m, equivalent to a GTX 660 in performance

**Comment by youmukonpaku1337** [comment]
do you have mods like sodium?

**Comment by ghost** [comment]
My modpack has almost all performance mods (Sodium, Lithium, Startlight, etc)

No mod conflicts as I tried Spectrum alone and same 15 FPS results.

**Comment by youmukonpaku1337** [comment]
check your settings, you might've set max FPS to 15 by accident, also make sure to disable vsync

**Comment by ghost** [comment]
**MY CONCLUSION**: To run Spectrum you must have a high performance PC.

**Comment by youmukonpaku1337** [comment]
check. your. settings.

**Comment by ghost** [comment]
None of that has anything to do with it. When installing the mod the fps go down to 15 when removing the mod they go up to 60

The problem is my PC.

**Comment by youmukonpaku1337** [comment]
is the FPS always locked at 15 or does it fluctuate?

**Comment by ghost** [comment]
The FPS will depend on the power of the PC.

One solution to the problem is to have a good PC or the other solution would be to improve the optimization of the mod.

**Comment by Jenny77** [comment]
And,if you installed too many mods,or limited the FPS in the options,that FPS would be limited. Try to toggle the FPS limit to "unlimited",if you do. Also,try to install mods that optmize the FPS,such as Ferrite Core.

**Comment by ghost** [comment]
> And,if you installed too many mods,or limited the FPS in the options,that FPS would be limited. Try to toggle the FPS limit to "unlimited",if you do. Also,try to install mods that optmize the FPS,such as Ferrite Core.

I have FerriteCore also set FPS to max, disabled various high impact sodium options. gave the same result 15 FPS.

And as I said in the description I tried it on a better PC than mine and the FPS was good, coming to my conclusion that the mod is not optimized or I'm wrong.

**Comment by enchanted-sword** [comment]
This is likely the same issue as #84. Check your mod list for incompatibilities.

**Comment by ghost** [comment]
> This is likely the same issue as #84. Check your mod list for incompatibilities.

- Spectrum without other mods 15 FPS
- Spectrum with other mods 15 FPS
- Without Spectrum alone or with mods 60 FPS

**Comment by DaFuqs** [comment]
Can you use the mod Spark and run a client performance profile, please? That should give us a lot of information on what's taking up all your PCs resources.

**Comment by ghost** [comment]
#

> Can you use the mod Spark and run a client performance profile, please? That should give us a lot of information on what's taking up all your PCs resources.

https://spark.lucko.me/zt3Q9gogAH : Running **/sparkc profiler**

**Comment by DaFuqs** [comment]
Sorry for only getting back to you now.
Your profile does not mention a performance impact by Spectrum in any way. While I believe you might still very well be correct, it seems I can not help you with that, sorry.
