### ISSUE TITLE
[Feature] Configurable Focus Bar position

### ISSUE THREAD

**Issue by recon88** [DaFuqs/Spectrum#94]
I would like to be able to configure the Focus Bar position because HWYLA usually takes the center top area already. A simple X and Y value should do it.
I could move HWYLA but I prefer to have Spectrum's bar somewhere else because it's not needed that often.

![dhXqe5v](https://user-images.githubusercontent.com/1056686/182098833-05753571-fa25-4055-8459-ab37b4eeec7f.png)

**Comment by DaFuqs** [comment]
Very valid request. I can see that being an issue.
The ghost blocks are a feature of Patchouli. Maybe there is a setting in it's config already? Otherwise open an issue at https://github.com/VazkiiMods/Patchouli/issues

**Comment by recon88** [comment]
Wait, why was it closed already? 
The ghost blocks aren't an issue, the focus bar is.

**Comment by DaFuqs** [comment]
The focus bar with the placed block counter of the multiblock structures is from Patchouli, too. (The one behind the HWYLA display in your screenshot)
Or did I misunderstand you?

**Comment by recon88** [comment]
Oh I see, didn't know the bar was also part of Patchouli. I guess I will ask in their Discord first.
