### ISSUE TITLE
[BUG] Natures' Staff does absolutely nothing

### ISSUE THREAD

**Issue by jotarosez** [DaFuqs/Spectrum#97]
Exactly as the title says. With 2 stacks of vegetal in my inventory, the only thing the staff does is produce music, instead of growing crops and saplings

Currently playing on All Of Fabric 5 1.3.1

**Comment by Jenny77** [comment]
Weird. That works exactly well for me. Maybe you're not pointing at the plant you wanted to grow,or you're trying to grow an Ominous Sapling with that!

**Comment by jotarosez** [comment]
So I tried testing this in both singleplayer and multiplayer: it works with the former, but not the latter? That's weird

There also doesn't seem to be anything affecting whether or not it works in the server's config file

**Comment by Jenny77** [comment]
Did you keep the version of this mod on your client the same with that in your server?

**Comment by jotarosez** [comment]
We are all using the exact same version of the mod, yeah

**Comment by Jenny77** [comment]
Oh! That seems like a bug! Found and reported!

**Comment by DaFuqs** [comment]
Fixed in next release

**Comment by DaFuqs** [comment]
Release released
